#pragma once

#define WAVETABLE_POOL_MAX_SLOTS       (64U)
#define WAVETABLE_POOL_INVALID_SLOT    (0xFFFFU)
#define WAVETABLE_FRAME_SAMPLE_COUNT   (1024U)
#define WAVETABLE_PREVIEW_COLUMNS      (124U)
#define WAVETABLE_MIPMAP_MAX_BANDS     (8U)
