#pragma once

#include <stdint.h>

typedef enum
{
    MOD_LFO_SHAPE_SINE = 0,
    MOD_LFO_SHAPE_TRIANGLE,
    MOD_LFO_SHAPE_SAW,
    MOD_LFO_SHAPE_SQUARE,
    MOD_LFO_SHAPE_RANDOM_SH,
    MOD_LFO_SHAPE_SINE_POS,
    MOD_LFO_SHAPE_TRIANGLE_POS,
    MOD_LFO_SHAPE_SQUARE_POS,
    MOD_LFO_SHAPE_REVERSE_SAW,
    MOD_LFO_SHAPE_COUNT
} mod_lfo_shape_t;

typedef enum
{
    MOD_LFO_TRIG_FREE = 0,
    MOD_LFO_TRIG_TRIG,
    MOD_LFO_TRIG_HOLD,
    MOD_LFO_TRIG_ONE,
    MOD_LFO_TRIG_POLY_TRIG,
    MOD_LFO_TRIG_POLY_HOLD,
    MOD_LFO_TRIG_POLY_ONE,
    MOD_LFO_TRIG_COUNT
} mod_lfo_trig_mode_t;

typedef enum
{
    MOD_LFO_PARAM_RATE = 0,
    MOD_LFO_PARAM_SHAPE,
    MOD_LFO_PARAM_TRIG,
    MOD_LFO_PARAM_PHASE,
    MOD_LFO_PARAM_COUNT
} mod_lfo_param_t;

#define MOD_LFO_COUNT_PER_TRACK 3U
#define MOD_LFO_POLY_SYNTH_SLOT_COUNT 16U
#define MOD_LFO_POLY_MULTI_SLOT_COUNT 8U
#define MOD_LFO_POLY_SLOT_COUNT \
    (MOD_LFO_POLY_SYNTH_SLOT_COUNT + MOD_LFO_POLY_MULTI_SLOT_COUNT)
#define LFO_FREE_MAX_HZ 80.0f
#define MOD_LFO_SYNC_RATE_COUNT 16U
