#include "Param/live_parameter_migration.h"

uint8_t live_parameter_is_audio_owned(param_id_t parameter)
{
    switch (parameter)
    {
        case PARAM_VCA_ATTACK:
        case PARAM_VCA_DECAY:
        case PARAM_VCA_SUSTAIN:
        case PARAM_VCA_RELEASE:
        case PARAM_EXTERNAL_TRIG:
        case PARAM_FILTER_MODE:
        case PARAM_FILTER_CUTOFF:
        case PARAM_FILTER_RESONANCE:
        case PARAM_MIX_LEVEL:
        case PARAM_MIX_PAN:
        case PARAM_MIX_SEND1:
        case PARAM_MIX_SEND2:
        case PARAM_MIX_SEND3:
        case PARAM_MIX_SEND0_FX:
        case PARAM_MIX_SEND1_FX:
        case PARAM_BUS_COMP_THRESHOLD_DB:
        case PARAM_BUS_COMP_RATIO:
        case PARAM_BUS_COMP_ATTACK_INDEX:
        case PARAM_BUS_COMP_RELEASE_INDEX:
        case PARAM_BUS_COMP_MAKEUP_DB:
        case PARAM_BUS_COMP_AUTO_MAKEUP:
        case PARAM_BUS_COMP_DRYWET:
        case PARAM_BUS_COMP_HPF_HZ:
        case PARAM_EQ_LOW_DB:
        case PARAM_EQ_MID_DB:
        case PARAM_EQ_HIGH_DB:
        case PARAM_SAT_TONE:
        case PARAM_SAT_BIAS:
        case PARAM_SAT_DRIVE:
        case PARAM_SAT_MIX:
        case PARAM_POST_GAIN:
        case PARAM_OUTPUT_COMP:
        case PARAM_COMP_MODEL:
        case PARAM_COMP_DETECT:
        case PARAM_COMP_KNEE_DB:
        case PARAM_COMP_DELUGE_SAT:
        case PARAM_AUDIO_FX_P1:
        case PARAM_AUDIO_FX_P2:
        case PARAM_AUDIO_FX_P3:
        case PARAM_AUDIO_FX_MODEL:
        case PARAM_AUDIO_FX_B_P1:
        case PARAM_AUDIO_FX_B_P2:
        case PARAM_AUDIO_FX_B_P3:
        case PARAM_AUDIO_FX_B_MODEL:
        case PARAM_GROUP_FX_A_LEVEL:
        case PARAM_GROUP_FX_B_LEVEL:
        case PARAM_WAVE_OSC1_POS:
        case PARAM_WAVE_OSC2_POS:
        case PARAM_WAVE_OSC1_START:
        case PARAM_WAVE_OSC2_START:
        case PARAM_WAVE_OSC1_LEN:
        case PARAM_WAVE_OSC2_LEN:
        case PARAM_WAVE_VOLUME:
        case PARAM_WAVE_BALANCE:
        case PARAM_WAVE_TUNE:
        case PARAM_WAVE_DETUNE:
        case PARAM_PRISM_VOLUME:
        case PARAM_PRISM_TUNE:
        case PARAM_PRISM_PITCH_MOD1:
        case PARAM_PRISM_OSC1_PARAM1:
        case PARAM_PRISM_OSC1_AMOD:
        case PARAM_PRISM_OSC1_PARAM2:
        case PARAM_PRISM_BALANCE:
        case PARAM_PRISM_DETUNE:
        case PARAM_PRISM_DRIFT:
        case PARAM_PRISM_PITCH_MOD2:
        case PARAM_PRISM_OSC2_PARAM1:
        case PARAM_PRISM_OSC2_AMOD:
        case PARAM_PRISM_OSC2_PARAM2:
        case PARAM_STACK_OSC1_LEVEL:
        case PARAM_STACK_OSC2_LEVEL:
        case PARAM_STACK_OSC3_LEVEL:
        case PARAM_STACK_NOISE_LEVEL:
        case PARAM_STACK_OSC1_TUNE:
        case PARAM_STACK_OSC1_TIMBRE:
        case PARAM_STACK_OSC1_COLOR:
        case PARAM_STACK_OSC2_TUNE:
        case PARAM_STACK_OSC2_TIMBRE:
        case PARAM_STACK_OSC2_COLOR:
        case PARAM_STACK_OSC3_TUNE:
        case PARAM_STACK_OSC3_TIMBRE:
        case PARAM_STACK_OSC3_COLOR:
        case PARAM_STACK_OSC_DETUNE:
        case PARAM_MIX_REVERB_WET:
        case PARAM_MODFX_MODEL:
        case PARAM_MODFX_RATE:
        case PARAM_MODFX_DEPTH:
        case PARAM_MODFX_FEEDBACK:
        case PARAM_MODFX_OFFSET:
        case PARAM_MODFX_RATE_B:
        case PARAM_MODFX_DELAY_B:
        case PARAM_MODFX_DEPTH_B:
        case PARAM_MODFX_WIDTH:
        case PARAM_MIX_REVERB_ROOM_SIZE:
        case PARAM_MIX_REVERB_DAMPING:
        case PARAM_MIX_REVERB_WIDTH:
        case PARAM_MIX_REVERB_HPF:
        case PARAM_MIX_REVERB_LPF:
        case PARAM_MIX_REVERB_DELAYS:
        case PARAM_MIX_DELAY_TYPE:
        case PARAM_MIX_DELAY_MODE:
        case PARAM_MIX_DELAY_TIME:
        case PARAM_MIX_DELAY_TIME_R:
        case PARAM_MIX_DELAY_PINGPONG:
        case PARAM_MIX_DELAY_WIDTH:
        case PARAM_MIX_DELAY_FEEDBACK:
        case PARAM_MIX_DELAY_SPECTRAL_POSITION:
        case PARAM_MIX_DELAY_SPECTRAL_WIDTH:
        case PARAM_MIX_DELAY_FBW:
        case PARAM_MIX_DELAY_MOD:
        case PARAM_MIX_DELAY_MOD_RATE:
        case PARAM_MIX_DELAY_REV:
        case PARAM_MIX_DELAY_VOL:
            return 1U;
        default:
            return 0U;
    }
}
