#ifndef TRACK_TYPES_H
#define TRACK_TYPES_H

#include <stdint.h>

#include "Track/entity_types.h"

#define TRACK_COUNT BRICK_ENTITY_TOP_LEVEL_COUNT
#define TRACK_ACTIVE_COUNT BRICK_ENTITY_TOP_LEVEL_COUNT
#define TRACK_AUDIO_INPUT_RESOURCE_COUNT ENTITY_TOPOLOGY_PHYSICAL_INPUT_COUNT
#define TRACK_AUDIO_INPUT_PROTO_WIRED_COUNT ENTITY_TOPOLOGY_PHYSICAL_INPUT_COUNT
#define BRICK6_MAX_CLIP_TRACKS 4U

typedef enum
{
    TRACK_FAMILY_OFF = 0,
    TRACK_FAMILY_SYNTH = 4,
    TRACK_FAMILY_DRUM = 5,
    TRACK_FAMILY_MIDI = 6,
    TRACK_FAMILY_SAMPLER = 7,
    TRACK_FAMILY_EXTERNAL = 8,
    TRACK_FAMILY_COUNT
} track_family_t;

typedef enum
{
    TRACK_TYPE_NONE = 0,
    TRACK_TYPE_RAM,
    TRACK_TYPE_PRISM,
    TRACK_TYPE_DRUM_MD,
    TRACK_TYPE_MIDI,
    TRACK_TYPE_STREAM,
    TRACK_TYPE_DRUM_BD_ANALOG,
    TRACK_TYPE_LOOPER,
    TRACK_TYPE_MULTI,
    TRACK_TYPE_STACK,
    TRACK_TYPE_WAVE,
    TRACK_TYPE_EXTERNAL,
    TRACK_TYPE_GROUP,
    TRACK_TYPE_FM,
    TRACK_TYPE_COUNT
} track_type_t;

typedef struct
{
    track_family_t family;
    track_type_t type;
} track_config_t;

/* Pure CONTROL/AUDIO vocabulary.  Selection policy remains in
 * track_runtime.c; AUDIO only consumes the resolved value carried by PROGRAM. */
typedef enum
{
    TRACK_RUNTIME_ENGINE_NONE = 0,
    TRACK_RUNTIME_ENGINE_AUDIO_TRACK,
    TRACK_RUNTIME_ENGINE_SAMPLER,
    TRACK_RUNTIME_ENGINE_LOOPER,
    TRACK_RUNTIME_ENGINE_PRISM,
    TRACK_RUNTIME_ENGINE_DRUM,
    TRACK_RUNTIME_ENGINE_STACK,
    TRACK_RUNTIME_ENGINE_WAVE,
    TRACK_RUNTIME_ENGINE_FM,
    TRACK_RUNTIME_ENGINE_COUNT
} track_runtime_engine_t;

typedef enum
{
    TRACK_RUNTIME_FAMILY_OFF = 0,
    TRACK_RUNTIME_FAMILY_SYNTH,
    TRACK_RUNTIME_FAMILY_SAMPLER,
    TRACK_RUNTIME_FAMILY_DRUM,
    TRACK_RUNTIME_FAMILY_MIDI,
    TRACK_RUNTIME_FAMILY_EXTERNAL,
    TRACK_RUNTIME_FAMILY_OTHER
} track_runtime_family_t;

typedef enum
{
    TRACK_RUNTIME_TYPE_NONE = 0,
    TRACK_RUNTIME_TYPE_RAM,
    TRACK_RUNTIME_TYPE_PRISM,
    TRACK_RUNTIME_TYPE_DRUM_MD,
    TRACK_RUNTIME_TYPE_MIDI,
    TRACK_RUNTIME_TYPE_STREAM,
    TRACK_RUNTIME_TYPE_DRUM_BD_ANALOG,
    TRACK_RUNTIME_TYPE_LOOPER,
    TRACK_RUNTIME_TYPE_MULTI,
    TRACK_RUNTIME_TYPE_STACK,
    TRACK_RUNTIME_TYPE_WAVE,
    TRACK_RUNTIME_TYPE_EXTERNAL,
    TRACK_RUNTIME_TYPE_GROUP,
    TRACK_RUNTIME_TYPE_FM,
    TRACK_RUNTIME_TYPE_OTHER
} track_runtime_type_t;

typedef enum
{
    TRACK_MIDI_SOURCE_INTERNAL = 0,
    TRACK_MIDI_SOURCE_EXTERNAL,
    TRACK_MIDI_SOURCE_ALL,
    TRACK_MIDI_SOURCE_COUNT
} track_midi_source_t;


#endif /* TRACK_TYPES_H */
