#ifndef NOTE_FX_CONTRACT_H
#define NOTE_FX_CONTRACT_H

#define NOTE_FX_SLOT_COUNT 4U
#define NOTE_FX_PARAM_COUNT 4U
#define NOTE_FX_CANONICAL_PARAM_COUNT \
    (NOTE_FX_SLOT_COUNT * NOTE_FX_PARAM_COUNT)

#endif
