#ifndef NOTE_FX_CONTRACT_H
#define NOTE_FX_CONTRACT_H

#define NOTE_FX_SLOT_COUNT 3U
#define NOTE_FX_PARAM_COUNT 4U
#define NOTE_FX_VALUE_COUNT (NOTE_FX_PARAM_COUNT + 1U)
#define NOTE_FX_MODEL_INDEX NOTE_FX_PARAM_COUNT
#define NOTE_FX_ORDER_COUNT 6U
#define NOTE_FX_CANONICAL_PARAM_COUNT \
    (NOTE_FX_SLOT_COUNT * NOTE_FX_VALUE_COUNT + 1U)

#endif
