#ifndef SEQ_NOTE_PATH_DEBUG_H
#define SEQ_NOTE_PATH_DEBUG_H

#include <stdint.h>

/* Diagnostic-only counters.  Read with GDB; they do not participate in
 * transport, scheduling, admission, or publication decisions. */
typedef enum
{
    SEQ_NOTE_DBG_RUNTIME_SCHEDULE_ENTRY = 0,
    SEQ_NOTE_DBG_RUNTIME_TOPOLOGY_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_ENTRY,
    SEQ_NOTE_DBG_SCHEDULER_TOPOLOGY_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_CAPABILITY_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_CONTEXT_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_INACTIVE_STEP,
    SEQ_NOTE_DBG_SCHEDULER_STORE_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_PLAY_READ_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_VELOCITY_REJECT,
    SEQ_NOTE_DBG_SCHEDULER_NOTE_REJECT,
    SEQ_NOTE_DBG_SOURCE_ACCEPT,
    SEQ_NOTE_DBG_SOURCE_REJECT,
    SEQ_NOTE_DBG_IMMINENT_NOTE_ON,
    SEQ_NOTE_DBG_COLLECTED_NOTE_ON,
    SEQ_NOTE_DBG_APPLY_NOTE_ON,
    SEQ_NOTE_DBG_APPLY_STALE_REJECT,
    SEQ_NOTE_DBG_APPLY_MUTE_REJECT,
    SEQ_NOTE_DBG_NOTE_FX_ACCEPT,
    SEQ_NOTE_DBG_NOTE_FX_REJECT,
    SEQ_NOTE_DBG_NOTE_FX_TERMINAL,
    SEQ_NOTE_DBG_OUTPUT_ACCEPT,
    SEQ_NOTE_DBG_OUTPUT_REJECT,
    SEQ_NOTE_DBG_PUBLICATION_ACTIONS,
    SEQ_NOTE_DBG_PUBLICATION_ACCEPT,
    SEQ_NOTE_DBG_PUBLICATION_REJECT,
    SEQ_NOTE_DBG_LAST_TRACK_STEP,
    SEQ_NOTE_DBG_LAST_NOTE,
    SEQ_NOTE_DBG_LAST_SAMPLE_LO,
    SEQ_NOTE_DBG_LAST_SAMPLE_HI,
    SEQ_NOTE_DBG_COUNT
} seq_note_path_debug_index_t;

extern volatile uint32_t g_seq_note_path_debug[SEQ_NOTE_DBG_COUNT];

#endif
