CXX ?= g++
CXXFLAGS ?= -std=c++17 -O2 -Wall -Wextra -pedantic

CPPFLAGS += -DMICRODEXED_MINIMAL -I.

CORE_SOURCES = \
	EngineMkI.cpp \
	PluginFx.cpp \
	dexed.cpp \
	dx7note.cpp \
	env.cpp \
	exp2.cpp \
	fm_core.cpp \
	fm_op_kernel.cpp \
	freqlut.cpp \
	lfo.cpp \
	pitchenv.cpp \
	porta.cpp \
	sin.cpp \
	microdexed_marki_minimal.cpp

SMOKE_SOURCES = microdexed_marki_smoke.cpp

all: smoke

smoke: microdexed_marki_smoke

microdexed_marki_smoke: $(CORE_SOURCES:.cpp=.o) $(SMOKE_SOURCES:.cpp=.o)
	$(CXX) $(CXXFLAGS) $^ -o $@

clean:
	rm -f *.o microdexed_marki_smoke

.PHONY: all smoke clean
