#include "NoteFx/note_fx_engine.h"
#include <string.h>
#include "Keyboard/keyboard_params.h"
#include "NoteFx/note_fx_euclid.h"
#include "NoteFx/note_fx_context.h"
#include "Seq/seq_division_catalog.h"
#include "Platform/memory_layout.h"

typedef struct { uint32_t source_token,occurrence_id,generation,group_id,lifetime_end;uint8_t note,velocity,dependency_mask,routing; } note_fx_held_pitch_t;
typedef struct { note_fx_held_pitch_t held[NOTE_FX_HELD_PITCH_CAPACITY];uint16_t dependency_versions;uint8_t held_count,model,p1,p2,p3; } note_fx_slot_runtime_t;
typedef struct { int8_t timing[8],velocity[8]; } note_fx_groove_template_t;

static const note_fx_groove_template_t g_groove[NOTE_FX_GROOVE_TYPE_COUNT]={
 {{0,24,0,24,0,24,0,24},{12,-8,8,-8,12,-8,8,-8}},
 {{0,32,0,32,0,32,0,32},{10,-12,6,-12,10,-12,6,-12}},
 {{0,12,-5,18,0,10,-4,16},{16,-10,5,-7,13,-9,4,-6}},
 {{0,18,-8,10,4,22,-6,12},{18,-14,8,-5,12,-12,7,-4}}};
static const uint8_t g_harmony[NOTE_FX_HARMONIZER_TYPE_COUNT][4]={
 {0,4,7,255},{0,3,7,255},{0,5,7,255},{0,2,7,255},
 {0,4,7,10},{0,4,7,11},{0,3,6,10},{0,4,8,255}};
static const uint8_t g_scale_count[7]={7,7,7,7,5,5,12};
static const uint8_t g_scale[7][12]={{0,2,4,5,7,9,11},{0,2,3,5,7,8,10},
 {0,2,3,5,7,9,10},{0,2,4,5,7,9,10},{0,2,4,7,9},{0,3,5,7,10},
 {0,1,2,3,4,5,6,7,8,9,10,11}};
_Static_assert(sizeof(note_fx_slot_runtime_t)<=224U,"Note FX slot runtime budget");
_Static_assert(sizeof(g_groove)==64U,"Groove table proof");
_Static_assert(sizeof(g_harmony)==32U,"Harmony table proof");

typedef struct { note_fx_slot_runtime_t slot[NOTE_FX_TRACK_COUNT][NOTE_FX_SLOT_COUNT];
 uint64_t work_slot_mask;uint32_t token,samples_per_step_q16;uint8_t rt_mode;
 uint64_t transport_position_q16,block_start;uint32_t pattern_position_q16[NOTE_FX_TRACK_COUNT];
 uint8_t scale_index,root_index;
} note_fx_engine_context_t;
CONTROL_STATE_SDRAM static note_fx_engine_context_t g_control_context;
static CONTROL_M4_SRAM2 note_fx_engine_context_t g_rt_context;
static note_fx_engine_context_t *g_context=&g_control_context;
#define g_slot (g_context->slot)
#define g_work_slot_mask (g_context->work_slot_mask)
#define g_token (g_context->token)
#define g_samples_per_step_q16 (g_context->samples_per_step_q16)
static uint64_t slot_bit(uint8_t t,uint8_t s){return UINT64_C(1)<<((uint32_t)t*NOTE_FX_SLOT_COUNT+s);}
static uint8_t model_is_arp(uint8_t model){return (model==NOTE_FX_MODEL_ARP_FREE||model==NOTE_FX_MODEL_ARP_SYNC)?1U:0U;}
static uint8_t model_is_generator(uint8_t model){return (model_is_arp(model)||model==NOTE_FX_MODEL_EUCLID)?1U:0U;}
static uint8_t model_needs_held(uint8_t model){return (model_is_generator(model)||model==NOTE_FX_MODEL_CHORD||model==NOTE_FX_MODEL_HARMONIZER)?1U:0U;}
static uint8_t held_destination(const note_fx_held_pitch_t*h){return(uint8_t)(h->routing&0x0FU);}
static uint8_t held_temporal_index(const note_fx_held_pitch_t*h){return(uint8_t)((h->routing>>4U)&0x03U);}
static uint8_t held_has_deadline(const note_fx_held_pitch_t*h){return(uint8_t)((h->routing&0x40U)!=0U);}
static uint8_t held_deadline_reached(const note_fx_held_pitch_t*h,uint64_t sample){return(uint8_t)(held_has_deadline(h)&&((int32_t)((uint32_t)sample-h->lifetime_end)>=0));}
static uint32_t held_remaining(const note_fx_held_pitch_t*h,uint64_t sample,uint32_t fallback){if(!held_has_deadline(h))return fallback;const uint32_t remaining=h->lifetime_end-(uint32_t)sample;return remaining<fallback?remaining:fallback;}
static uint8_t provenance_from_source(uint32_t source){switch(source&~NOTE_EVENT_OCCURRENCE_COUNTER_MASK){case NOTE_EVENT_OCCURRENCE_NAMESPACE_KEY:return NOTE_EVENT_SOURCE_KEY;case NOTE_EVENT_OCCURRENCE_NAMESPACE_MIDI:return NOTE_EVENT_SOURCE_MIDI;case NOTE_EVENT_OCCURRENCE_NAMESPACE_FX:return NOTE_EVENT_SOURCE_FX;default:return NOTE_EVENT_SOURCE_STEP;}}
static uint16_t selected_versions(uint16_t versions,uint8_t mask){uint16_t selected=0U;for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s)if((mask&(uint8_t)(1U<<s))!=0U)selected|=(uint16_t)(versions&(uint16_t)(0x0FU<<(s*4U)));return selected;}
static void refresh_work(uint8_t t,uint8_t s){const uint64_t b=slot_bit(t,s);if((model_is_arp(g_slot[t][s].model)||g_slot[t][s].model==NOTE_FX_MODEL_EUCLID)&&g_slot[t][s].held_count)g_work_slot_mask|=b;else g_work_slot_mask&=~b;}
static uint32_t next_token(void){g_token=(g_token+1U)&NOTE_EVENT_OCCURRENCE_COUNTER_MASK;if(!g_token)g_token=1U;return NOTE_EVENT_OCCURRENCE_NAMESPACE_FX|g_token;}
static uint32_t mix32(uint32_t x){x^=x>>16;x*=UINT32_C(0x7FEB352D);x^=x>>15;x*=UINT32_C(0x846CA68B);return x^(x>>16);}
static uint32_t child_id(uint32_t p,uint8_t s,uint8_t v,uint8_t r){uint32_t x=mix32(p^((uint32_t)(s+1U)<<24)^((uint32_t)(v+1U)<<12)^((uint32_t)(r+1U)<<4))&NOTE_EVENT_OCCURRENCE_COUNTER_MASK;if(!x)x=1U;return NOTE_EVENT_OCCURRENCE_NAMESPACE_FX|x;}
static int8_t held_find(const note_fx_slot_runtime_t*r,const note_event_t*e){for(uint8_t i=0;i<r->held_count;++i)if(r->held[i].occurrence_id==e->intent_id&&r->held[i].generation==e->source_generation&&r->held[i].source_token==e->source_id)return(int8_t)i;return-1;}
static void held_remove(note_fx_slot_runtime_t*r,uint8_t i){if(i>=r->held_count)return;--r->held_count;r->held[i]=r->held[r->held_count];memset(&r->held[r->held_count],0,sizeof(r->held[0]));}
static note_event_result_t held_ingest(note_fx_slot_runtime_t*r,const note_event_t*e){const int8_t f=held_find(r,e);if(e->kind==NOTE_EVENT_KIND_OFF){if(f>=0)held_remove(r,(uint8_t)f);return NOTE_EVENT_RESULT_ACCEPTED;}uint8_t i;if(f>=0)i=(uint8_t)f;else{if(r->held_count>=NOTE_FX_HELD_PITCH_CAPACITY)return NOTE_EVENT_RESULT_REJECTED_CAPACITY;i=r->held_count++;}const uint8_t has_deadline=(uint8_t)(e->duration_samples!=NOTE_EVENT_DURATION_OPEN);r->held[i]=(note_fx_held_pitch_t){e->source_id,e->intent_id,e->source_generation,e->group_id,has_deadline?(uint32_t)(e->sample_abs+e->duration_samples):0U,e->note,e->velocity,e->dependency_mask,(uint8_t)((e->destination_id&0x0FU)|((e->temporal_index&0x03U)<<4U)|(has_deadline?0x40U:0U))};return NOTE_EVENT_RESULT_ACCEPTED;}
static void held_expire(note_fx_slot_runtime_t*r,uint64_t sample){uint8_t i=0U;while(i<r->held_count){if(held_deadline_reached(&r->held[i],sample))held_remove(r,i);else++i;}}
static uint8_t held_sorted(const note_fx_slot_runtime_t*r,uint8_t rank){uint8_t used=0,sel=0;for(uint8_t k=0;k<=rank;++k){uint8_t best=UINT8_MAX;for(uint8_t i=0;i<r->held_count;++i)if(!(used&(1U<<i))&&(best==UINT8_MAX||r->held[i].note<r->held[best].note))best=i;sel=best;used|=(uint8_t)(1U<<best);}return sel;}
static uint8_t arp_select(note_fx_slot_runtime_t*r,uint32_t step,uint8_t track,uint8_t slot,note_fx_held_pitch_t**oh,uint8_t*on){if(!r->held_count||!oh||!on)return 0;const note_fx_arp_style_t style=(note_fx_arp_style_t)r->p2;uint8_t rank;if(style==NOTE_FX_ARP_RANDOM){rank=(uint8_t)(mix32(step^((uint32_t)track<<24)^((uint32_t)slot<<16)^UINT32_C(0x9E3779B9))%r->held_count);}else if(style==NOTE_FX_ARP_UP_DOWN&&r->held_count>1U){const uint8_t cycle=(uint8_t)(2U*r->held_count-2U),pos=(uint8_t)(step%cycle);rank=pos<r->held_count?pos:(uint8_t)(cycle-pos);}else{rank=(uint8_t)(step%r->held_count);if(style==NOTE_FX_ARP_DOWN)rank=(uint8_t)(r->held_count-1U-rank);}const uint8_t i=style==NOTE_FX_ARP_ORDER?rank:held_sorted(r,rank);note_fx_held_pitch_t*h=&r->held[i];const uint8_t range=r->p3>=1&&r->p3<=4?r->p3:1;const uint32_t cycle=style==NOTE_FX_ARP_UP_DOWN&&r->held_count>1?(uint32_t)(2U*r->held_count-2U):r->held_count;const uint16_t raised=(uint16_t)h->note+(uint16_t)(12U*((step/cycle)%range));*on=raised<128U?(uint8_t)raised:h->note;*oh=h;return 1;}
static note_event_result_t emit_generated(uint8_t t,uint8_t s,const note_fx_held_pitch_t*h,uint8_t n,uint64_t sample,uint64_t duration,note_fx_emit_fn emit,void*ctx){if(!emit)return NOTE_EVENT_RESULT_ACCEPTED;const uint32_t token=next_token();const uint8_t mask=(uint8_t)(h->dependency_mask|(uint8_t)(1U<<s));const uint32_t bounded_duration=held_remaining(h,sample,duration>UINT32_MAX?UINT32_MAX:(uint32_t)duration);const note_event_t e={.sample_abs=sample,.duration_samples=bounded_duration,.source_id=h->source_token,.intent_id=token,.source_generation=h->generation,.group_id=h->group_id?h->group_id:token,.dependency_versions=selected_versions(g_slot[t][s].dependency_versions,mask),.track=t,.destination_id=held_destination(h),.note=n,.velocity=h->velocity,.kind=NOTE_EVENT_KIND_ON,.provenance=NOTE_EVENT_SOURCE_FX,.stage=(uint8_t)(s+1U),.flags=NOTE_EVENT_FLAG_GENERATED,.temporal_index=held_temporal_index(h),.dependency_mask=mask};return emit(&e,ctx);}
static uint8_t append(note_event_t*out,uint8_t cap,uint8_t*count,const note_event_t*e,uint8_t stage){if(*count>=cap)return 0;out[*count]=*e;out[*count].stage=stage;++*count;return 1;}
static uint64_t step_samples(void){const uint64_t x=((uint64_t)g_samples_per_step_q16+0x8000ULL)>>16;return x?x:1U;}
static uint8_t groove_phase(uint8_t track,uint64_t sample_abs){uint64_t position;if(g_context->rt_mode!=0U){const uint64_t step=step_samples();const uint64_t delta=(sample_abs>=g_context->block_start)?sample_abs-g_context->block_start:0U;position=g_context->pattern_position_q16[track]+(delta<<16U)/step;}else{seq_musical_time_t time;if(seq_runtime_get_musical_time(track,sample_abs,&time)==0U)return 0U;position=time.pattern_position_q16;}return(uint8_t)((position*6ULL>>16U)%8ULL);}
static uint8_t probability_pass(const note_fx_slot_runtime_t*r,const note_event_t*e,uint8_t slot){static const uint8_t num[10]={0,1,2,1,2,3,1,2,3,4},den[10]={1,2,2,3,3,3,4,4,4,4};if(e->kind==NOTE_EVENT_KIND_OFF)return 1U;const uint8_t c=r->p2<10?r->p2:0;uint64_t identity=e->group_id;if(r->p3){const uint64_t p=seq_division_period_samples((uint8_t)(r->p3-1U),g_samples_per_step_q16);identity=e->sample_abs/(p?p:1U);}const uint64_t cycle=e->sample_abs/(step_samples()*16ULL);if(c&&((uint8_t)(cycle%den[c])+1U)!=num[c])return 0;if(r->p1>=100)return 1;if(!r->p1)return 0;return(uint8_t)((mix32((uint32_t)identity^(uint32_t)(identity>>32)^((uint32_t)e->track<<24)^((uint32_t)slot<<16)^(uint32_t)cycle)%100U)<r->p1);}
static uint8_t scale_shift(uint8_t note,int8_t shift){uint8_t sc=g_context->rt_mode?g_context->scale_index:keyboard_params_get_scale_index();if(sc>=7)sc=0;const uint8_t root=(g_context->rt_mode?g_context->root_index:keyboard_params_get_root_index())%12U,count=g_scale_count[sc];int16_t best=0;uint8_t dist=255;for(int16_t d=-12;d<128;++d){int16_t oct=d/(int16_t)count,idx=d%(int16_t)count;if(idx<0){idx+=count;--oct;}const int16_t cand=(int16_t)root+g_scale[sc][idx]+12*oct;const uint8_t dd=(uint8_t)(cand>note?cand-note:note-cand);if(dd<dist){dist=dd;best=d;if(!dd)break;}}int16_t d=best+shift,oct=d/(int16_t)count,idx=d%(int16_t)count;if(idx<0){idx+=count;--oct;}int16_t target=(int16_t)root+g_scale[sc][idx]+12*oct;while(target<0)target+=12;while(target>127)target-=12;return(uint8_t)target;}

static note_event_result_t direct(uint8_t slot,note_fx_slot_runtime_t*r,const note_event_t*e,note_event_t*out,uint8_t cap,uint8_t*count){const uint8_t stage=(uint8_t)(slot+1U);
 if(r->model==NOTE_FX_MODEL_PROBABILITY){const uint8_t pass=probability_pass(r,e,slot);return!pass?NOTE_EVENT_RESULT_ACCEPTED:(append(out,cap,count,e,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY);}
 if(r->model==NOTE_FX_MODEL_GROOVE){note_event_t x=*e;const uint8_t phase=groove_phase(e->track,e->sample_abs);const note_fx_groove_template_t*t=&g_groove[r->p1%NOTE_FX_GROOVE_TYPE_COUNT];const int64_t off=((int64_t)t->timing[phase]*(int64_t)step_samples()*r->p2)/(96LL*100LL);x.sample_abs=(off<0&&x.sample_abs<(uint64_t)(-off))?0U:(uint64_t)((int64_t)x.sample_abs+off);if(x.kind==NOTE_EVENT_KIND_ON){int32_t v=x.velocity+((int32_t)t->velocity[phase]*x.velocity*r->p3)/10000;if(v<1)v=1;if(v>127)v=127;x.velocity=(uint8_t)v;}return append(out,cap,count,&x,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY;}
 if(r->model==NOTE_FX_MODEL_ECHO){if(!append(out,cap,count,e,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;const uint64_t period=seq_division_period_samples(r->p1,g_samples_per_step_q16);for(uint8_t rep=1;rep<=r->p2;++rep){note_event_t x=*e;x.sample_abs+=(uint64_t)rep*period;x.occurrence_id=child_id(e->occurrence_id,slot,0,rep);x.group_id=mix32(e->group_id^((uint32_t)slot<<24)^rep);if(!x.group_id)x.group_id=1;x.provenance=NOTE_EVENT_SOURCE_FX;x.flags|=(NOTE_EVENT_FLAG_GENERATED|NOTE_EVENT_FLAG_FUTURE|NOTE_EVENT_FLAG_ECHO);x.temporal_index=rep;if(x.kind==NOTE_EVENT_KIND_ON){uint32_t v=x.velocity;for(uint8_t n=0;n<rep;++n)v=(v*(100U-r->p3)+50U)/100U;if(!v)v=1;x.velocity=(uint8_t)v;}if(!append(out,cap,count,&x,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;}return NOTE_EVENT_RESULT_ACCEPTED;}
 if(r->model==NOTE_FX_MODEL_GATE){if(e->kind==NOTE_EVENT_KIND_OFF)return NOTE_EVENT_RESULT_ACCEPTED;note_event_t on=*e;on.flags|=NOTE_EVENT_FLAG_GATE;if(r->p3==NOTE_FX_GATE_MODE_LEGATO)on.flags|=NOTE_EVENT_FLAG_LEGATO;else if(r->p3==NOTE_FX_GATE_MODE_RETRIG)on.flags|=NOTE_EVENT_FLAG_RETRIGGER;int32_t var=0;if(r->p2){const uint32_t h=mix32(e->group_id^((uint32_t)slot<<24));var=(int32_t)(h%(2U*r->p2+1U))-(int32_t)r->p2;}int32_t pct=(int32_t)r->p1+var;if(pct<1)pct=1;if(r->p3==NOTE_FX_GATE_MODE_CLIP&&pct>100)pct=100;on.duration_samples=(uint32_t)(((uint64_t)pct*step_samples()+50U)/100U);return append(out,cap,count,&on,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY;}
 if(r->model==NOTE_FX_MODEL_HARMONIZER){uint8_t emitted=0;for(uint8_t voice=0;voice<4;++voice){uint8_t interval=g_harmony[r->p1%NOTE_FX_HARMONIZER_TYPE_COUNT][voice];if(interval==255)continue;if(voice<r->p3)interval=(uint8_t)(interval+12U);if(r->p2&&voice)interval=(uint8_t)(interval+12U*(1U+(uint8_t)((voice-1U)%r->p2)));if((uint16_t)e->note+interval>=128)continue;note_event_t x=*e;x.note=(uint8_t)(e->note+interval);if(voice){x.occurrence_id=child_id(e->occurrence_id,slot,voice,0);x.provenance=NOTE_EVENT_SOURCE_FX;x.flags|=NOTE_EVENT_FLAG_GENERATED;}uint8_t dup=0;for(uint8_t i=0;i<*count;++i)if(out[i].destination_id==x.destination_id&&out[i].note==x.note)dup=1;if(!dup){if(!append(out,cap,count,&x,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;++emitted;}}return emitted?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_DROPPED_POLICY;}
 return append(out,cap,count,e,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY;}

static note_event_result_t chord_group(uint8_t slot,note_fx_slot_runtime_t*r,
 const note_event_t*in,uint8_t n,note_event_t*out,uint8_t cap,uint8_t*count){
 const uint8_t stage=(uint8_t)(slot+1U);*count=0;
 for(uint8_t i=0;i<n;++i){note_event_t x=in[i];x.note=scale_shift(x.note,(int8_t)r->p1-7);
  uint8_t duplicate=0;for(uint8_t j=0;j<*count;++j)if(out[j].destination_id==x.destination_id&&out[j].note==x.note)duplicate=1;
  if(!duplicate&&!append(out,cap,count,&x,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;}
 for(uint8_t i=1;i<*count;++i){note_event_t x=out[i];uint8_t j=i;while(j&&out[j-1U].note>x.note){out[j]=out[j-1U];--j;}out[j]=x;}
 const uint8_t invert=(r->p3<*count)?r->p3:*count;
 for(uint8_t i=0;i<*count;++i){uint16_t note=out[i].note;
  if(i<invert)note+=12U;
  if(r->p2!=0U)note+=(uint16_t)(12U*(i%(uint8_t)(r->p2+1U)));
  while(note>127U&&note>=12U)note-=12U;
  out[i].note=(uint8_t)note;}
 uint8_t write=0;for(uint8_t i=0;i<*count;++i){uint8_t duplicate=0;for(uint8_t j=0;j<write;++j)if(out[j].destination_id==out[i].destination_id&&out[j].note==out[i].note)duplicate=1;if(!duplicate)out[write++]=out[i];}
 *count=write;return write?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_DROPPED_POLICY;}

void note_fx_engine_init(void){memset(&g_control_context,0,sizeof(g_control_context));g_control_context.samples_per_step_q16=UINT32_C(65536);g_context=&g_control_context;}
void note_fx_engine_set_samples_per_step_q16(uint32_t v){g_samples_per_step_q16=v?v:1U;}
note_event_result_t note_fx_engine_configure(uint8_t t,uint8_t s,uint8_t model,uint8_t p1,uint8_t p2,uint8_t p3,uint16_t dependency_versions){if(t>=NOTE_FX_TRACK_COUNT||s>=NOTE_FX_SLOT_COUNT)return NOTE_EVENT_RESULT_DROPPED_POLICY;note_fx_slot_runtime_t*r=&g_slot[t][s];if(model>=NOTE_FX_MODEL_COUNT)model=NOTE_FX_MODEL_OFF;if(r->model!=model)memset(r,0,sizeof(*r));r->model=model;r->p1=p1;r->p2=p2;r->p3=p3;r->dependency_versions=dependency_versions;refresh_work(t,s);return NOTE_EVENT_RESULT_ACCEPTED;}
note_event_result_t note_fx_engine_transform(uint8_t s,const note_event_t*in,uint8_t n,note_event_t*out,uint8_t cap,uint8_t*count){if(!in||!out||!count||!n||s>=NOTE_FX_SLOT_COUNT)return NOTE_EVENT_RESULT_DROPPED_POLICY;for(uint8_t i=0;i<n;++i)if(!note_event_is_valid(&in[i])||in[i].track>=NOTE_FX_TRACK_COUNT||in[i].stage!=s||in[i].track!=in[0].track||in[i].group_id!=in[0].group_id||in[i].kind!=in[0].kind)return NOTE_EVENT_RESULT_DROPPED_POLICY;note_fx_slot_runtime_t*r=&g_slot[in[0].track][s];if(model_needs_held(r->model))for(uint8_t i=0;i<n;++i){const note_event_result_t held_result=held_ingest(r,&in[i]);if(held_result!=NOTE_EVENT_RESULT_ACCEPTED)return held_result;}refresh_work(in[0].track,s);if(r->model==NOTE_FX_MODEL_CHORD)return chord_group(s,r,in,n,out,cap,count);*count=0;for(uint8_t i=0;i<n;++i){const note_event_t*e=&in[i];if(!model_is_arp(r->model)&&r->model!=NOTE_FX_MODEL_EUCLID){const note_event_result_t result=direct(s,r,e,out,cap,count);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;}}return NOTE_EVENT_RESULT_ACCEPTED;}
note_event_result_t note_fx_engine_collect_held(uint8_t t,uint8_t s,uint64_t sample,note_event_t*out,uint8_t cap,uint8_t*count){if(t>=NOTE_FX_TRACK_COUNT||s>=NOTE_FX_SLOT_COUNT||!out||!count)return NOTE_EVENT_RESULT_DROPPED_POLICY;note_fx_slot_runtime_t*r=&g_slot[t][s];held_expire(r,sample);*count=0;if(r->held_count>cap)return NOTE_EVENT_RESULT_REJECTED_CAPACITY;for(uint8_t i=0;i<r->held_count;++i){const note_fx_held_pitch_t*h=&r->held[i];out[i]=(note_event_t){.sample_abs=sample,.duration_samples=held_has_deadline(h)?held_remaining(h,sample,UINT32_MAX):NOTE_EVENT_DURATION_OPEN,.source_token=h->source_token,.occurrence_id=h->occurrence_id,.generation=h->generation,.group_id=h->group_id,.dependency_versions=selected_versions(r->dependency_versions,h->dependency_mask),.track=t,.destination_id=held_destination(h),.note=h->note,.velocity=h->velocity,.kind=NOTE_EVENT_KIND_ON,.provenance=provenance_from_source(h->source_token),.stage=s,.flags=0U,.temporal_index=held_temporal_index(h),.dependency_mask=h->dependency_mask};++*count;}return NOTE_EVENT_RESULT_ACCEPTED;}
void note_fx_engine_forget_causal_source(uint8_t t,uint32_t source){if(t>=NOTE_FX_TRACK_COUNT||!source)return;for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[t][s];uint8_t i=0;while(i<r->held_count){if(r->held[i].source_token==source)held_remove(r,i);else++i;}refresh_work(t,s);}}
note_event_result_t note_fx_engine_process(uint64_t start,uint16_t frames,uint32_t sps,note_fx_emit_fn emit,void*ctx){note_fx_engine_set_samples_per_step_q16(sps);const uint64_t end=start+frames;uint64_t processed=0,work;while((work=(g_work_slot_mask&~processed))!=0){const uint32_t idx=(uint32_t)__builtin_ctzll(work);processed|=UINT64_C(1)<<idx;const uint8_t t=(uint8_t)(idx/NOTE_FX_SLOT_COUNT),s=(uint8_t)(idx%NOTE_FX_SLOT_COUNT);note_fx_slot_runtime_t*r=&g_slot[t][s];held_expire(r,start);refresh_work(t,s);if(!r->held_count||!model_is_generator(r->model))continue;uint64_t period=seq_division_period_samples(r->model==NOTE_FX_MODEL_EUCLID?r->p3:r->p1,sps);if(!period)period=1;const note_fx_phase_policy_t policy=(r->model==NOTE_FX_MODEL_ARP_FREE)?NOTE_FX_PHASE_TRANSPORT_FREE:NOTE_FX_PHASE_PATTERN_SYNC;uint64_t position;if(g_context->rt_mode!=0U)position=(policy==NOTE_FX_PHASE_TRANSPORT_FREE)?g_context->transport_position_q16:g_context->pattern_position_q16[t];else{seq_musical_time_t time;if(seq_runtime_get_musical_time(t,start,&time)==0U)return NOTE_EVENT_RESULT_DROPPED_POLICY;position=(policy==NOTE_FX_PHASE_TRANSPORT_FREE)?time.transport_position_q16:time.pattern_position_q16;}const uint64_t step_sample=step_samples();uint64_t period_q16=(period<<16U)/step_sample;if(!period_q16)period_q16=1U;uint32_t ordinal=(uint32_t)(position/period_q16);const uint64_t remainder=position%period_q16;uint64_t sample=start;if(remainder!=0U){const uint64_t remaining=period_q16-remainder;sample+=((remaining*step_sample)+UINT16_MAX)>>16U;++ordinal;}while(sample<end){held_expire(r,sample);if(!r->held_count)break;if(model_is_arp(r->model)){note_fx_held_pitch_t*h=NULL;uint8_t note=0;if(arp_select(r,ordinal,t,s,&h,&note)){const note_event_result_t result=emit_generated(t,s,h,note,sample,period,emit,ctx);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;}}else{const uint8_t length=r->p1?r->p1:NOTE_FX_EUCLID_LENGTH_DEFAULT,pulse=r->p2<=length?r->p2:length;const uint64_t mask=euclid_build_mask(length,pulse);if((mask>>(ordinal%length))&UINT64_C(1))for(uint8_t i=0;i<r->held_count;++i){const note_fx_held_pitch_t*h=&r->held[i];const note_event_result_t result=emit_generated(t,s,h,h->note,sample,period,emit,ctx);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;}}++ordinal;sample+=period;}refresh_work(t,s);}return NOTE_EVENT_RESULT_ACCEPTED;}
void note_fx_engine_release_terminal(const note_event_t*e){if(!e||e->track>=NOTE_FX_TRACK_COUNT||e->kind!=NOTE_EVENT_KIND_OFF)return;for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[e->track][s];if(r->model!=NOTE_FX_MODEL_CHORD&&r->model!=NOTE_FX_MODEL_HARMONIZER)continue;uint8_t i=0;while(i<r->held_count){const note_fx_held_pitch_t*h=&r->held[i];if((e->dependency_mask&(uint8_t)(1U<<s))!=0U&&h->source_token==e->source_id&&h->generation==e->source_generation&&held_temporal_index(h)==e->temporal_index)held_remove(r,i);else++i;}refresh_work(e->track,s);}}
void note_fx_engine_forget_dependency(uint8_t t,uint8_t owner){if(t>=NOTE_FX_TRACK_COUNT||owner>=NOTE_FX_SLOT_COUNT)return;const uint8_t bit=(uint8_t)(1U<<owner);for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[t][s];uint8_t i=0;while(i<r->held_count){if((r->held[i].dependency_mask&bit)!=0U)held_remove(r,i);else++i;}refresh_work(t,s);}}
void note_fx_engine_forget_causal_sources_from_slot(uint8_t t,uint8_t first,const uint32_t*ids,uint16_t count){if(t>=NOTE_FX_TRACK_COUNT||first>=NOTE_FX_SLOT_COUNT||!ids)return;for(uint8_t s=first;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[t][s];uint8_t i=0;while(i<r->held_count){uint8_t remove=0;for(uint16_t j=0;j<count;++j)if(r->held[i].source_token==ids[j])remove=1;if(remove)held_remove(r,i);else++i;}refresh_work(t,s);}}
note_event_result_t note_fx_engine_cleanup(uint8_t t){if(t>=NOTE_FX_TRACK_COUNT)return NOTE_EVENT_RESULT_DROPPED_POLICY;for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[t][s];memset(r->held,0,sizeof(r->held));r->held_count=0;refresh_work(t,s);}return NOTE_EVENT_RESULT_ACCEPTED;}

void note_fx_engine_rt_init(void){note_fx_engine_context_t*old=g_context;memset(&g_rt_context,0,sizeof(g_rt_context));g_rt_context.samples_per_step_q16=UINT32_C(65536);g_rt_context.rt_mode=1U;g_context=old;}
note_event_result_t note_fx_engine_rt_configure(uint8_t t,uint8_t s,uint8_t m,uint8_t p1,uint8_t p2,uint8_t p3){note_fx_engine_context_t*old=g_context;g_context=&g_rt_context;const note_event_result_t r=note_fx_engine_configure(t,s,m,p1,p2,p3,0U);g_context=old;return r;}
note_event_result_t note_fx_engine_rt_transform(uint8_t s,const note_event_t*in,uint8_t n,note_event_t*out,uint8_t cap,uint8_t*count){note_fx_engine_context_t*old=g_context;g_context=&g_rt_context;const note_event_result_t r=note_fx_engine_transform(s,in,n,out,cap,count);g_context=old;return r;}
note_event_result_t note_fx_engine_rt_process(uint64_t start,uint16_t frames,uint32_t sps,uint64_t transport,const uint32_t pattern[NOTE_FX_TRACK_COUNT],uint8_t scale,uint8_t root,note_fx_emit_fn emit,void*ctx){note_fx_engine_context_t*old=g_context;g_context=&g_rt_context;g_rt_context.block_start=start;g_rt_context.transport_position_q16=transport;g_rt_context.scale_index=scale;g_rt_context.root_index=root;memcpy(g_rt_context.pattern_position_q16,pattern,sizeof(g_rt_context.pattern_position_q16));const note_event_result_t r=note_fx_engine_process(start,frames,sps,emit,ctx);g_context=old;return r;}
