#include "NoteFx/note_fx_engine.h"
#include <string.h>
#include "Keyboard/keyboard_params.h"
#include "NoteFx/note_fx_euclid.h"
#include "Seq/seq_division_catalog.h"

typedef struct { uint32_t source_token,occurrence_id,generation,group_id;uint16_t chain_generation;uint8_t note,velocity,destination,provenance,active,reserved; } note_fx_held_pitch_t;
typedef struct { note_fx_held_pitch_t held[NOTE_FX_HELD_PITCH_CAPACITY];uint64_t next_sample;uint32_t phase,random_state;uint8_t held_count,cursor,model,p1,p2,p3; } note_fx_slot_runtime_t;
typedef struct { int8_t timing[8],velocity[8]; } note_fx_groove_template_t;

static const note_fx_groove_template_t g_groove[NOTE_FX_GROOVE_TYPE_COUNT]={
 {{0,24,0,24,0,24,0,24},{12,-8,8,-8,12,-8,8,-8}},
 {{0,32,0,32,0,32,0,32},{10,-12,6,-12,10,-12,6,-12}},
 {{0,12,-5,18,0,10,-4,16},{16,-10,5,-7,13,-9,4,-6}},
 {{0,18,-8,10,4,22,-6,12},{18,-14,8,-5,12,-12,7,-4}}};
static const uint8_t g_harmony[NOTE_FX_HARMONIZER_TYPE_COUNT][4]={
 {0,4,7,255},{0,3,7,255},{0,5,7,255},{0,2,7,255},
 {0,4,7,10},{0,4,7,11},{0,3,6,10},{0,4,8,255}};
static const uint8_t g_scale_count[7]={7,7,7,7,5,5,12};
static const uint8_t g_scale[7][12]={{0,2,4,5,7,9,11},{0,2,3,5,7,8,10},
 {0,2,3,5,7,9,10},{0,2,4,5,7,9,10},{0,2,4,7,9},{0,3,5,7,10},
 {0,1,2,3,4,5,6,7,8,9,10,11}};
static const note_fx_capacity_desc_t g_capacity[NOTE_FX_MODEL_COUNT]={
 [NOTE_FX_MODEL_OFF]={1,1,8,0,0},[NOTE_FX_MODEL_ARP]={1,1,8,16,1},
 [NOTE_FX_MODEL_EUCLID]={1,1,8,16,1},[NOTE_FX_MODEL_PROBABILITY]={1,1,8,0,0},
 [NOTE_FX_MODEL_GATE]={1,1,8,8,2},[NOTE_FX_MODEL_GROOVE]={1,1,8,0,0},
 [NOTE_FX_MODEL_ECHO]={1,3,8,32,4},[NOTE_FX_MODEL_HARMONIZER]={4,1,8,0,0},
 [NOTE_FX_MODEL_CHORD]={1,1,8,0,0}};
_Static_assert(sizeof(note_fx_slot_runtime_t)<=224U,"Note FX slot runtime budget");
_Static_assert(sizeof(g_groove)==64U,"Groove table proof");
_Static_assert(sizeof(g_harmony)==32U,"Harmony table proof");

static note_fx_slot_runtime_t g_slot[NOTE_FX_TRACK_COUNT][NOTE_FX_SLOT_COUNT];
static uint64_t g_work_slot_mask;static uint32_t g_token;
static uint32_t g_samples_per_step_q16=UINT32_C(65536);
static uint64_t slot_bit(uint8_t t,uint8_t s){return UINT64_C(1)<<((uint32_t)t*NOTE_FX_SLOT_COUNT+s);}
static void refresh_work(uint8_t t,uint8_t s){const uint64_t b=slot_bit(t,s);if((g_slot[t][s].model==NOTE_FX_MODEL_ARP||g_slot[t][s].model==NOTE_FX_MODEL_EUCLID)&&g_slot[t][s].held_count)g_work_slot_mask|=b;else g_work_slot_mask&=~b;}
static uint32_t next_token(void){g_token=(g_token+1U)&NOTE_EVENT_OCCURRENCE_COUNTER_MASK;if(!g_token)g_token=1U;return NOTE_EVENT_OCCURRENCE_NAMESPACE_FX|g_token;}
static uint32_t mix32(uint32_t x){x^=x>>16;x*=UINT32_C(0x7FEB352D);x^=x>>15;x*=UINT32_C(0x846CA68B);return x^(x>>16);}
static uint32_t child_id(uint32_t p,uint8_t s,uint8_t v,uint8_t r){uint32_t x=mix32(p^((uint32_t)(s+1U)<<24)^((uint32_t)(v+1U)<<12)^((uint32_t)(r+1U)<<4))&NOTE_EVENT_OCCURRENCE_COUNTER_MASK;if(!x)x=1U;return NOTE_EVENT_OCCURRENCE_NAMESPACE_FX|x;}
static int8_t held_find(const note_fx_slot_runtime_t*r,uint8_t n){for(uint8_t i=0;i<r->held_count;++i)if(r->held[i].active&&r->held[i].note==n)return(int8_t)i;return-1;}
static void held_remove(note_fx_slot_runtime_t*r,uint8_t i){if(i>=r->held_count)return;--r->held_count;r->held[i]=r->held[r->held_count];memset(&r->held[r->held_count],0,sizeof(r->held[0]));if(!r->held_count){r->phase=0;r->cursor=0;r->next_sample=0;}}
static note_event_result_t held_ingest(note_fx_slot_runtime_t*r,const note_event_t*e){const int8_t f=held_find(r,e->note);if(e->kind==NOTE_EVENT_KIND_OFF){if(f>=0&&r->held[(uint8_t)f].occurrence_id==e->occurrence_id&&r->held[(uint8_t)f].generation==e->generation)held_remove(r,(uint8_t)f);return NOTE_EVENT_RESULT_ACCEPTED;}uint8_t i;if(f>=0)i=(uint8_t)f;else{if(r->held_count>=NOTE_FX_HELD_PITCH_CAPACITY)return NOTE_EVENT_RESULT_REJECTED_CAPACITY;i=r->held_count++;if(r->held_count==1U){r->phase=0;r->cursor=0;r->next_sample=e->sample_abs;}}r->held[i]=(note_fx_held_pitch_t){e->source_token,e->occurrence_id,e->generation,e->group_id,e->chain_generation,e->note,e->velocity,e->destination_id,e->provenance,1,0};return NOTE_EVENT_RESULT_ACCEPTED;}
static uint8_t held_sorted(const note_fx_slot_runtime_t*r,uint8_t rank){uint8_t used=0,sel=0;for(uint8_t k=0;k<=rank;++k){uint8_t best=UINT8_MAX;for(uint8_t i=0;i<r->held_count;++i)if(!(used&(1U<<i))&&(best==UINT8_MAX||r->held[i].note<r->held[best].note))best=i;sel=best;used|=(uint8_t)(1U<<best);}return sel;}
static uint8_t arp_select(note_fx_slot_runtime_t*r,note_fx_held_pitch_t**oh,uint8_t*on){if(!r->held_count||!oh||!on)return 0;const note_fx_arp_style_t style=(note_fx_arp_style_t)r->p2;const uint32_t step=r->phase++;uint8_t rank;if(style==NOTE_FX_ARP_RANDOM){uint32_t x=r->random_state;x^=x<<13;x^=x>>17;x^=x<<5;r->random_state=x;rank=(uint8_t)(x%r->held_count);}else if(style==NOTE_FX_ARP_UP_DOWN&&r->held_count>1U){const uint8_t cycle=(uint8_t)(2U*r->held_count-2U),pos=(uint8_t)(step%cycle);rank=pos<r->held_count?pos:(uint8_t)(cycle-pos);}else{rank=(uint8_t)(step%r->held_count);if(style==NOTE_FX_ARP_DOWN)rank=(uint8_t)(r->held_count-1U-rank);}const uint8_t i=style==NOTE_FX_ARP_ORDER?rank:held_sorted(r,rank);note_fx_held_pitch_t*h=&r->held[i];const uint8_t range=r->p3>=1&&r->p3<=4?r->p3:1;const uint32_t cycle=style==NOTE_FX_ARP_UP_DOWN&&r->held_count>1?(uint32_t)(2U*r->held_count-2U):r->held_count;const uint16_t raised=(uint16_t)h->note+(uint16_t)(12U*((step/cycle)%range));*on=raised<128U?(uint8_t)raised:h->note;*oh=h;r->cursor=rank;return 1;}
static note_event_result_t emit_pair(uint8_t t,uint8_t s,const note_fx_held_pitch_t*h,uint8_t n,uint64_t sample,uint64_t duration,note_fx_emit_fn emit,void*ctx){if(!emit)return NOTE_EVENT_RESULT_ACCEPTED;const uint32_t token=next_token();note_event_t e={.sample_abs=sample,.duration_samples=duration>UINT32_MAX?UINT32_MAX:(uint32_t)duration,.source_token=h->source_token,.occurrence_id=token,.generation=h->generation,.group_id=h->group_id?h->group_id:token,.chain_generation=h->chain_generation,.track=t,.destination_id=h->destination,.note=n,.velocity=h->velocity,.kind=NOTE_EVENT_KIND_ON,.provenance=NOTE_EVENT_SOURCE_FX,.stage=(uint8_t)(s+1U),.flags=NOTE_EVENT_FLAG_GENERATED};note_event_result_t result=emit(&e,ctx);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;e.sample_abs=sample+(duration?duration:1U);e.duration_samples=0;e.velocity=0;e.kind=NOTE_EVENT_KIND_OFF;return emit(&e,ctx);}
static uint8_t append(note_event_t*out,uint8_t cap,uint8_t*count,const note_event_t*e,uint8_t stage){if(*count>=cap)return 0;out[*count]=*e;out[*count].stage=stage;++*count;return 1;}
static uint64_t step_samples(void){const uint64_t x=((uint64_t)g_samples_per_step_q16+0x8000ULL)>>16;return x?x:1U;}
static uint8_t probability_pass(const note_fx_slot_runtime_t*r,const note_event_t*e,uint8_t slot){static const uint8_t num[10]={0,1,2,1,2,3,1,2,3,4},den[10]={1,2,2,3,3,3,4,4,4,4};if(e->kind==NOTE_EVENT_KIND_OFF)return 1U;const uint8_t c=r->p2<10?r->p2:0;uint64_t identity=e->group_id;if(r->p3){const uint64_t p=seq_division_period_samples((uint8_t)(r->p3-1U),g_samples_per_step_q16);identity=e->sample_abs/(p?p:1U);}const uint64_t cycle=e->sample_abs/(step_samples()*16ULL);if(c&&((uint8_t)(cycle%den[c])+1U)!=num[c])return 0;if(r->p1>=100)return 1;if(!r->p1)return 0;return(uint8_t)((mix32((uint32_t)identity^(uint32_t)(identity>>32)^((uint32_t)e->track<<24)^((uint32_t)slot<<16)^(uint32_t)cycle)%100U)<r->p1);}
static uint8_t scale_shift(uint8_t note,int8_t shift){uint8_t sc=keyboard_params_get_scale_index();if(sc>=7)sc=0;const uint8_t root=keyboard_params_get_root_index()%12U,count=g_scale_count[sc];int16_t best=0;uint8_t dist=255;for(int16_t d=-12;d<128;++d){int16_t oct=d/(int16_t)count,idx=d%(int16_t)count;if(idx<0){idx+=count;--oct;}const int16_t cand=(int16_t)root+g_scale[sc][idx]+12*oct;const uint8_t dd=(uint8_t)(cand>note?cand-note:note-cand);if(dd<dist){dist=dd;best=d;if(!dd)break;}}int16_t d=best+shift,oct=d/(int16_t)count,idx=d%(int16_t)count;if(idx<0){idx+=count;--oct;}int16_t target=(int16_t)root+g_scale[sc][idx]+12*oct;while(target<0)target+=12;while(target>127)target-=12;return(uint8_t)target;}

static note_event_result_t direct(uint8_t slot,note_fx_slot_runtime_t*r,const note_event_t*e,note_event_t*out,uint8_t cap,uint8_t*count){const uint8_t stage=(uint8_t)(slot+1U);
 if(r->model==NOTE_FX_MODEL_PROBABILITY){const uint8_t pass=probability_pass(r,e,slot);return!pass?NOTE_EVENT_RESULT_ACCEPTED:(append(out,cap,count,e,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY);}
 if(r->model==NOTE_FX_MODEL_GROOVE){note_event_t x=*e;const uint8_t phase=(uint8_t)(mix32(e->group_id)%8U);const note_fx_groove_template_t*t=&g_groove[r->p1%NOTE_FX_GROOVE_TYPE_COUNT];const int64_t off=((int64_t)t->timing[phase]*(int64_t)step_samples()*r->p2)/(96LL*100LL);x.sample_abs=(off<0&&x.sample_abs<(uint64_t)(-off))?0U:(uint64_t)((int64_t)x.sample_abs+off);if(x.kind==NOTE_EVENT_KIND_ON){int32_t v=x.velocity+((int32_t)t->velocity[phase]*x.velocity*r->p3)/10000;if(v<1)v=1;if(v>127)v=127;x.velocity=(uint8_t)v;}return append(out,cap,count,&x,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY;}
 if(r->model==NOTE_FX_MODEL_ECHO){if(!append(out,cap,count,e,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;const uint64_t period=seq_division_period_samples(r->p1,g_samples_per_step_q16);for(uint8_t rep=1;rep<=r->p2;++rep){note_event_t x=*e;x.sample_abs+=(uint64_t)rep*period;x.occurrence_id=child_id(e->occurrence_id,slot,0,rep);x.group_id=mix32(e->group_id^((uint32_t)slot<<24)^rep);if(!x.group_id)x.group_id=1;x.provenance=NOTE_EVENT_SOURCE_FX;x.flags|=(NOTE_EVENT_FLAG_GENERATED|NOTE_EVENT_FLAG_FUTURE);if(x.kind==NOTE_EVENT_KIND_ON){uint32_t v=x.velocity;for(uint8_t n=0;n<rep;++n)v=(v*(100U-r->p3)+50U)/100U;if(!v)v=1;x.velocity=(uint8_t)v;}if(!append(out,cap,count,&x,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;}return NOTE_EVENT_RESULT_ACCEPTED;}
 if(r->model==NOTE_FX_MODEL_GATE){if(e->kind==NOTE_EVENT_KIND_OFF)return NOTE_EVENT_RESULT_ACCEPTED;note_event_t on=*e;on.duration_samples=0;if(r->p3==NOTE_FX_GATE_MODE_LEGATO)on.flags|=NOTE_EVENT_FLAG_LEGATO;else if(r->p3==NOTE_FX_GATE_MODE_RETRIG)on.flags|=NOTE_EVENT_FLAG_RETRIGGER;if(!append(out,cap,count,&on,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;int32_t var=0;if(r->p2){const uint32_t h=mix32(e->group_id^((uint32_t)slot<<24));var=(int32_t)(h%(2U*r->p2+1U))-(int32_t)r->p2;}int32_t pct=(int32_t)r->p1+var;if(pct<1)pct=1;if(r->p3==NOTE_FX_GATE_MODE_CLIP&&pct>100)pct=100;note_event_t off=on;off.sample_abs+=((uint64_t)pct*step_samples()+50U)/100U;off.kind=NOTE_EVENT_KIND_OFF;off.velocity=0;off.flags&=(uint8_t)~(NOTE_EVENT_FLAG_LEGATO|NOTE_EVENT_FLAG_RETRIGGER);off.flags|=(NOTE_EVENT_FLAG_GENERATED|NOTE_EVENT_FLAG_FUTURE);return append(out,cap,count,&off,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY;}
 if(r->model==NOTE_FX_MODEL_HARMONIZER){uint8_t emitted=0;for(uint8_t voice=0;voice<4;++voice){uint8_t interval=g_harmony[r->p1%NOTE_FX_HARMONIZER_TYPE_COUNT][voice];if(interval==255)continue;if(voice<r->p3)interval=(uint8_t)(interval+12U);if(r->p2&&voice)interval=(uint8_t)(interval+12U*(1U+(uint8_t)((voice-1U)%r->p2)));if((uint16_t)e->note+interval>=128)continue;note_event_t x=*e;x.note=(uint8_t)(e->note+interval);if(voice){x.occurrence_id=child_id(e->occurrence_id,slot,voice,0);x.provenance=NOTE_EVENT_SOURCE_FX;x.flags|=NOTE_EVENT_FLAG_GENERATED;}uint8_t dup=0;for(uint8_t i=0;i<*count;++i)if(out[i].destination_id==x.destination_id&&out[i].note==x.note)dup=1;if(!dup){if(!append(out,cap,count,&x,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;++emitted;}}return emitted?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_DROPPED_POLICY;}
 return append(out,cap,count,e,stage)?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_REJECTED_CAPACITY;}

static note_event_result_t chord_group(uint8_t slot,note_fx_slot_runtime_t*r,
 const note_event_t*in,uint8_t n,note_event_t*out,uint8_t cap,uint8_t*count){
 const uint8_t stage=(uint8_t)(slot+1U);*count=0;
 for(uint8_t i=0;i<n;++i){note_event_t x=in[i];x.note=scale_shift(x.note,(int8_t)r->p1-7);
  uint8_t duplicate=0;for(uint8_t j=0;j<*count;++j)if(out[j].destination_id==x.destination_id&&out[j].note==x.note)duplicate=1;
  if(!duplicate&&!append(out,cap,count,&x,stage))return NOTE_EVENT_RESULT_REJECTED_CAPACITY;}
 for(uint8_t i=1;i<*count;++i){note_event_t x=out[i];uint8_t j=i;while(j&&out[j-1U].note>x.note){out[j]=out[j-1U];--j;}out[j]=x;}
 const uint8_t invert=(r->p3<*count)?r->p3:*count;
 for(uint8_t i=0;i<*count;++i){uint16_t note=out[i].note;
  if(i<invert)note+=12U;
  if(r->p2!=0U)note+=(uint16_t)(12U*(i%(uint8_t)(r->p2+1U)));
  while(note>127U&&note>=12U)note-=12U;out[i].note=(uint8_t)note;}
 uint8_t write=0;for(uint8_t i=0;i<*count;++i){uint8_t duplicate=0;for(uint8_t j=0;j<write;++j)if(out[j].destination_id==out[i].destination_id&&out[j].note==out[i].note)duplicate=1;if(!duplicate)out[write++]=out[i];}
 *count=write;return write?NOTE_EVENT_RESULT_ACCEPTED:NOTE_EVENT_RESULT_DROPPED_POLICY;}

void note_fx_engine_init(void){memset(g_slot,0,sizeof(g_slot));g_work_slot_mask=0;g_token=0;for(uint8_t t=0;t<NOTE_FX_TRACK_COUNT;++t)for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s)g_slot[t][s].random_state=UINT32_C(0x9E3779B9)^((uint32_t)t<<8)^s;}
void note_fx_engine_set_samples_per_step_q16(uint32_t v){g_samples_per_step_q16=v?v:1U;}
uint8_t note_fx_engine_capacity(uint8_t model,note_fx_capacity_desc_t*out){if(!out||model>=NOTE_FX_MODEL_COUNT)return 0;*out=g_capacity[model];return 1;}
note_event_result_t note_fx_engine_configure(uint8_t t,uint8_t s,uint8_t model,uint8_t p1,uint8_t p2,uint8_t p3){if(t>=NOTE_FX_TRACK_COUNT||s>=NOTE_FX_SLOT_COUNT)return NOTE_EVENT_RESULT_DROPPED_POLICY;note_fx_slot_runtime_t*r=&g_slot[t][s];if(model>=NOTE_FX_MODEL_COUNT)model=NOTE_FX_MODEL_OFF;if(r->model!=model){const uint32_t random=r->random_state;memset(r,0,sizeof(*r));r->random_state=random?random:UINT32_C(0x6D2B79F5);}r->model=model;r->p1=p1;r->p2=p2;r->p3=p3;refresh_work(t,s);return NOTE_EVENT_RESULT_ACCEPTED;}
note_event_result_t note_fx_engine_transform(uint8_t s,const note_event_t*in,uint8_t n,note_event_t*out,uint8_t cap,uint8_t*count){if(!in||!out||!count||!n||s>=NOTE_FX_SLOT_COUNT)return NOTE_EVENT_RESULT_DROPPED_POLICY;for(uint8_t i=0;i<n;++i)if(!note_event_is_valid(&in[i])||in[i].track>=NOTE_FX_TRACK_COUNT||in[i].stage!=s||in[i].track!=in[0].track||in[i].group_id!=in[0].group_id||in[i].kind!=in[0].kind)return NOTE_EVENT_RESULT_DROPPED_POLICY;note_fx_slot_runtime_t*r=&g_slot[in[0].track][s];if(r->model==NOTE_FX_MODEL_CHORD)return chord_group(s,r,in,n,out,cap,count);*count=0;for(uint8_t i=0;i<n;++i){const note_event_t*e=&in[i];if(r->model==NOTE_FX_MODEL_ARP||r->model==NOTE_FX_MODEL_EUCLID){const note_event_result_t result=held_ingest(r,e);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;refresh_work(e->track,s);}else{const note_event_result_t result=direct(s,r,e,out,cap,count);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;}}return NOTE_EVENT_RESULT_ACCEPTED;}
void note_fx_engine_forget_causal_source(uint8_t t,uint32_t source){if(t>=NOTE_FX_TRACK_COUNT||!source)return;for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[t][s];uint8_t i=0;while(i<r->held_count){if(r->held[i].source_token==source)held_remove(r,i);else++i;}refresh_work(t,s);}}
note_event_result_t note_fx_engine_process(uint64_t start,uint16_t frames,uint32_t sps,note_fx_emit_fn emit,void*ctx){note_fx_engine_set_samples_per_step_q16(sps);const uint64_t end=start+frames;uint64_t processed=0,work;while((work=(g_work_slot_mask&~processed))!=0){const uint32_t idx=(uint32_t)__builtin_ctzll(work);processed|=UINT64_C(1)<<idx;const uint8_t t=(uint8_t)(idx/NOTE_FX_SLOT_COUNT),s=(uint8_t)(idx%NOTE_FX_SLOT_COUNT);note_fx_slot_runtime_t*r=&g_slot[t][s];if(!r->held_count||(r->model!=NOTE_FX_MODEL_ARP&&r->model!=NOTE_FX_MODEL_EUCLID))continue;uint64_t period=seq_division_period_samples(r->model==NOTE_FX_MODEL_EUCLID?r->p3:r->p1,sps);if(!period)period=1;if(r->next_sample<start)r->next_sample=start;while(r->next_sample<end){const uint64_t sample=r->next_sample;if(r->model==NOTE_FX_MODEL_ARP){note_fx_held_pitch_t*h=NULL;uint8_t note=0;if(arp_select(r,&h,&note)){const note_event_result_t result=emit_pair(t,s,h,note,sample,period,emit,ctx);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;}}else{const uint8_t length=r->p1?r->p1:NOTE_FX_EUCLID_LENGTH_DEFAULT,pulse=r->p2<=length?r->p2:length;const uint64_t mask=euclid_build_mask(length,pulse);if((mask>>(r->phase%length))&UINT64_C(1))for(uint8_t i=0;i<r->held_count;++i){const note_fx_held_pitch_t*h=&r->held[i];const note_event_result_t result=emit_pair(t,s,h,h->note,sample,period,emit,ctx);if(result!=NOTE_EVENT_RESULT_ACCEPTED)return result;}r->phase=(r->phase+1U)%length;}r->next_sample=sample+period;}}return NOTE_EVENT_RESULT_ACCEPTED;}
note_event_result_t note_fx_engine_cleanup(uint8_t t){if(t>=NOTE_FX_TRACK_COUNT)return NOTE_EVENT_RESULT_DROPPED_POLICY;for(uint8_t s=0;s<NOTE_FX_SLOT_COUNT;++s){note_fx_slot_runtime_t*r=&g_slot[t][s];memset(r->held,0,sizeof(r->held));r->held_count=0;r->phase=0;r->cursor=0;r->next_sample=0;refresh_work(t,s);}return NOTE_EVENT_RESULT_ACCEPTED;}
