#pragma once

#include "param_store.h"

/**
 * @file control_router.h
 * @brief Routage des paramètres de contrôle vers le moteur audio.
 */

typedef param_id_t control_param_id_t;

#define CTRL_PARAM_GRAN_DENSITY             PARAM_GRAN_DENSITY
#define CTRL_PARAM_GRAN_PITCH               PARAM_GRAN_PITCH
#define CTRL_PARAM_GRAN_MIX                 PARAM_GRAN_MIX
#define CTRL_PARAM_GRAN_FREEZE              PARAM_GRAN_FREEZE
#define CTRL_PARAM_GRAN_SPREAD              PARAM_GRAN_SPREAD
#define CTRL_PARAM_GRAN_STEREO              PARAM_GRAN_STEREO

#define CTRL_PARAM_MIX_TRACK0_GAIN          PARAM_MIX_TRACK0_GAIN
#define CTRL_PARAM_MIX_TRACK1_GAIN          PARAM_MIX_TRACK1_GAIN
#define CTRL_PARAM_MIX_TRACK2_GAIN          PARAM_MIX_TRACK2_GAIN
#define CTRL_PARAM_MIX_TRACK3_GAIN          PARAM_MIX_TRACK3_GAIN
#define CTRL_PARAM_MIX_TRACK0_PAN           PARAM_MIX_TRACK0_PAN
#define CTRL_PARAM_MIX_TRACK1_PAN           PARAM_MIX_TRACK1_PAN
#define CTRL_PARAM_MIX_TRACK2_PAN           PARAM_MIX_TRACK2_PAN
#define CTRL_PARAM_MIX_TRACK3_PAN           PARAM_MIX_TRACK3_PAN
#define CTRL_PARAM_MIX_TRACK0_MUTE          PARAM_MIX_TRACK0_MUTE
#define CTRL_PARAM_MIX_TRACK1_MUTE          PARAM_MIX_TRACK1_MUTE
#define CTRL_PARAM_MIX_TRACK2_MUTE          PARAM_MIX_TRACK2_MUTE
#define CTRL_PARAM_MIX_TRACK3_MUTE          PARAM_MIX_TRACK3_MUTE
#define CTRL_PARAM_MIX_TRACK0_ROUTE         PARAM_MIX_TRACK0_ROUTE
#define CTRL_PARAM_MIX_TRACK1_ROUTE         PARAM_MIX_TRACK1_ROUTE
#define CTRL_PARAM_MIX_TRACK2_ROUTE         PARAM_MIX_TRACK2_ROUTE
#define CTRL_PARAM_MIX_TRACK3_ROUTE         PARAM_MIX_TRACK3_ROUTE
#define CTRL_PARAM_MIX_TRACK0_INSERT0       PARAM_MIX_TRACK0_INSERT0
#define CTRL_PARAM_MIX_TRACK0_INSERT1       PARAM_MIX_TRACK0_INSERT1
#define CTRL_PARAM_MIX_TRACK1_INSERT0       PARAM_MIX_TRACK1_INSERT0
#define CTRL_PARAM_MIX_TRACK1_INSERT1       PARAM_MIX_TRACK1_INSERT1
#define CTRL_PARAM_MIX_TRACK2_INSERT0       PARAM_MIX_TRACK2_INSERT0
#define CTRL_PARAM_MIX_TRACK2_INSERT1       PARAM_MIX_TRACK2_INSERT1
#define CTRL_PARAM_MIX_TRACK3_INSERT0       PARAM_MIX_TRACK3_INSERT0
#define CTRL_PARAM_MIX_TRACK3_INSERT1       PARAM_MIX_TRACK3_INSERT1
#define CTRL_PARAM_MIX_TRACK0_SEND0         PARAM_MIX_TRACK0_SEND0
#define CTRL_PARAM_MIX_TRACK0_SEND1         PARAM_MIX_TRACK0_SEND1
#define CTRL_PARAM_MIX_TRACK1_SEND0         PARAM_MIX_TRACK1_SEND0
#define CTRL_PARAM_MIX_TRACK1_SEND1         PARAM_MIX_TRACK1_SEND1
#define CTRL_PARAM_MIX_TRACK2_SEND0         PARAM_MIX_TRACK2_SEND0
#define CTRL_PARAM_MIX_TRACK2_SEND1         PARAM_MIX_TRACK2_SEND1
#define CTRL_PARAM_MIX_TRACK3_SEND0         PARAM_MIX_TRACK3_SEND0
#define CTRL_PARAM_MIX_TRACK3_SEND1         PARAM_MIX_TRACK3_SEND1
#define CTRL_PARAM_MIX_SEND0_FX             PARAM_MIX_SEND0_FX
#define CTRL_PARAM_MIX_SEND1_FX             PARAM_MIX_SEND1_FX

#define CTRL_PARAM_BUS_COMP_THRESHOLD_DB    PARAM_BUS_COMP_THRESHOLD_DB
#define CTRL_PARAM_BUS_COMP_RATIO           PARAM_BUS_COMP_RATIO
#define CTRL_PARAM_BUS_COMP_ATTACK_INDEX    PARAM_BUS_COMP_ATTACK_INDEX
#define CTRL_PARAM_BUS_COMP_RELEASE_INDEX   PARAM_BUS_COMP_RELEASE_INDEX
#define CTRL_PARAM_BUS_COMP_MAKEUP_DB       PARAM_BUS_COMP_MAKEUP_DB
#define CTRL_PARAM_BUS_COMP_AUTO_MAKEUP     PARAM_BUS_COMP_AUTO_MAKEUP
#define CTRL_PARAM_BUS_COMP_DRYWET          PARAM_BUS_COMP_DRYWET
#define CTRL_PARAM_BUS_COMP_HPF_HZ          PARAM_BUS_COMP_HPF_HZ

#define CTRL_PARAM_DAISY_COMP_THRESHOLD_DB  PARAM_DAISY_COMP_THRESHOLD_DB
#define CTRL_PARAM_DAISY_COMP_RATIO         PARAM_DAISY_COMP_RATIO
#define CTRL_PARAM_DAISY_COMP_ATTACK_S      PARAM_DAISY_COMP_ATTACK_S
#define CTRL_PARAM_DAISY_COMP_RELEASE_S     PARAM_DAISY_COMP_RELEASE_S
#define CTRL_PARAM_DAISY_COMP_MAKEUP_DB     PARAM_DAISY_COMP_MAKEUP_DB
#define CTRL_PARAM_DAISY_COMP_AUTO_MAKEUP   PARAM_DAISY_COMP_AUTO_MAKEUP
#define CTRL_PARAM_DAISY_COMP_MIX           PARAM_DAISY_COMP_MIX

#define CTRL_PARAM_EQ_LOW_DB                 PARAM_EQ_LOW_DB
#define CTRL_PARAM_EQ_MID_DB                 PARAM_EQ_MID_DB
#define CTRL_PARAM_EQ_HIGH_DB                PARAM_EQ_HIGH_DB

#define CTRL_PARAM_SAT_TONE                  PARAM_SAT_TONE
#define CTRL_PARAM_SAT_BIAS                  PARAM_SAT_BIAS
#define CTRL_PARAM_SAT_DRIVE                 PARAM_SAT_DRIVE
#define CTRL_PARAM_SAT_MIX                   PARAM_SAT_MIX

#define CTRL_PARAM_MASTER_GAIN               PARAM_MASTER_GAIN
#define CTRL_PARAM_POST_GAIN                 PARAM_POST_GAIN
#define CTRL_PARAM_OUTPUT_COMP               PARAM_OUTPUT_COMP

void control_router_set_param(control_param_id_t id, float v);
