#ifndef BRICK_BUILD_CONFIG_H
#define BRICK_BUILD_CONFIG_H

#ifndef BRICK_TEST_BUILD
#define BRICK_TEST_BUILD 0
#endif

#if (BRICK_TEST_BUILD != 0) && (BRICK_TEST_BUILD != 1)
#error "BRICK_TEST_BUILD must be defined to 0 or 1"
#endif

#if defined(BRICK6_VARIANT_LOWCOST)
#define BRICK6_LOOPER_GLOBAL_CAP 1U
#define BRICK6_LOOPER_RAW_SLOT_CAP 1U
#define BRICK6_LOOPER_SHIFTER_SLOT_CAP 1U
#else
#define BRICK6_LOOPER_GLOBAL_CAP 8U
#define BRICK6_LOOPER_RAW_SLOT_CAP 4U
#define BRICK6_LOOPER_SHIFTER_SLOT_CAP 4U
#endif

#endif
