#pragma once

#include <stdint.h>

#define BOARD_AUDIO_SAMPLE_RATE_HZ 48000U
#define BOARD_AUDIO_FRAMES_PER_HALF 64U
#define BOARD_AUDIO_FRAMES_TOTAL (BOARD_AUDIO_FRAMES_PER_HALF * 2U)

/*
 * Common BRICK audio contract.
 *
 * The physical SAI/I2C/DMA wiring remains board-specific.
 */
#define BOARD_AUDIO_CONTRACT_SAMPLE_RATE_HZ 48000U
#define BOARD_AUDIO_CONTRACT_SAMPLE_BITS 24U
#define BOARD_AUDIO_CONTRACT_SLOT_BITS 32U
#define BOARD_AUDIO_CONTRACT_FRAMES_PER_HALF 64U
#define BOARD_AUDIO_CONTRACT_FRAMES_TOTAL \
    (BOARD_AUDIO_CONTRACT_FRAMES_PER_HALF * 2U)
#define BOARD_AUDIO_CONTRACT_TDM_SLOTS 2U
#define BOARD_AUDIO_CONTRACT_LOGICAL_CHANNELS 2U
#define BOARD_AUDIO_CONTRACT_WORDS_PER_FRAME BOARD_AUDIO_CONTRACT_TDM_SLOTS
#define BOARD_AUDIO_CONTRACT_BUFFER_WORDS \
    (BOARD_AUDIO_CONTRACT_FRAMES_TOTAL * BOARD_AUDIO_CONTRACT_WORDS_PER_FRAME)

#if (BOARD_AUDIO_SAMPLE_RATE_HZ != BOARD_AUDIO_CONTRACT_SAMPLE_RATE_HZ) \
    || (BOARD_AUDIO_FRAMES_PER_HALF != BOARD_AUDIO_CONTRACT_FRAMES_PER_HALF)
#error "Board audio timing must match the common audio contract"
#endif

#define BOARD_AUDIO_TDM_SLOTS BOARD_AUDIO_CONTRACT_TDM_SLOTS
#define BOARD_AUDIO_WORDS_PER_FRAME BOARD_AUDIO_TDM_SLOTS
#define BOARD_AUDIO_BUFFER_WORDS (BOARD_AUDIO_FRAMES_TOTAL * BOARD_AUDIO_WORDS_PER_FRAME)
