#pragma once

#include <stdint.h>

#define BOARD_AUDIO_SAMPLE_RATE_HZ 48000U
#define BOARD_AUDIO_FRAMES_PER_HALF 64U
#define BOARD_AUDIO_FRAMES_TOTAL (BOARD_AUDIO_FRAMES_PER_HALF * 2U)
#define BOARD_AUDIO_TDM_SLOTS 8U
#define BOARD_AUDIO_WORDS_PER_FRAME BOARD_AUDIO_TDM_SLOTS
#define BOARD_AUDIO_BUFFER_WORDS (BOARD_AUDIO_FRAMES_TOTAL * BOARD_AUDIO_WORDS_PER_FRAME)

