#include "Track/tone_param_codec.h"

#include <stddef.h>

#include "Seq/seq_types.h"

static const param_id_t prism[] = {
 PARAM_PRISM_OSC1_PARAM1,PARAM_PRISM_OSC1_PARAM2,PARAM_PRISM_OSC1_AMOD,PARAM_PRISM_OSC1_MODEL,
 PARAM_PRISM_VOLUME,PARAM_PRISM_BALANCE,PARAM_PRISM_TUNE,PARAM_PRISM_DETUNE,PARAM_PRISM_DRIFT,
 PARAM_PRISM_PITCH_MOD1,PARAM_PRISM_PHASE1_RESET,PARAM_PRISM_OSC2_PARAM1,PARAM_PRISM_OSC2_PARAM2,
 PARAM_PRISM_OSC2_AMOD,PARAM_PRISM_OSC2_MODEL,PARAM_PRISM_PITCH_MOD2};
static const param_id_t stack[] = {
 PARAM_STACK_OSC1_LEVEL,PARAM_STACK_OSC2_LEVEL,PARAM_STACK_OSC3_LEVEL,PARAM_STACK_NOISE_LEVEL,
 PARAM_STACK_OSC1_MODEL,PARAM_STACK_OSC1_TUNE,PARAM_STACK_OSC1_TIMBRE,PARAM_STACK_OSC1_COLOR,
 PARAM_STACK_OSC2_MODEL,PARAM_STACK_OSC2_TUNE,PARAM_STACK_OSC2_TIMBRE,PARAM_STACK_OSC2_COLOR,
 PARAM_STACK_OSC3_MODEL,PARAM_STACK_OSC3_TUNE,PARAM_STACK_OSC3_TIMBRE,PARAM_STACK_OSC3_COLOR,
 PARAM_STACK_OSC_DETUNE,PARAM_STACK_PHASE_RESET};
static const param_id_t wave[] = {PARAM_WAVE_OSC1_POS,PARAM_WAVE_OSC1_START,PARAM_WAVE_OSC1_LEN,
 PARAM_WAVE_OSC2_POS,PARAM_WAVE_OSC2_START,PARAM_WAVE_OSC2_LEN,PARAM_WAVE_VOLUME,PARAM_WAVE_BALANCE,
 PARAM_WAVE_TUNE,PARAM_WAVE_DETUNE};
static const param_id_t ram[] = {PARAM_SAMPLER_GAIN,PARAM_SAMPLER_START,PARAM_SAMPLER_LENGTH,
 PARAM_SAMPLER_MODE,PARAM_SAMPLER_TUNE,PARAM_SAMPLER_LOOP_START,PARAM_SAMPLER_SLICE_COUNT};
static const param_id_t stream[] = {PARAM_SAMPLER_GAIN,PARAM_SAMPLER_CLIP_SOURCE_BPM,
 PARAM_SAMPLER_CLIP_PLAY_MODE,PARAM_SAMPLER_CLIP_LOOP,PARAM_SAMPLER_CLIP_STRETCH_MODE,
 PARAM_SAMPLER_CLIP_PITCH,PARAM_SAMPLER_CLIP_SYNC_LENGTH,PARAM_SAMPLER_CLIP_GRAIN};
static const param_id_t looper[] = {PARAM_LOOPER_XFADE,PARAM_LOOPER_STRETCH,PARAM_LOOPER_PITCH,PARAM_LOOPER_GRAIN};
static const param_id_t multi[] = {PARAM_SAMPLER_GAIN,PARAM_SAMPLER_MULTI_LOOP};
static const param_id_t midi[] = {PARAM_MIDI_PROGRAM,PARAM_MIDI_CC1_1,PARAM_MIDI_CC1_2,PARAM_MIDI_CC1_3,
 PARAM_MIDI_CC1_4,PARAM_MIDI_CC2_1,PARAM_MIDI_CC2_2,PARAM_MIDI_CC2_3,PARAM_MIDI_CC2_4,
 PARAM_MIDI_CC3_1,PARAM_MIDI_CC3_2,PARAM_MIDI_CC3_3,PARAM_MIDI_CC3_4};
static const param_id_t external[] = {PARAM_MIDI_PROGRAM,PARAM_MIDI_CC1_1,PARAM_MIDI_CC1_2,PARAM_MIDI_CC1_3,
 PARAM_MIDI_CC1_4,PARAM_MIDI_CC2_1,PARAM_MIDI_CC2_2,PARAM_MIDI_CC2_3,PARAM_MIDI_CC2_4,
 PARAM_MIDI_CC3_1,PARAM_MIDI_CC3_2,PARAM_MIDI_CC3_3,PARAM_MIDI_CC3_4,PARAM_EXTERNAL_TRIG};
static const param_id_t analog[] = {PARAM_DRUM_TRX_BD_PITCH,PARAM_DRUM_TRX_BD_DECAY,
 PARAM_DRUM_TRX_BD_HARMONICS,PARAM_DRUM_TRX_BD_PITCH_SWEEP,PARAM_DRUM_TRX_BD_SWEEP_DECAY,
 PARAM_DRUM_TRX_BD_ATTACK,PARAM_DRUM_TRX_BD_NOISE,PARAM_DRUM_TRX_BD_DRIVE};
static const param_id_t md[] = {PARAM_DRUM_MD_MODEL,PARAM_DRUM_MD_P1,PARAM_DRUM_MD_P2,PARAM_DRUM_MD_P3,
 PARAM_DRUM_MD_P4,PARAM_DRUM_MD_P5,PARAM_DRUM_MD_P6,PARAM_DRUM_MD_P7,PARAM_DRUM_MD_P8};

static uint8_t table_for(track_runtime_type_t type,const param_id_t **table,uint8_t *count)
{
 if(table==NULL||count==NULL)return 0U;
#define T(x) do{*table=(x);*count=(uint8_t)(sizeof(x)/sizeof((x)[0]));return 1U;}while(0)
 switch(type){
 case TRACK_RUNTIME_TYPE_PRISM:T(prism); case TRACK_RUNTIME_TYPE_STACK:T(stack);
 case TRACK_RUNTIME_TYPE_WAVE:T(wave); case TRACK_RUNTIME_TYPE_RAM:T(ram);
 case TRACK_RUNTIME_TYPE_STREAM:T(stream); case TRACK_RUNTIME_TYPE_LOOPER:T(looper);
 case TRACK_RUNTIME_TYPE_MULTI:T(multi); case TRACK_RUNTIME_TYPE_MIDI:T(midi);
 case TRACK_RUNTIME_TYPE_EXTERNAL:T(external); case TRACK_RUNTIME_TYPE_DRUM_BD_ANALOG:T(analog);
 case TRACK_RUNTIME_TYPE_DRUM_MD:T(md); default:return 0U;}
#undef T
}
uint8_t tone_param_codec_count(track_runtime_type_t type){const param_id_t*t;uint8_t n;return table_for(type,&t,&n)?n:0U;}
uint8_t tone_param_codec_slot_to_param(track_runtime_type_t type,uint8_t slot,param_id_t*out)
{const param_id_t*t;uint8_t n;if(out==NULL||!table_for(type,&t,&n)||slot>=n)return 0U;*out=t[slot];return 1U;}
uint8_t tone_param_codec_param_to_slot(track_runtime_type_t type,param_id_t id,uint8_t*out)
{const param_id_t*t;uint8_t n;if(out==NULL||!table_for(type,&t,&n))return 0U;for(uint8_t i=0;i<n;++i)if(t[i]==id){*out=i;return 1U;}return 0U;}
