#include "Audio/fx_audio_drift.h"
#include <stddef.h>
#include <string.h>
#define DRIFT_RING_MASK (FX_AUDIO_DRIFT_RING_SIZE-1U)
void fx_audio_drift_reset(fx_audio_drift_state_t*s,fx_audio_drift_history_t*h){if(!s||!h)return;memset(s,0,sizeof(*s));memset(h,0,sizeof(*h));s->delay=s->delay_target=FX_AUDIO_DRIFT_DELAY_MIN_SAMPLES;}
void fx_audio_drift_set_delay(fx_audio_drift_state_t*s,float v){if(!s)return;if(v<0)v=0;if(v>FX_AUDIO_DRIFT_DELAY_MOD_MAX_CONTROL)v=FX_AUDIO_DRIFT_DELAY_MOD_MAX_CONTROL;s->delay_target=FX_AUDIO_DRIFT_DELAY_MIN_SAMPLES+FX_AUDIO_DRIFT_DELAY_BASE_SPAN_SAMPLES*v;}
void fx_audio_drift_set_feedback(fx_audio_drift_state_t*s,float v){if(!s)return;if(v<0)v=0;if(v>FX_AUDIO_DRIFT_FEEDBACK_MAX)v=FX_AUDIO_DRIFT_FEEDBACK_MAX;s->feedback=v;}
float fx_audio_drift_process_mono_sample(fx_audio_drift_state_t*s,fx_audio_drift_history_t*h,float in,float inc){s->delay+=inc;const float d=s->delay;const uint32_t whole=(uint32_t)d,pos=(s->write+whole)&DRIFT_RING_MASK;const float a=h->ring[pos],out=a+(h->ring[(pos+1U)&DRIFT_RING_MASK]-a)*(d-(float)whole);h->ring[s->write]=in+out*s->feedback;s->write=(s->write-1U)&DRIFT_RING_MASK;return out;}
void fx_audio_drift_process_stereo(fx_audio_drift_state_t*s,fx_audio_drift_history_t*h,float*l,float*r,uint32_t n){if(!s||!h||!l||!r||!n)return;const float inc=(s->delay_target-s->delay)/(float)n;for(uint32_t i=0;i<n;++i){const float wet=fx_audio_drift_process_mono_sample(s,h,(l[i]+r[i])*.5f,inc)*.5f;l[i]=wet;r[i]=wet;}s->delay=s->delay_target;}
void fx_audio_drift_process_dual_mono_stereo(fx_audio_drift_state_t*s,fx_audio_drift_history_t*hl,fx_audio_drift_history_t*hr,float*l,float*r,uint32_t n){if(!s||!hl||!hr||!l||!r||!n)return;const float inc=(s->delay_target-s->delay)/(float)n;for(uint32_t i=0;i<n;++i){s->delay+=inc;const float d=s->delay;const uint32_t whole=(uint32_t)d,pos=(s->write+whole)&DRIFT_RING_MASK;const float al=hl->ring[pos],ar=hr->ring[pos],wl=al+(hl->ring[(pos+1U)&DRIFT_RING_MASK]-al)*(d-(float)whole),wr=ar+(hr->ring[(pos+1U)&DRIFT_RING_MASK]-ar)*(d-(float)whole);hl->ring[s->write]=l[i]+wl*s->feedback;hr->ring[s->write]=r[i]+wr*s->feedback;s->write=(s->write-1U)&DRIFT_RING_MASK;l[i]=wl*.5f;r[i]=wr*.5f;}s->delay=s->delay_target;}
