################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/Middlewares/ST/STM32_USB_Host_Library/Core/Src \
App/usb_stack \
Drivers/CMSIS_DSP/Source/BasicMathFunctions \
Drivers/CMSIS_DSP/Source/CommonTables \
Drivers/CMSIS_DSP/Source/ComplexMathFunctions \
Drivers/CMSIS_DSP/Source/ControllerFunctions \
Drivers/CMSIS_DSP/Source/FastMathFunctions \
Drivers/CMSIS_DSP/Source/FilteringFunctions \
Drivers/CMSIS_DSP/Source/QuaternionMathFunctions \
Drivers/CMSIS_DSP/Source/TransformFunctions \
Drivers/Drv_app/Src \
Drivers/STM32H7xx_HAL_Driver/Src \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Src/App \
Src/Audio \
Src/Core \
Src/MIDI \
Src/Param \
Src/Sampler \
Src/Storage \
Src/UI \
Src \
Startup \
mutable_instruments/clouds \
mutable_instruments/clouds/dsp \
mutable_instruments/clouds/dsp/pvoc \
mutable_instruments/stmlib/dsp \
mutable_instruments/stmlib/utils \
tinyusb/src/class/audio \
tinyusb/src/class/bth \
tinyusb/src/class/cdc \
tinyusb/src/class/dfu \
tinyusb/src/class/hid \
tinyusb/src/class/midi \
tinyusb/src/class/msc \
tinyusb/src/class/mtp \
tinyusb/src/class/net \
tinyusb/src/class/usbtmc \
tinyusb/src/class/vendor \
tinyusb/src/class/video \
tinyusb/src/common \
tinyusb/src/device \
tinyusb/src/host \
tinyusb/src/portable/analog/max3421 \
tinyusb/src/portable/bridgetek/ft9xx \
tinyusb/src/portable/chipidea/ci_fs \
tinyusb/src/portable/chipidea/ci_hs \
tinyusb/src/portable/dialog/da146xx \
tinyusb/src/portable/ehci \
tinyusb/src/portable/mentor/musb \
tinyusb/src/portable/microchip/pic \
tinyusb/src/portable/microchip/pic32mz \
tinyusb/src/portable/microchip/samd \
tinyusb/src/portable/microchip/samg \
tinyusb/src/portable/microchip/samx7x \
tinyusb/src/portable/mindmotion/mm32 \
tinyusb/src/portable/nordic/nrf5x \
tinyusb/src/portable/nuvoton/nuc120 \
tinyusb/src/portable/nuvoton/nuc121 \
tinyusb/src/portable/nuvoton/nuc505 \
tinyusb/src/portable/nxp/khci \
tinyusb/src/portable/nxp/lpc17_40 \
tinyusb/src/portable/nxp/lpc_ip3511 \
tinyusb/src/portable/ohci \
tinyusb/src/portable/raspberrypi/pio_usb \
tinyusb/src/portable/raspberrypi/rp2040 \
tinyusb/src/portable/renesas/rusb2 \
tinyusb/src/portable/sony/cxd56 \
tinyusb/src/portable/st/stm32_fsdev \
tinyusb/src/portable/st/typec \
tinyusb/src/portable/sunxi \
tinyusb/src/portable/synopsys/dwc2 \
tinyusb/src/portable/template \
tinyusb/src/portable/ti/msp430x5xx \
tinyusb/src/portable/valentyusb/eptri \
tinyusb/src/portable/wch \
tinyusb/src \
tinyusb/src/typec \

