#ifndef PERSISTENT_PROJECT_CONTROL_H
#define PERSISTENT_PROJECT_CONTROL_H
#include "Storage/persistent_control_codec.h"
void persistent_project_control_capture_metadata(persist_codec_project_metadata_t*out);
persist_codec_result_t persistent_project_control_apply_working(const persist_codec_project_metadata_t*metadata,const persist_control_pattern_t*pattern,uint8_t resume_transport);
#endif
