#ifndef PERSISTENT_PATTERN_CONTROL_H
#define PERSISTENT_PATTERN_CONTROL_H
#include <stdint.h>
#include "Storage/persistent_control_codec.h"
persist_codec_result_t persistent_pattern_control_capture(persist_control_pattern_t *out_pattern);
persist_codec_result_t persistent_pattern_control_validate(const persist_control_pattern_t *pattern);
persist_codec_result_t persistent_pattern_control_apply(const persist_control_pattern_t *pattern,uint8_t resume_transport);
#endif
