#pragma once

#include "param_store.h"

/**
 * @file control_router.h
 * @brief Routage des paramètres de contrôle vers le moteur audio.
 */

typedef param_id_t control_param_id_t;

#define CTRL_PARAM_GRAN_DENSITY             PARAM_GRAN_DENSITY
#define CTRL_PARAM_GRAN_PITCH               PARAM_GRAN_PITCH
#define CTRL_PARAM_GRAN_MIX                 PARAM_GRAN_MIX
#define CTRL_PARAM_GRAN_FREEZE              PARAM_GRAN_FREEZE
#define CTRL_PARAM_GRAN_SPREAD              PARAM_GRAN_SPREAD
#define CTRL_PARAM_GRAN_STEREO              PARAM_GRAN_STEREO

#define CTRL_PARAM_MIX_SEND0_FX             PARAM_MIX_SEND0_FX
#define CTRL_PARAM_MIX_SEND1_FX             PARAM_MIX_SEND1_FX

#define CTRL_PARAM_BUS_COMP_THRESHOLD_DB    PARAM_BUS_COMP_THRESHOLD_DB
#define CTRL_PARAM_BUS_COMP_RATIO           PARAM_BUS_COMP_RATIO
#define CTRL_PARAM_BUS_COMP_ATTACK_INDEX    PARAM_BUS_COMP_ATTACK_INDEX
#define CTRL_PARAM_BUS_COMP_RELEASE_INDEX   PARAM_BUS_COMP_RELEASE_INDEX
#define CTRL_PARAM_BUS_COMP_MAKEUP_DB       PARAM_BUS_COMP_MAKEUP_DB
#define CTRL_PARAM_BUS_COMP_AUTO_MAKEUP     PARAM_BUS_COMP_AUTO_MAKEUP
#define CTRL_PARAM_BUS_COMP_DRYWET          PARAM_BUS_COMP_DRYWET
#define CTRL_PARAM_BUS_COMP_HPF_HZ          PARAM_BUS_COMP_HPF_HZ

#define CTRL_PARAM_EQ_LOW_DB                 PARAM_EQ_LOW_DB
#define CTRL_PARAM_EQ_MID_DB                 PARAM_EQ_MID_DB
#define CTRL_PARAM_EQ_HIGH_DB                PARAM_EQ_HIGH_DB

#define CTRL_PARAM_SAT_TONE                  PARAM_SAT_TONE
#define CTRL_PARAM_SAT_BIAS                  PARAM_SAT_BIAS
#define CTRL_PARAM_SAT_DRIVE                 PARAM_SAT_DRIVE
#define CTRL_PARAM_SAT_MIX                   PARAM_SAT_MIX

#define CTRL_PARAM_FILTER_TYPE               PARAM_FILTER_TYPE
#define CTRL_PARAM_FILTER_CUTOFF             PARAM_FILTER_CUTOFF
#define CTRL_PARAM_FILTER_RESONANCE          PARAM_FILTER_RESONANCE
#define CTRL_PARAM_FILTER_EG_AMT             PARAM_FILTER_EG_AMT
#define CTRL_PARAM_FILTER_ATTACK             PARAM_FILTER_ATTACK
#define CTRL_PARAM_FILTER_DECAY              PARAM_FILTER_DECAY
#define CTRL_PARAM_FILTER_SUSTAIN            PARAM_FILTER_SUSTAIN
#define CTRL_PARAM_FILTER_RELEASE            PARAM_FILTER_RELEASE
#define CTRL_PARAM_FILTER_EQ_LOW             PARAM_FILTER_EQ_LOW
#define CTRL_PARAM_FILTER_EQ_MID             PARAM_FILTER_EQ_MID
#define CTRL_PARAM_FILTER_EQ_HIGH            PARAM_FILTER_EQ_HIGH
#define CTRL_PARAM_FILTER_DRIVE              PARAM_FILTER_DRIVE
#define CTRL_PARAM_FILTER_DECIMATOR_BITS     PARAM_FILTER_DECIMATOR_BITS
#define CTRL_PARAM_FILTER_DECIMATOR_RATE     PARAM_FILTER_DECIMATOR_RATE

#define CTRL_PARAM_MASTER_GAIN               PARAM_MASTER_GAIN
#define CTRL_PARAM_POST_GAIN                 PARAM_POST_GAIN
#define CTRL_PARAM_OUTPUT_COMP               PARAM_OUTPUT_COMP

#define CTRL_PARAM_JUNO_SAW                  PARAM_JUNO_SAW
#define CTRL_PARAM_JUNO_PULSE                PARAM_JUNO_PULSE
#define CTRL_PARAM_JUNO_SUB                  PARAM_JUNO_SUB
#define CTRL_PARAM_JUNO_PWM                  PARAM_JUNO_PWM
#define CTRL_PARAM_JUNO_VCF_FREQ             PARAM_JUNO_VCF_FREQ
#define CTRL_PARAM_JUNO_VCF_RES              PARAM_JUNO_VCF_RES
#define CTRL_PARAM_JUNO_VCF_ENV              PARAM_JUNO_VCF_ENV
#define CTRL_PARAM_JUNO_VCF_LFO              PARAM_JUNO_VCF_LFO
#define CTRL_PARAM_JUNO_ATTACK               PARAM_JUNO_ATTACK
#define CTRL_PARAM_JUNO_DECAY                PARAM_JUNO_DECAY
#define CTRL_PARAM_JUNO_SUSTAIN              PARAM_JUNO_SUSTAIN
#define CTRL_PARAM_JUNO_RELEASE              PARAM_JUNO_RELEASE
#define CTRL_PARAM_JUNO_LFO_RATE             PARAM_JUNO_LFO_RATE
#define CTRL_PARAM_JUNO_HPF                  PARAM_JUNO_HPF
#define CTRL_PARAM_JUNO_PORTA                PARAM_JUNO_PORTA
#define CTRL_PARAM_JUNO_MODE                 PARAM_JUNO_MODE

void control_router_set_param(control_param_id_t id, float v);
