#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint16_t param_id_t;

enum {
    PARAM_MIX_MUTE = 0,
    PARAM_CFG_POLY_SPREAD,
    PARAM_DRUM_MD_MODEL,
    PARAM_DRUM_MD_P1,
    PARAM_DRUM_MD_P2,
    PARAM_DRUM_MD_P3,
    PARAM_DRUM_MD_P4,
    PARAM_DRUM_MD_P5,
    PARAM_DRUM_MD_P6,
    PARAM_DRUM_MD_P7,
    PARAM_DRUM_MD_P8,
    PARAM_MIX_SEND0_FX,
    PARAM_MIX_SEND1_FX,
    PARAM_MIX_LEVEL,
    PARAM_MIX_PAN,
    PARAM_MIX_SEND1,
    PARAM_MIX_SEND2,

    PARAM_BUS_COMP_THRESHOLD_DB,
    PARAM_BUS_COMP_RATIO,
    PARAM_BUS_COMP_ATTACK_INDEX,
    PARAM_BUS_COMP_RELEASE_INDEX,
    PARAM_BUS_COMP_MAKEUP_DB,
    PARAM_BUS_COMP_AUTO_MAKEUP,
    PARAM_BUS_COMP_DRYWET,
    PARAM_BUS_COMP_HPF_HZ,
    PARAM_SAT_TONE,
    PARAM_SAT_BIAS,
    PARAM_SAT_DRIVE,
    PARAM_SAT_MIX,

    PARAM_FILTER_MORPH,
    PARAM_FILTER_CUTOFF,
    PARAM_FILTER_RESONANCE,
    PARAM_FILTER_EG_AMT,
    PARAM_FILTER_ATTACK,
    PARAM_FILTER_DECAY,
    PARAM_FILTER_SUSTAIN,
    PARAM_FILTER_RELEASE,
    PARAM_FILTER_KEYTRK,
    PARAM_FILTER_ENVRST,
    PARAM_FILTER_ENVDLY,
    PARAM_VCA_ATTACK,
    PARAM_VCA_DECAY,
    PARAM_VCA_SUSTAIN,
    PARAM_VCA_RELEASE,

    PARAM_MASTER_GAIN,
    PARAM_POST_GAIN,
    PARAM_OUTPUT_COMP,

    PARAM_LFO1_RATE,
    PARAM_LFO1_SHAPE,
    PARAM_LFO1_TRIG,
    PARAM_LFO1_PHASE,
    PARAM_LFO2_RATE,
    PARAM_LFO2_SHAPE,
    PARAM_LFO2_TRIG,
    PARAM_LFO2_PHASE,
    PARAM_LFO3_RATE,
    PARAM_LFO3_SHAPE,
    PARAM_LFO3_TRIG,
    PARAM_LFO3_PHASE,
    PARAM_ENV3_ATTACK,
    PARAM_ENV3_DECAY,
    PARAM_ENV3_SUSTAIN,
    PARAM_ENV3_RELEASE,
    PARAM_ENV_RETRIG_FILTER,
    PARAM_ENV_RETRIG_VCA,
    PARAM_ENV_RETRIG_MOD,
    PARAM_MIX_REVERB_WET,
    PARAM_MIX_REVERB_ROOM_SIZE,
    PARAM_MIX_REVERB_DAMPING,
    PARAM_MIX_REVERB_WIDTH,
    PARAM_MIX_REVERB_HPF,
    PARAM_MIX_REVERB_LPF,
    PARAM_MIX_DELAY_TYPE,
    PARAM_MIX_DELAY_TIME,
    PARAM_MIX_DELAY_PINGPONG,
    PARAM_MIX_DELAY_MODE,
    PARAM_MIX_DELAY_TIME_R,
    PARAM_MIX_DELAY_WIDTH,
    PARAM_MIX_DELAY_FEEDBACK,
    PARAM_MIX_DELAY_SPECTRAL_POSITION,
    PARAM_MIX_DELAY_SPECTRAL_WIDTH,
    PARAM_MIX_DELAY_FBW,
    PARAM_MIX_REVERB_DELAYS,
    PARAM_MIX_DELAY_MOD,
    PARAM_MIX_DELAY_MOD_RATE,
    PARAM_MIX_DELAY_REV,
    PARAM_MIX_DELAY_VOL,

    PARAM_SAMPLER_GAIN,
    PARAM_SAMPLER_START,
    PARAM_SAMPLER_LENGTH,
    PARAM_SAMPLER_MODE,
    PARAM_SAMPLER_TUNE,
    PARAM_SAMPLER_SLICE_COUNT,
    PARAM_PRISM_OSC1_MODEL,
    PARAM_PRISM_VOLUME,
    PARAM_PRISM_TUNE,
    PARAM_PRISM_PITCH_MOD1,
    PARAM_PRISM_OSC1_PARAM1,
    PARAM_PRISM_OSC1_AMOD,
    PARAM_PRISM_OSC1_PARAM2,
    PARAM_PRISM_PHASE1_RESET,
    PARAM_PRISM_BALANCE,
    PARAM_PRISM_OSC2_MODEL,
    PARAM_PRISM_DETUNE,
    PARAM_PRISM_PITCH_MOD2,
    PARAM_PRISM_OSC2_PARAM1,
    PARAM_PRISM_OSC2_AMOD,
    PARAM_PRISM_OSC2_PARAM2,
    PARAM_PRISM_DRIFT,
    PARAM_STACK_OSC1_LEVEL,
    PARAM_STACK_OSC2_LEVEL,
    PARAM_STACK_OSC3_LEVEL,
    PARAM_STACK_NOISE_LEVEL,
    PARAM_STACK_OSC1_MODEL,
    PARAM_STACK_OSC1_TUNE,
    PARAM_STACK_OSC1_TIMBRE,
    PARAM_STACK_OSC1_COLOR,
    PARAM_STACK_OSC2_MODEL,
    PARAM_STACK_OSC2_TUNE,
    PARAM_STACK_OSC2_TIMBRE,
    PARAM_STACK_OSC2_COLOR,
    PARAM_STACK_OSC3_MODEL,
    PARAM_STACK_OSC3_TUNE,
    PARAM_STACK_OSC3_TIMBRE,
    PARAM_STACK_OSC3_COLOR,
    PARAM_STACK_OSC_DETUNE,
    PARAM_STACK_PHASE_RESET,
    PARAM_MIDI_PROGRAM,
    PARAM_MIDI_CC1_1,
    PARAM_MIDI_CC1_2,
    PARAM_MIDI_CC1_3,
    PARAM_MIDI_CC1_4,
    PARAM_MIDI_CC2_1,
    PARAM_MIDI_CC2_2,
    PARAM_MIDI_CC2_3,
    PARAM_MIDI_CC2_4,
    PARAM_MIDI_CC3_1,
    PARAM_MIDI_CC3_2,
    PARAM_MIDI_CC3_3,
    PARAM_MIDI_CC3_4,
    PARAM_SAMPLER_CLIP_SOURCE_BPM,
    PARAM_SAMPLER_CLIP_SYNC_LENGTH,
    PARAM_SAMPLER_CLIP_PITCH,
    PARAM_SAMPLER_CLIP_PLAY_MODE,
    PARAM_SAMPLER_CLIP_LOOP,
    PARAM_SAMPLER_CLIP_STRETCH_MODE,
    PARAM_SAMPLER_CLIP_GRAIN,
    PARAM_FILTER_MODE,
    PARAM_FM_RATIO,
    PARAM_FM_ALGORITHM,
    PARAM_FM_FEEDBACK,
    PARAM_FM_SYNC,
    PARAM_FM_BRIGHT,
    PARAM_FM_BODY,
    PARAM_FM_DETAIL,
    PARAM_FM_METAL,
    PARAM_FM_ENV_ATTACK,
    PARAM_FM_ENV_DECAY,
    PARAM_FM_ENV_SUSTAIN,
    PARAM_FM_ENV_RELEASE,
    PARAM_SAMPLER_CLIP_SOURCE,
    PARAM_SHIFTER_HEADS,
    PARAM_SHIFTER_WINDOW,
    PARAM_SHIFTER_DISP,
    PARAM_SAMPLER_MULTI_LOOP,
    PARAM_SAMPLER_LOOP_START,
    PARAM_WAVE_OSC1_POS,
    PARAM_WAVE_OSC1_START,
    PARAM_WAVE_OSC1_LEN,
    PARAM_WAVE_OSC2_POS,
    PARAM_WAVE_OSC2_START,
    PARAM_WAVE_OSC2_LEN,
    PARAM_WAVE_VOLUME,
    PARAM_WAVE_BALANCE,
    PARAM_WAVE_TUNE,
    PARAM_WAVE_DETUNE,
    PARAM_COMP_MODEL,
    PARAM_COMP_DETECT,
    PARAM_COMP_KNEE_DB,
    PARAM_COMP_DELUGE_SAT,
    /* EXT TONE gate policy. */
    PARAM_EXT_GATE,

    PARAM_MIDI_FX_S1_PARAM1,
    PARAM_MIDI_FX_S1_PARAM2,
    PARAM_MIDI_FX_S1_PARAM3,
    PARAM_MIDI_FX_S1_PARAM4,
    PARAM_MIDI_FX_S1_MODEL,
    PARAM_MIDI_FX_S2_PARAM1,
    PARAM_MIDI_FX_S2_PARAM2,
    PARAM_MIDI_FX_S2_PARAM3,
    PARAM_MIDI_FX_S2_PARAM4,
    PARAM_MIDI_FX_S2_MODEL,
    PARAM_MIDI_FX_S3_PARAM1,
    PARAM_MIDI_FX_S3_PARAM2,
    PARAM_MIDI_FX_S3_PARAM3,
    PARAM_MIDI_FX_S3_PARAM4,
    PARAM_MIDI_FX_S3_MODEL,
    PARAM_MIDI_FX_ORDER,

    PARAM_FM_PLAY_VEL,
    PARAM_FM_PLAY_KEY,
    PARAM_FM_PLAY_PITCH_ENV,
    PARAM_FM_PLAY_PITCH_TIME,
    PARAM_FM_OP1_LEVEL,
    PARAM_FM_OP1_FREQ,
    PARAM_FM_OP1_DETUNE,
    PARAM_FM_OP1_ENV_ATTACK,
    PARAM_FM_OP1_ENV_DECAY,
    PARAM_FM_OP1_ENV_SUSTAIN,
    PARAM_FM_OP1_ENV_RELEASE,
    PARAM_FM_OP1_ON,
    PARAM_FM_OP1_MODE,
    PARAM_FM_OP1_VEL,
    PARAM_FM_OP1_KEY,
    PARAM_FM_OP2_LEVEL,
    PARAM_FM_OP2_FREQ,
    PARAM_FM_OP2_DETUNE,
    PARAM_FM_OP2_ENV_ATTACK,
    PARAM_FM_OP2_ENV_DECAY,
    PARAM_FM_OP2_ENV_SUSTAIN,
    PARAM_FM_OP2_ENV_RELEASE,
    PARAM_FM_OP2_ON,
    PARAM_FM_OP2_MODE,
    PARAM_FM_OP2_VEL,
    PARAM_FM_OP2_KEY,
    PARAM_FM_OP3_LEVEL,
    PARAM_FM_OP3_FREQ,
    PARAM_FM_OP3_DETUNE,
    PARAM_FM_OP3_ENV_ATTACK,
    PARAM_FM_OP3_ENV_DECAY,
    PARAM_FM_OP3_ENV_SUSTAIN,
    PARAM_FM_OP3_ENV_RELEASE,
    PARAM_FM_OP3_ON,
    PARAM_FM_OP3_MODE,
    PARAM_FM_OP3_VEL,
    PARAM_FM_OP3_KEY,
    PARAM_FM_OP4_LEVEL,
    PARAM_FM_OP4_FREQ,
    PARAM_FM_OP4_DETUNE,
    PARAM_FM_OP4_ENV_ATTACK,
    PARAM_FM_OP4_ENV_DECAY,
    PARAM_FM_OP4_ENV_SUSTAIN,
    PARAM_FM_OP4_ENV_RELEASE,
    PARAM_FM_OP4_ON,
    PARAM_FM_OP4_MODE,
    PARAM_FM_OP4_VEL,
    PARAM_FM_OP4_KEY,
    PARAM_FM_OP5_LEVEL,
    PARAM_FM_OP5_FREQ,
    PARAM_FM_OP5_DETUNE,
    PARAM_FM_OP5_ENV_ATTACK,
    PARAM_FM_OP5_ENV_DECAY,
    PARAM_FM_OP5_ENV_SUSTAIN,
    PARAM_FM_OP5_ENV_RELEASE,
    PARAM_FM_OP5_ON,
    PARAM_FM_OP5_MODE,
    PARAM_FM_OP5_VEL,
    PARAM_FM_OP5_KEY,
    PARAM_FM_OP6_LEVEL,
    PARAM_FM_OP6_FREQ,
    PARAM_FM_OP6_DETUNE,
    PARAM_FM_OP6_ENV_ATTACK,
    PARAM_FM_OP6_ENV_DECAY,
    PARAM_FM_OP6_ENV_SUSTAIN,
    PARAM_FM_OP6_ENV_RELEASE,
    PARAM_FM_OP6_ON,
    PARAM_FM_OP6_MODE,
    PARAM_FM_OP6_VEL,
    PARAM_FM_OP6_KEY,

    /* Public FM projections of the typed CONTROL-owned base voice. */
    PARAM_FM_TRANSPOSE,
    PARAM_FM_PITCH_R1,
    PARAM_FM_PITCH_R2,
    PARAM_FM_PITCH_R3,
    PARAM_FM_PITCH_R4,
    PARAM_FM_PITCH_L1,
    PARAM_FM_PITCH_L2,
    PARAM_FM_PITCH_L3,
    PARAM_FM_PITCH_L4,

    /* Per-entity Audio FX control. */
    PARAM_AUDIO_FX_P1,
    PARAM_AUDIO_FX_P2,
    PARAM_AUDIO_FX_P3,
    PARAM_AUDIO_FX_MODEL,

    PARAM_MIX_SEND3,
    PARAM_MODFX_MODEL,
    PARAM_MODFX_RATE,
    PARAM_MODFX_DEPTH,
    PARAM_MODFX_FEEDBACK,
    PARAM_MODFX_OFFSET,
    PARAM_MODFX_RATE_B,
    PARAM_MODFX_DELAY_B,
    PARAM_MODFX_DEPTH_B,
    PARAM_MODFX_WIDTH,

    /* Per-entity Audio FX slot B control. */
    PARAM_AUDIO_FX_B_P1,
    PARAM_AUDIO_FX_B_P2,
    PARAM_AUDIO_FX_B_P3,
    PARAM_AUDIO_FX_B_MODEL,

    /* GROUP children own only these local sends into the GROUP master's
     * parallel Audio FX slots. */
    PARAM_GROUP_FX_A_LEVEL,
    PARAM_GROUP_FX_B_LEVEL,

    /* TB-303 TONE controls. */
    PARAM_TB303_WAVE,
    PARAM_TB303_TUNE,
    PARAM_TB303_CUT,
    PARAM_TB303_RES,
    PARAM_TB303_ENV_MOD,
    PARAM_TB303_DECAY,
    PARAM_TB303_ACCENT,
    PARAM_TB303_SLIDE,
    PARAM_TB303_VCF_RATE,

    PARAM_ACID_WAVE,
    PARAM_ACID_TUNE,
    PARAM_ACID_CUT,
    PARAM_ACID_RES,
    PARAM_ACID_ENV_MOD,
    PARAM_ACID_DECAY,
    PARAM_ACID_ACCENT,
    PARAM_ACID_SLIDE,
    PARAM_ACID_VCF_RATE,

    PARAM_COUNT
};


#define PARAM_FM_OPERATOR_FIRST       PARAM_FM_OP1_LEVEL
#define PARAM_FM_OPERATOR_LAST        PARAM_FM_OP6_KEY
#define PARAM_FM_OPERATOR_PARAM_COUNT 11U
#define PARAM_FM_OPERATOR_COUNT       6U
#define PARAM_FM_UI_FIRST             PARAM_FM_TRANSPOSE
#define PARAM_FM_UI_LAST              PARAM_FM_PITCH_L4

static inline uint8_t param_id_is_fm_public(param_id_t id)
{
    return (uint8_t)(((id >= PARAM_FM_RATIO) && (id <= PARAM_FM_ENV_RELEASE))
            || ((id >= PARAM_FM_PLAY_VEL) && (id <= PARAM_FM_UI_LAST)));
}

static inline uint8_t param_id_is_valid(param_id_t id)
{
    return (uint8_t)(id < PARAM_COUNT);
}

#ifdef __cplusplus
#define PARAM_ID_STATIC_ASSERT static_assert
#else
#define PARAM_ID_STATIC_ASSERT _Static_assert
#endif
PARAM_ID_STATIC_ASSERT(PARAM_MIX_MUTE == 0, "Parameter IDs must stay dense");
PARAM_ID_STATIC_ASSERT(PARAM_DRUM_MD_P1 == (PARAM_DRUM_MD_MODEL + 1), "Drum MD block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_DRUM_MD_P8 == (PARAM_DRUM_MD_P1 + 7), "Drum MD block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_LFO2_RATE == (PARAM_LFO1_RATE + 4), "LFO blocks must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_LFO3_RATE == (PARAM_LFO2_RATE + 4), "LFO blocks must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_MIDI_CC3_4 == (PARAM_MIDI_CC1_1 + 11), "MIDI CC block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_STACK_OSC3_LEVEL == (PARAM_STACK_OSC1_LEVEL + 2),
        "Stack level block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_STACK_OSC3_COLOR == (PARAM_STACK_OSC1_MODEL + 11),
        "Stack oscillator blocks must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_WAVE_OSC1_LEN == (PARAM_WAVE_OSC1_POS + 2),
        "Wave oscillator 1 block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_WAVE_OSC2_POS == (PARAM_WAVE_OSC1_POS + 3),
        "Wave oscillator blocks must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_WAVE_OSC2_LEN == (PARAM_WAVE_OSC2_POS + 2),
        "Wave oscillator 2 block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_FM_OPERATOR_LAST == (PARAM_FM_OPERATOR_FIRST
        + (PARAM_FM_OPERATOR_COUNT * PARAM_FM_OPERATOR_PARAM_COUNT) - 1U),
        "FM operator blocks must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_FM_PITCH_R4 == (PARAM_FM_PITCH_R1 + 3),
        "FM pitch rate block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_FM_PITCH_L1 == (PARAM_FM_PITCH_R4 + 1),
        "FM pitch envelope blocks must stay adjacent");
PARAM_ID_STATIC_ASSERT(PARAM_FM_PITCH_L4 == (PARAM_FM_PITCH_L1 + 3),
        "FM pitch level block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_AUDIO_FX_P3 == (PARAM_AUDIO_FX_P1 + 2),
        "Audio FX slot A parameter block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_AUDIO_FX_B_P3 == (PARAM_AUDIO_FX_B_P1 + 2),
        "Audio FX slot B parameter block must stay contiguous");
PARAM_ID_STATIC_ASSERT(PARAM_COUNT == 314, "Unexpected parameter catalog size");
#undef PARAM_ID_STATIC_ASSERT

#ifdef __cplusplus
}
#endif
