#pragma once
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint16_t param_id_t;

enum {
    PARAM_RESERVED_000 = 0,
    PARAM_RESERVED_001 = 1,
    PARAM_RESERVED_002 = 2,
    PARAM_RESERVED_003 = 3,
    PARAM_RESERVED_004 = 4,
    PARAM_RESERVED_005 = 5,

    PARAM_RESERVED_006 = 6,
    PARAM_RESERVED_007 = 7,
    PARAM_RESERVED_008 = 8,
    PARAM_RESERVED_009 = 9,
    PARAM_RESERVED_010 = 10,
    PARAM_RESERVED_011 = 11,
    PARAM_RESERVED_012 = 12,
    PARAM_RESERVED_013 = 13,
    PARAM_MIX_MUTE = 14,
    PARAM_RESERVED_015 = 15,
    PARAM_CFG_POLY_VOICES = 16,
    PARAM_CFG_POLY_SPREAD = 17,
    PARAM_RESERVED_018 = 18,
    PARAM_RESERVED_019 = 19,
    PARAM_RESERVED_020 = 20,
    PARAM_DRUM_MD_MODEL = 21,
    PARAM_DRUM_MD_P1 = 22,
    PARAM_DRUM_MD_P2 = 23,
    PARAM_DRUM_MD_P3 = 24,
    PARAM_DRUM_MD_P4 = 25,
    PARAM_DRUM_MD_P5 = 26,
    PARAM_DRUM_MD_P6 = 27,
    PARAM_DRUM_MD_P7 = 28,
    PARAM_DRUM_MD_P8 = 29,
    PARAM_RESERVED_030 = 30,
    PARAM_RESERVED_031 = 31,
    PARAM_RESERVED_032 = 32,
    PARAM_RESERVED_033 = 33,
    PARAM_RESERVED_034 = 34,
    PARAM_RESERVED_035 = 35,
    PARAM_RESERVED_036 = 36,
    PARAM_RESERVED_037 = 37,
    PARAM_MIX_SEND0_FX,
    PARAM_MIX_SEND1_FX,
    PARAM_MIX_LEVEL,
    PARAM_MIX_PAN,
    PARAM_MIX_SEND1,
    PARAM_MIX_SEND2,

    PARAM_BUS_COMP_THRESHOLD_DB,
    PARAM_BUS_COMP_RATIO,
    PARAM_BUS_COMP_ATTACK_INDEX,
    PARAM_BUS_COMP_RELEASE_INDEX,
    PARAM_BUS_COMP_MAKEUP_DB,
    PARAM_BUS_COMP_AUTO_MAKEUP,
    PARAM_BUS_COMP_DRYWET,
    PARAM_BUS_COMP_HPF_HZ,

    PARAM_EQ_LOW_DB,
    PARAM_EQ_MID_DB,
    PARAM_EQ_HIGH_DB,

    PARAM_SAT_TONE,
    PARAM_SAT_BIAS,
    PARAM_SAT_DRIVE,
    PARAM_SAT_MIX,

    PARAM_FILTER_TYPE,
    PARAM_FILTER_CUTOFF,
    PARAM_FILTER_RESONANCE,
    PARAM_FILTER_EG_AMT,
    PARAM_FILTER_ATTACK,
    PARAM_FILTER_DECAY,
    PARAM_FILTER_SUSTAIN,
    PARAM_FILTER_RELEASE,
    PARAM_FILTER_KEYTRK,
    PARAM_FILTER_ENVRST,
    PARAM_FILTER_ENVDLY,
    PARAM_FILTER_EQ_LOW,
    PARAM_FILTER_EQ_MID,
    PARAM_FILTER_EQ_HIGH,
    PARAM_FILTER_DRIVE,
    PARAM_FILTER_DECIMATOR_BITS,
    PARAM_FILTER_DECIMATOR_RATE,
    PARAM_FILTER_DECIMATOR_RATE2,
    PARAM_VCA_ATTACK,
    PARAM_VCA_DECAY,
    PARAM_VCA_SUSTAIN,
    PARAM_VCA_RELEASE,

    PARAM_CFG_TRACK,
    PARAM_CFG_TRACK_TYPE,
    PARAM_CFG_MIDI_CH,
    PARAM_CFG_MIDI_SRC,
    PARAM_CFG_START,
    PARAM_CFG_TEMPO,
    PARAM_CFG_SYNC,
    PARAM_CFG_REC_LEN,
    PARAM_CFG_METRO,

    PARAM_SEQ_LENGTH,
    PARAM_SEQ_DIV,
    PARAM_SEQ_QUANT,
    PARAM_SEQ_SWING,

    PARAM_SEQ_PLAY_V1_NOTE,
    PARAM_SEQ_PLAY_V1_VEL,
    PARAM_SEQ_PLAY_V1_LEN,
    PARAM_SEQ_PLAY_V1_MICTIM,
    PARAM_SEQ_PLAY_V2_NOTE,
    PARAM_SEQ_PLAY_V2_VEL,
    PARAM_SEQ_PLAY_V2_LEN,
    PARAM_SEQ_PLAY_V2_MICTIM,
    PARAM_SEQ_PLAY_V3_NOTE,
    PARAM_SEQ_PLAY_V3_VEL,
    PARAM_SEQ_PLAY_V3_LEN,
    PARAM_SEQ_PLAY_V3_MICTIM,
    PARAM_SEQ_PLAY_V4_NOTE,
    PARAM_SEQ_PLAY_V4_VEL,
    PARAM_SEQ_PLAY_V4_LEN,
    PARAM_SEQ_PLAY_V4_MICTIM,

    PARAM_KBD_ROOT,
    PARAM_KBD_SCALE,
    PARAM_KBD_OMNICHORD,
    PARAM_KBD_NOTE_ORDER,
    PARAM_KBD_CHORD_OVERRIDE,
    PARAM_KBD_MONO_LAST,


    PARAM_MASTER_GAIN,
    PARAM_POST_GAIN,
    PARAM_OUTPUT_COMP,

    PARAM_DRUM_TRX_BD_PITCH,
    PARAM_DRUM_TRX_BD_DECAY,
    PARAM_DRUM_TRX_BD_PITCH_SWEEP,
    PARAM_DRUM_TRX_BD_SWEEP_DECAY,
    PARAM_DRUM_TRX_BD_ATTACK,
    PARAM_DRUM_TRX_BD_NOISE,
    PARAM_DRUM_TRX_BD_HARMONICS,
    PARAM_DRUM_TRX_BD_DRIVE,

    PARAM_LFO1_RATE,
    PARAM_LFO1_SHAPE,
    PARAM_LFO1_TRIG,
    PARAM_LFO1_PHASE,
    PARAM_LFO2_RATE,
    PARAM_LFO2_SHAPE,
    PARAM_LFO2_TRIG,
    PARAM_LFO2_PHASE,
    PARAM_LFO3_RATE,
    PARAM_LFO3_SHAPE,
    PARAM_LFO3_TRIG,
    PARAM_LFO3_PHASE,
    PARAM_MOD_MATRIX_SLOT,
    PARAM_MOD_MATRIX_SOURCE,
    PARAM_MOD_MATRIX_DEST,
    PARAM_MOD_MATRIX_DEPTH,
    PARAM_MOD_MULTI_1_A,
    PARAM_MOD_MULTI_1_B,
    PARAM_MOD_MULTI_2_A,
    PARAM_MOD_MULTI_2_B,
    PARAM_MOD_SLEW_1_SOURCE,
    PARAM_MOD_SLEW_1_AMOUNT,
    PARAM_MOD_SLEW_2_SOURCE,
    PARAM_MOD_SLEW_2_AMOUNT,
    PARAM_ENV3_ATTACK,
    PARAM_ENV3_DECAY,
    PARAM_ENV3_SUSTAIN,
    PARAM_ENV3_RELEASE,
    PARAM_ENV_RETRIG_FILTER,
    PARAM_ENV_RETRIG_VCA,
    PARAM_ENV_RETRIG_MOD,

    PARAM_MIX_REVERB_WET,
    PARAM_MIX_REVERB_ROOM_SIZE,
    PARAM_MIX_REVERB_DAMPING,
    PARAM_MIX_REVERB_WIDTH,
    PARAM_MIX_REVERB_HPF,
    PARAM_MIX_REVERB_LPF,
    PARAM_MIX_DELAY_TYPE,
    PARAM_MIX_DELAY_TIME,
    PARAM_MIX_DELAY_PINGPONG,
    PARAM_MIX_DELAY_MODE,
    PARAM_MIX_DELAY_TIME_R,
    PARAM_MIX_DELAY_WIDTH,
    PARAM_MIX_DELAY_FEEDBACK,
    PARAM_MIX_DELAY_SPECTRAL_POSITION,
    PARAM_MIX_DELAY_SPECTRAL_WIDTH,
    PARAM_MIX_DELAY_FBW,
    PARAM_RESERVED_174,
    PARAM_RESERVED_175,
    PARAM_MIX_DELAY_MOD,
    PARAM_MIX_DELAY_MOD_RATE,
    PARAM_MIX_DELAY_REV,
    PARAM_MIX_DELAY_VOL,

    PARAM_SAMPLER_SAMPLE,
    PARAM_SAMPLER_GAIN,
    PARAM_SAMPLER_START,
    PARAM_SAMPLER_END,
    PARAM_SAMPLER_MODE,
    PARAM_SAMPLER_TUNE,
    PARAM_SAMPLER_SLICE_COUNT,
    PARAM_PRISM_EDIT,
    PARAM_PRISM_FINE,
    PARAM_PRISM_COARSE,
    PARAM_PRISM_FM,
    PARAM_PRISM_TIMBRE,
    PARAM_PRISM_MODULATION,
    PARAM_PRISM_COLOR,
    PARAM_PRISM_PHASE_RESET,
    PARAM_PRISM_LEVEL,
    PARAM_PRISM_OSC2_EDIT,
    PARAM_PRISM_OSC2_FINE,
    PARAM_PRISM_OSC2_COARSE,
    PARAM_PRISM_OSC2_FM,
    PARAM_PRISM_OSC2_TIMBRE,
    PARAM_PRISM_OSC2_MODULATION,
    PARAM_PRISM_OSC2_COLOR,
    PARAM_PRISM_OSC2_PHASE_RESET,
    PARAM_PRISM_OSC2_LEVEL,
    PARAM_STACK_OSC1_LEVEL,
    PARAM_STACK_OSC2_LEVEL,
    PARAM_STACK_OSC3_LEVEL,
    PARAM_STACK_NOISE_LEVEL,
    PARAM_STACK_OSC1_MODEL,
    PARAM_STACK_OSC1_TUNE,
    PARAM_STACK_OSC1_TIMBRE,
    PARAM_STACK_OSC1_COLOR,
    PARAM_STACK_OSC1_PARAM3,
    PARAM_STACK_OSC2_MODEL,
    PARAM_STACK_OSC2_TUNE,
    PARAM_STACK_OSC2_TIMBRE,
    PARAM_STACK_OSC2_COLOR,
    PARAM_STACK_OSC2_PARAM3,
    PARAM_STACK_OSC3_MODEL,
    PARAM_STACK_OSC3_TUNE,
    PARAM_STACK_OSC3_TIMBRE,
    PARAM_STACK_OSC3_COLOR,
    PARAM_STACK_OSC3_PARAM3,
    PARAM_STACK_OSC_DETUNE,
    PARAM_STACK_PHASE_RESET,
    PARAM_MIDI_PROGRAM,
    PARAM_MIDI_CC1_1,
    PARAM_MIDI_CC1_2,
    PARAM_MIDI_CC1_3,
    PARAM_MIDI_CC1_4,
    PARAM_MIDI_CC2_1,
    PARAM_MIDI_CC2_2,
    PARAM_MIDI_CC2_3,
    PARAM_MIDI_CC2_4,
    PARAM_MIDI_CC3_1,
    PARAM_MIDI_CC3_2,
    PARAM_MIDI_CC3_3,
    PARAM_MIDI_CC3_4,
    PARAM_SAMPLER_CLIP_SOURCE_BPM,
    PARAM_SAMPLER_CLIP_SYNC_LENGTH,
    PARAM_SAMPLER_CLIP_PITCH,
    PARAM_SAMPLER_CLIP_QUANT,
    PARAM_SAMPLER_CLIP_PLAY_MODE,
    PARAM_SAMPLER_CLIP_LOOP,
    PARAM_SAMPLER_CLIP_STRETCH_MODE,
    PARAM_SAMPLER_CLIP_GRAIN,
    PARAM_SAMPLER_CLIP_HOP,
    PARAM_SAMPLER_CLIP_SEARCH,
    PARAM_SAMPLER_CLIP_BEAT_RESYNC,
    PARAM_RESERVED_250,
    PARAM_RESERVED_251,
    PARAM_RESERVED_252,
    PARAM_RESERVED_253,
    PARAM_RESERVED_254,
    PARAM_RESERVED_255,
    PARAM_RESERVED_256,
    PARAM_RESERVED_257,
    PARAM_RESERVED_258,
    PARAM_RESERVED_259,
    PARAM_RESERVED_260,
    PARAM_RESERVED_261,
    PARAM_RESERVED_262,
    PARAM_RESERVED_263,
    PARAM_RESERVED_264,
    PARAM_RESERVED_265,
    PARAM_LOOPER_ARM,
    PARAM_LOOPER_LEN,
    PARAM_LOOPER_PLAY,
    PARAM_LOOPER_XFADE,
    PARAM_LOOPER_STRETCH,
    PARAM_LOOPER_PITCH,
    PARAM_LOOPER_GRAIN,
    PARAM_SAMPLER_MULTI_LOOP,
    PARAM_SAMPLER_LOOP_START,
    PARAM_WAVE_OSC1_TABLE,
    PARAM_WAVE_OSC1_POS,
    PARAM_WAVE_OSC1_START,
    PARAM_WAVE_OSC1_END,
    PARAM_WAVE_OSC1_LEVEL,
    PARAM_WAVE_OSC1_TUNE,
    PARAM_WAVE_OSC1_PHASE,
    PARAM_WAVE_OSC1_FLIP,
    PARAM_WAVE_OSC2_TABLE,
    PARAM_WAVE_OSC2_POS,
    PARAM_WAVE_OSC2_START,
    PARAM_WAVE_OSC2_END,
    PARAM_WAVE_OSC2_LEVEL,
    PARAM_WAVE_OSC2_TUNE,
    PARAM_WAVE_OSC2_PHASE,
    PARAM_WAVE_OSC2_FLIP,
    PARAM_WAVE_FRAME_INTERP,
    PARAM_WAVE_SAMPLE_INTERP,
    PARAM_WAVE_POS_UPDATE,
    PARAM_WAVE_POS_SMOOTH,
    PARAM_DELUGE_MODEL,
    PARAM_DELUGE_LEVEL,
    PARAM_DELUGE_TUNE,
    PARAM_DELUGE_FINE,
    PARAM_DELUGE_WIDTH,
    PARAM_DELUGE_PHASE,
    PARAM_DELUGE_RETRIG,

    PARAM_COMP_MODEL,
    PARAM_COMP_DETECT,
    PARAM_COMP_KNEE_DB,
    PARAM_COMP_DELUGE_SAT,
    PARAM_EXTERNAL_INPUT,

    PARAM_MIDI_FX_S1_PARAM1,
    PARAM_MIDI_FX_S1_PARAM2,
    PARAM_MIDI_FX_S1_PARAM3,
    PARAM_MIDI_FX_S1_MODEL,
    PARAM_MIDI_FX_S2_PARAM1,
    PARAM_MIDI_FX_S2_PARAM2,
    PARAM_MIDI_FX_S2_PARAM3,
    PARAM_MIDI_FX_S2_MODEL,
    PARAM_MIDI_FX_S3_PARAM1,
    PARAM_MIDI_FX_S3_PARAM2,
    PARAM_MIDI_FX_S3_PARAM3,
    PARAM_MIDI_FX_S3_MODEL,
    PARAM_MIDI_FX_S4_PARAM1,
    PARAM_MIDI_FX_S4_PARAM2,
    PARAM_MIDI_FX_S4_PARAM3,
    PARAM_MIDI_FX_S4_MODEL,

    PARAM_COUNT
};

static inline uint8_t param_id_is_reserved(param_id_t id)
{
    switch (id)
    {
        case PARAM_RESERVED_000:
        case PARAM_RESERVED_001:
        case PARAM_RESERVED_002:
        case PARAM_RESERVED_003:
        case PARAM_RESERVED_004:
        case PARAM_RESERVED_005:
        case PARAM_RESERVED_006:
        case PARAM_RESERVED_007:
        case PARAM_RESERVED_008:
        case PARAM_RESERVED_009:
        case PARAM_RESERVED_010:
        case PARAM_RESERVED_011:
        case PARAM_RESERVED_012:
        case PARAM_RESERVED_013:
        case PARAM_RESERVED_015:
        case PARAM_RESERVED_175:
        case PARAM_RESERVED_018:
        case PARAM_RESERVED_019:
        case PARAM_RESERVED_020:
        case PARAM_RESERVED_030:
        case PARAM_RESERVED_031:
        case PARAM_RESERVED_032:
        case PARAM_RESERVED_033:
        case PARAM_RESERVED_034:
        case PARAM_RESERVED_035:
        case PARAM_RESERVED_036:
        case PARAM_RESERVED_037:
        case PARAM_RESERVED_250:
        case PARAM_RESERVED_251:
        case PARAM_RESERVED_252:
        case PARAM_RESERVED_253:
        case PARAM_RESERVED_254:
        case PARAM_RESERVED_255:
        case PARAM_RESERVED_256:
        case PARAM_RESERVED_257:
        case PARAM_RESERVED_258:
        case PARAM_RESERVED_259:
        case PARAM_RESERVED_260:
        case PARAM_RESERVED_261:
        case PARAM_RESERVED_262:
        case PARAM_RESERVED_263:
        case PARAM_RESERVED_264:
        case PARAM_RESERVED_265:
            return 1U;
        default:
            return 0U;
    }
}

#ifdef __cplusplus
#define PARAM_STORE_STATIC_ASSERT static_assert
#else
#define PARAM_STORE_STATIC_ASSERT _Static_assert
#endif
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_007 == 7, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_008 == 8, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_009 == 9, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_010 == 10, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_MIX_MUTE == 14, "Mute parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_015 == 15, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_CFG_POLY_VOICES == 16, "Polyphony parameter IDs changed");
PARAM_STORE_STATIC_ASSERT(PARAM_CFG_POLY_SPREAD == 17, "Polyphony parameter IDs changed");
PARAM_STORE_STATIC_ASSERT(PARAM_DRUM_MD_MODEL == 21, "Drum MD parameter IDs changed");
PARAM_STORE_STATIC_ASSERT(PARAM_DRUM_MD_P1 == 22, "Drum MD parameter IDs changed");
PARAM_STORE_STATIC_ASSERT(PARAM_DRUM_MD_P8 == 29, "Drum MD parameter IDs changed");
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_174 == 174, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_RESERVED_175 == 175, "Reserved parameter ID changed");
PARAM_STORE_STATIC_ASSERT(PARAM_COUNT == 323, "Parameter count changed");
PARAM_STORE_STATIC_ASSERT(PARAM_MIDI_FX_S1_PARAM1 == 307, "Persistent parameter count changed");
#undef PARAM_STORE_STATIC_ASSERT

/* Persistent PARAM_COUNT-indexed payloads stop before the staged MIDI FX domain until step 7. */
#define PARAM_PERSIST_COUNT PARAM_MIDI_FX_S1_PARAM1


void param_store_init(void);
void param_store_set_staging(param_id_t id, float v);
void param_store_set_active(param_id_t id, float v);
bool param_store_commit_if_block_advanced(void);
float param_store_get_active(param_id_t id);

uint32_t param_store_get_commit_count(void);
uint32_t param_store_get_last_commit_block(void);

#ifdef __cplusplus
}
#endif
