#pragma once

#include <stdint.h>

#include "Param/param_ids.h"
#include "Track/track_types.h"

/* Canonical compile-time ownership of TONE parameters by runtime type. */
#define TONE_PARAM_CATALOG_PRISM(X) \
    X(PARAM_PRISM_OSC1_PARAM1) X(PARAM_PRISM_OSC1_PARAM2) \
    X(PARAM_PRISM_OSC1_AMOD) X(PARAM_PRISM_OSC1_MODEL) \
    X(PARAM_PRISM_VOLUME) X(PARAM_PRISM_BALANCE) X(PARAM_PRISM_TUNE) \
    X(PARAM_PRISM_DETUNE) X(PARAM_PRISM_DRIFT) X(PARAM_PRISM_PITCH_MOD1) \
    X(PARAM_PRISM_PHASE1_RESET) X(PARAM_PRISM_OSC2_PARAM1) \
    X(PARAM_PRISM_OSC2_PARAM2) X(PARAM_PRISM_OSC2_AMOD) \
    X(PARAM_PRISM_OSC2_MODEL) X(PARAM_PRISM_PITCH_MOD2)

#define TONE_PARAM_CATALOG_STACK(X) \
    X(PARAM_STACK_OSC1_LEVEL) X(PARAM_STACK_OSC2_LEVEL) \
    X(PARAM_STACK_OSC3_LEVEL) X(PARAM_STACK_NOISE_LEVEL) \
    X(PARAM_STACK_OSC1_MODEL) X(PARAM_STACK_OSC1_TUNE) \
    X(PARAM_STACK_OSC1_TIMBRE) X(PARAM_STACK_OSC1_COLOR) \
    X(PARAM_STACK_OSC2_MODEL) X(PARAM_STACK_OSC2_TUNE) \
    X(PARAM_STACK_OSC2_TIMBRE) X(PARAM_STACK_OSC2_COLOR) \
    X(PARAM_STACK_OSC3_MODEL) X(PARAM_STACK_OSC3_TUNE) \
    X(PARAM_STACK_OSC3_TIMBRE) X(PARAM_STACK_OSC3_COLOR) \
    X(PARAM_STACK_OSC_DETUNE) X(PARAM_STACK_PHASE_RESET)

#define TONE_PARAM_CATALOG_WAVE(X) \
    X(PARAM_WAVE_OSC1_POS) X(PARAM_WAVE_OSC1_START) X(PARAM_WAVE_OSC1_LEN) \
    X(PARAM_WAVE_OSC2_POS) X(PARAM_WAVE_OSC2_START) X(PARAM_WAVE_OSC2_LEN) \
    X(PARAM_WAVE_VOLUME) X(PARAM_WAVE_BALANCE) X(PARAM_WAVE_TUNE) \
    X(PARAM_WAVE_DETUNE)

#define TONE_PARAM_CATALOG_TB303(X) \
    X(PARAM_TB303_WAVE) X(PARAM_TB303_TUNE) X(PARAM_TB303_CUT) \
    X(PARAM_TB303_RES) X(PARAM_TB303_ENV_MOD) X(PARAM_TB303_DECAY) \
    X(PARAM_TB303_ACCENT) X(PARAM_TB303_SLIDE) X(PARAM_TB303_VCF_RATE)

#define TONE_PARAM_CATALOG_RAM(X) \
    X(PARAM_SAMPLER_GAIN) X(PARAM_SAMPLER_START) X(PARAM_SAMPLER_LENGTH) \
    X(PARAM_SAMPLER_MODE) X(PARAM_SAMPLER_TUNE) X(PARAM_SAMPLER_LOOP_START) \
    X(PARAM_SAMPLER_SLICE_COUNT)

#define TONE_PARAM_CATALOG_STREAM(X) \
    X(PARAM_SAMPLER_GAIN) X(PARAM_SAMPLER_CLIP_SOURCE_BPM) \
    X(PARAM_SAMPLER_CLIP_PLAY_MODE) X(PARAM_SAMPLER_CLIP_LOOP) \
    X(PARAM_SAMPLER_CLIP_STRETCH_MODE) X(PARAM_SAMPLER_CLIP_PITCH) \
    X(PARAM_SAMPLER_CLIP_SYNC_LENGTH) X(PARAM_SAMPLER_CLIP_GRAIN)

#define TONE_PARAM_CATALOG_LOOPER(X) \
    X(PARAM_LOOPER_XFADE) X(PARAM_LOOPER_STRETCH) \
    X(PARAM_LOOPER_PITCH) X(PARAM_LOOPER_GRAIN)

#define TONE_PARAM_CATALOG_MULTI(X) \
    X(PARAM_SAMPLER_GAIN) X(PARAM_SAMPLER_MULTI_LOOP)

#define TONE_PARAM_CATALOG_MIDI(X) \
    X(PARAM_MIDI_PROGRAM) X(PARAM_MIDI_CC1_1) X(PARAM_MIDI_CC1_2) \
    X(PARAM_MIDI_CC1_3) X(PARAM_MIDI_CC1_4) X(PARAM_MIDI_CC2_1) \
    X(PARAM_MIDI_CC2_2) X(PARAM_MIDI_CC2_3) X(PARAM_MIDI_CC2_4) \
    X(PARAM_MIDI_CC3_1) X(PARAM_MIDI_CC3_2) X(PARAM_MIDI_CC3_3) \
    X(PARAM_MIDI_CC3_4)

#define TONE_PARAM_CATALOG_EXTERNAL(X) \
    X(PARAM_EXT_GATE) TONE_PARAM_CATALOG_MIDI(X)

#define TONE_PARAM_CATALOG_DRUM_ANALOG(X) \
    X(PARAM_DRUM_TRX_BD_PITCH) X(PARAM_DRUM_TRX_BD_DECAY) \
    X(PARAM_DRUM_TRX_BD_HARMONICS) X(PARAM_DRUM_TRX_BD_PITCH_SWEEP) \
    X(PARAM_DRUM_TRX_BD_SWEEP_DECAY) X(PARAM_DRUM_TRX_BD_ATTACK) \
    X(PARAM_DRUM_TRX_BD_NOISE) X(PARAM_DRUM_TRX_BD_DRIVE)

#define TONE_PARAM_CATALOG_DRUM_MD(X) \
    X(PARAM_DRUM_MD_MODEL) X(PARAM_DRUM_MD_P1) X(PARAM_DRUM_MD_P2) \
    X(PARAM_DRUM_MD_P3) X(PARAM_DRUM_MD_P4) X(PARAM_DRUM_MD_P5) \
    X(PARAM_DRUM_MD_P6) X(PARAM_DRUM_MD_P7) X(PARAM_DRUM_MD_P8)

#ifdef __cplusplus
#define TONE_PARAM_CATALOG_ASSERT(id) \
    static_assert((id) < PARAM_COUNT, "tone parameter outside canonical ABI");
#else
#define TONE_PARAM_CATALOG_ASSERT(id) \
    _Static_assert((id) < PARAM_COUNT, "tone parameter outside canonical ABI");
#endif
TONE_PARAM_CATALOG_PRISM(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_STACK(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_WAVE(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_TB303(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_RAM(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_STREAM(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_LOOPER(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_MULTI(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_MIDI(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_EXTERNAL(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_DRUM_ANALOG(TONE_PARAM_CATALOG_ASSERT)
TONE_PARAM_CATALOG_DRUM_MD(TONE_PARAM_CATALOG_ASSERT)
#undef TONE_PARAM_CATALOG_ASSERT

static inline uint8_t tone_param_catalog_type_is_declared(
    track_runtime_type_t type)
{
    switch (type)
    {
        case TRACK_RUNTIME_TYPE_PRISM:
        case TRACK_RUNTIME_TYPE_STACK:
        case TRACK_RUNTIME_TYPE_WAVE:
        case TRACK_RUNTIME_TYPE_TB303:
        case TRACK_RUNTIME_TYPE_RAM:
        case TRACK_RUNTIME_TYPE_STREAM:
        case TRACK_RUNTIME_TYPE_LOOPER:
        case TRACK_RUNTIME_TYPE_MULTI:
        case TRACK_RUNTIME_TYPE_MIDI:
        case TRACK_RUNTIME_TYPE_EXTERNAL:
        case TRACK_RUNTIME_TYPE_DRUM_BD_ANALOG:
        case TRACK_RUNTIME_TYPE_DRUM_MD:
        case TRACK_RUNTIME_TYPE_FM:
            return 1U;
        default:
            return 0U;
    }
}

static inline uint8_t tone_param_catalog_contains(track_runtime_type_t type,
                                                   param_id_t id)
{
#define TONE_PARAM_CATALOG_CASE(param) case param:
    switch (type)
    {
        case TRACK_RUNTIME_TYPE_PRISM:
            switch (id) { TONE_PARAM_CATALOG_PRISM(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_STACK:
            switch (id) { TONE_PARAM_CATALOG_STACK(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_WAVE:
            switch (id) { TONE_PARAM_CATALOG_WAVE(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_TB303:
            switch (id) { TONE_PARAM_CATALOG_TB303(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_RAM:
            switch (id) { TONE_PARAM_CATALOG_RAM(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_STREAM:
            switch (id) { TONE_PARAM_CATALOG_STREAM(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_LOOPER:
            switch (id) { TONE_PARAM_CATALOG_LOOPER(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_MULTI:
            switch (id) { TONE_PARAM_CATALOG_MULTI(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_MIDI:
            switch (id) { TONE_PARAM_CATALOG_MIDI(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_EXTERNAL:
            switch (id) { TONE_PARAM_CATALOG_EXTERNAL(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_DRUM_BD_ANALOG:
            switch (id) { TONE_PARAM_CATALOG_DRUM_ANALOG(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_DRUM_MD:
            switch (id) { TONE_PARAM_CATALOG_DRUM_MD(TONE_PARAM_CATALOG_CASE)
                return 1U; default: return 0U; }
        case TRACK_RUNTIME_TYPE_FM:
            return param_id_is_fm_public(id);
        default:
            return 0U;
    }
#undef TONE_PARAM_CATALOG_CASE
}
