#pragma once

#include <stdint.h>

#define AUDIO_RECORDER_SAMPLE_RATE_HZ (48000U)
#define AUDIO_RECORDER_CHANNELS (2U)
#define AUDIO_RECORDER_BYTES_PER_FRAME (6U)
#define AUDIO_RECORDER_CAPTURE_RING_FRAMES (12001U)

typedef enum
{
    AUDIO_RECORDER_CLIENT_NONE = 0,
    AUDIO_RECORDER_CLIENT_AUDIO_REC
} audio_recorder_client_t;

typedef enum
{
    AUDIO_RECORDER_ERROR_NONE = 0,
    AUDIO_RECORDER_ERROR_INVALID_ARGUMENT,
    AUDIO_RECORDER_ERROR_INVALID_STATE,
    AUDIO_RECORDER_ERROR_RING_OVERFLOW,
    AUDIO_RECORDER_ERROR_NO_SPACE,
    AUDIO_RECORDER_ERROR_SD_IO,
    AUDIO_RECORDER_ERROR_MEDIA_CHANGED,
    AUDIO_RECORDER_ERROR_OVERDUB_UNDERRUN
} audio_recorder_error_t;
