#include "Storage/patch_product.h"
#include "Storage/persistent_patch_control.h"
#include "Storage/persistent_fatfs_io.h"
#include "Storage/persistent_key_catalog.h"
#include "Storage/sd_access_gate.h"
#include "Storage/memory_layout.h"
#include "UI/ui_track_catalog.h"
#include "Core/track_state.h"
#include "ff.h"
#include <stdio.h>
#include <string.h>
static uint8_t g_present[PATCH_PRODUCT_SLOT_COUNT],g_invalid[PATCH_PRODUCT_SLOT_COUNT];
static patch_product_metadata_t g_meta[PATCH_PRODUCT_SLOT_COUNT];
static uint16_t g_current=PATCH_PRODUCT_INVALID_SLOT;
STORAGE_STATE_SDRAM static persist_codec_patch_staging_t g_stage;
static uint32_t crc32(uint32_t crc,const uint8_t*d,uint32_t n){for(uint32_t i=0;i<n;++i){crc^=d[i];for(uint8_t b=0;b<8U;++b)crc=(crc>>1U)^(0xEDB88320UL&((uint32_t)-(int32_t)(crc&1U)));}return crc;}
static uint8_t path(char*out,uint32_t size,uint16_t slot){int n=snprintf(out,size,"0:/BRICK/PATCH/P%04u.B6C",slot);return(n>0&&(uint32_t)n<size)?1U:0U;}
static uint8_t acquire(void){if(!sd_access_gate_try_acquire(SD_ACCESS_CLIENT_PATCH))return 0U;if(!sd_access_fs_mount_if_needed()){sd_access_gate_release(SD_ACCESS_CLIENT_PATCH);return 0U;}return 1U;}
static void meta_from_patch(uint16_t slot,const persist_control_patch_t*p){patch_product_metadata_t*m=&g_meta[slot];memset(m,0,sizeof(*m));uint16_t n=p->name_length;if(n>32U)n=32U;memcpy(m->name,p->name,n);ui_track_family_t f;ui_track_type_t t;if(persist_key_family_from_disk(p->family,&f))m->family=(uint8_t)f;if(persist_key_type_from_disk(p->type,&t))m->type=(uint8_t)t;m->summary_family=m->family;m->summary_type=m->type;}
static uint8_t scan_meta(uint16_t slot){char x[48];FIL f;UINT n=0U;uint8_t h[34];if(!path(x,sizeof(x),slot)||f_open(&f,x,FA_READ)!=FR_OK)return 0U;uint8_t ok=(f_read(&f,h,sizeof(h),&n)==FR_OK&&n==sizeof(h)&&h[0]=='B'&&h[1]=='6'&&h[2]=='P'&&h[3]=='C'&&h[4]==PERSIST_CODEC_VERSION&&h[6]==PERSIST_CODEC_DOCUMENT_PATCH&&h[8]==1U);uint32_t total=(uint32_t)h[12]|((uint32_t)h[13]<<8U)|((uint32_t)h[14]<<16U)|((uint32_t)h[15]<<24U);uint32_t expected=(uint32_t)h[16]|((uint32_t)h[17]<<8U)|((uint32_t)h[18]<<16U)|((uint32_t)h[19]<<24U);if(ok&&total==(uint32_t)f_size(&f)){uint8_t chunk[256];uint32_t crc=0xFFFFFFFFUL,remaining=total-PERSIST_CODEC_HEADER_BYTES;(void)f_lseek(&f,PERSIST_CODEC_HEADER_BYTES);while(ok&&remaining){UINT want=(remaining>sizeof(chunk))?sizeof(chunk):remaining;ok=(f_read(&f,chunk,want,&n)==FR_OK&&n==want);if(ok){crc=crc32(crc,chunk,want);remaining-=want;}}ok=(ok&&~crc==expected);}uint16_t name_len=(uint16_t)h[32]|((uint16_t)h[33]<<8U);if(ok&&name_len<=PERSIST_CONTROL_PATCH_NAME_BYTES){uint8_t buf[PERSIST_CONTROL_PATCH_NAME_BYTES+8U];(void)f_lseek(&f,34U);ok=(f_read(&f,buf,name_len+8U,&n)==FR_OK&&n==name_len+8U);if(ok){persist_control_patch_t p;memset(&p,0,sizeof(p));p.name_length=name_len;memcpy(p.name,buf,name_len);p.family=(uint32_t)buf[name_len]|((uint32_t)buf[name_len+1U]<<8U)|((uint32_t)buf[name_len+2U]<<16U)|((uint32_t)buf[name_len+3U]<<24U);p.type=(uint32_t)buf[name_len+4U]|((uint32_t)buf[name_len+5U]<<8U)|((uint32_t)buf[name_len+6U]<<16U)|((uint32_t)buf[name_len+7U]<<24U);meta_from_patch(slot,&p);}}else ok=0U;(void)f_close(&f);g_present[slot]=1U;g_invalid[slot]=ok?0U:1U;return ok;}
static uint8_t load(uint16_t slot,persist_control_patch_t*out){if(slot>=PATCH_PRODUCT_SLOT_COUNT||out==NULL||!g_present[slot]||!acquire())return 0U;char x[48];persistent_fatfs_file_t f;uint8_t ok=path(x,sizeof(x),slot)&&persistent_fatfs_open_read(&f,x);if(ok){persist_codec_source_t s=persistent_fatfs_source(&f);ok=(persist_codec_decode_patch(&s,&g_stage)==PERSIST_CODEC_OK);persistent_fatfs_close(&f);}sd_access_gate_release(SD_ACCESS_CLIENT_PATCH);if(ok){*out=g_stage.patch;meta_from_patch(slot,out);g_invalid[slot]=0U;}else g_invalid[slot]=1U;return ok;}
static uint8_t store(uint16_t slot,const persist_control_patch_t*p){if(slot>=PATCH_PRODUCT_SLOT_COUNT||p==NULL||!acquire())return 0U;char x[48],tmp[52];persistent_fatfs_file_t f;uint8_t ok=path(x,sizeof(x),slot);if(ok){snprintf(tmp,sizeof(tmp),"%s.TMP",x);ok=persistent_fatfs_open_write(&f,tmp);if(ok){persist_codec_sink_t s=persistent_fatfs_sink(&f);ok=(persist_codec_encode_patch(p,&s,NULL)==PERSIST_CODEC_OK)&&(f_sync(&f.file)==FR_OK);persistent_fatfs_close(&f);}if(ok){(void)f_unlink(x);ok=(f_rename(tmp,x)==FR_OK);}else(void)f_unlink(tmp);}sd_access_gate_release(SD_ACCESS_CLIENT_PATCH);if(ok){g_present[slot]=1U;g_invalid[slot]=0U;meta_from_patch(slot,p);}return ok;}
void patch_product_init(void){memset(g_present,0,sizeof(g_present));memset(g_invalid,0,sizeof(g_invalid));memset(g_meta,0,sizeof(g_meta));g_current=PATCH_PRODUCT_INVALID_SLOT;if(!acquire())return;(void)f_mkdir("0:/BRICK");(void)f_mkdir("0:/BRICK/PATCH");for(uint16_t s=0;s<PATCH_PRODUCT_SLOT_COUNT;++s){char x[48];FILINFO i;if(path(x,sizeof(x),s)&&f_stat(x,&i)==FR_OK)(void)scan_meta(s);}sd_access_gate_release(SD_ACCESS_CLIENT_PATCH);}
uint16_t patch_product_first_empty(void){for(uint16_t s=0;s<PATCH_PRODUCT_SLOT_COUNT;++s)if(!g_present[s])return s;return PATCH_PRODUCT_INVALID_SLOT;}
patch_product_result_t patch_product_save(uint8_t e,uint16_t*out){uint16_t s=(g_current<PATCH_PRODUCT_SLOT_COUNT&&!g_invalid[g_current])?g_current:patch_product_first_empty();if(s==PATCH_PRODUCT_INVALID_SLOT)return PATCH_PRODUCT_NO_SLOT;persist_control_patch_t p;char generated[33];const char*name=(g_present[s]&&g_meta[s].name[0])?g_meta[s].name:generated;if(name==generated)(void)snprintf(generated,sizeof(generated),"T%02u %s",(unsigned)(e+1U),ui_get_track_family_short_name(track_state_get_family(e)));if(persistent_patch_control_capture(e,name,&p)!=PERSIST_CODEC_OK)return PATCH_PRODUCT_INVALID;if(!store(s,&p))return PATCH_PRODUCT_IO_ERROR;g_current=s;if(out)*out=s;return PATCH_PRODUCT_OK;}
patch_product_result_t patch_product_apply(uint16_t s,uint8_t e){if(s>=PATCH_PRODUCT_SLOT_COUNT)return PATCH_PRODUCT_INVALID;if(!g_present[s])return PATCH_PRODUCT_EMPTY;persist_control_patch_t p;if(!load(s,&p))return PATCH_PRODUCT_IO_ERROR;if(persistent_patch_control_apply(&p,e)!=PERSIST_CODEC_OK)return PATCH_PRODUCT_INVALID;g_current=s;return PATCH_PRODUCT_OK;}
patch_product_result_t patch_product_rename(uint16_t s,const char*n){persist_control_patch_t p;if(n==NULL||!load(s,&p))return PATCH_PRODUCT_IO_ERROR;size_t z=strlen(n);if(z>PERSIST_CONTROL_PATCH_NAME_BYTES)return PATCH_PRODUCT_INVALID;memset(p.name,0,sizeof(p.name));memcpy(p.name,n,z);p.name_length=(uint16_t)z;return store(s,&p)?PATCH_PRODUCT_OK:PATCH_PRODUCT_IO_ERROR;}
patch_product_result_t patch_product_delete(uint16_t s,uint16_t*out){if(s>=PATCH_PRODUCT_SLOT_COUNT)return PATCH_PRODUCT_INVALID;if(!g_present[s])return PATCH_PRODUCT_EMPTY;if(!acquire())return PATCH_PRODUCT_IO_BUSY;char x[48];FRESULT r=FR_INVALID_NAME;if(path(x,sizeof(x),s))r=f_unlink(x);sd_access_gate_release(SD_ACCESS_CLIENT_PATCH);if(r!=FR_OK&&r!=FR_NO_FILE)return PATCH_PRODUCT_IO_ERROR;g_present[s]=g_invalid[s]=0U;memset(&g_meta[s],0,sizeof(g_meta[s]));uint16_t next=PATCH_PRODUCT_INVALID_SLOT;for(uint16_t i=1;i<=PATCH_PRODUCT_SLOT_COUNT;++i){uint16_t c=(uint16_t)((s+i)%PATCH_PRODUCT_SLOT_COUNT);if(g_present[c]&&!g_invalid[c]){next=c;break;}}g_current=next;if(out)*out=next;return PATCH_PRODUCT_OK;}
patch_product_slot_state_t patch_product_slot_state(uint16_t s){return(s>=PATCH_PRODUCT_SLOT_COUNT||g_invalid[s])?PATCH_PRODUCT_SLOT_INVALID:(g_present[s]?PATCH_PRODUCT_SLOT_VALID:PATCH_PRODUCT_SLOT_EMPTY);}
uint8_t patch_product_metadata(uint16_t s,patch_product_metadata_t*out){if(out==NULL||patch_product_slot_state(s)!=PATCH_PRODUCT_SLOT_VALID)return 0U;*out=g_meta[s];return 1U;}
void patch_product_set_current(uint16_t s){if(s<PATCH_PRODUCT_SLOT_COUNT)g_current=s;}
uint16_t patch_product_get_current(void){return g_current;}
const char*patch_product_result_label(patch_product_result_t r){switch(r){case PATCH_PRODUCT_OK:return "OK";case PATCH_PRODUCT_EMPTY:return "EMPTY";case PATCH_PRODUCT_IO_BUSY:return "SD BUSY";case PATCH_PRODUCT_NO_SLOT:return "BANK FULL";case PATCH_PRODUCT_IO_ERROR:return "SD ERROR";default:return "INVALID";}}
