#include "Storage/pattern_control_bank.h"
#include "Storage/persistent_fatfs_io.h"
#include "Storage/sd_access_gate.h"
#include "ff.h"
#include <stdio.h>
#include <string.h>

#define BANKS 16U
#define SLOTS 16U
#define SET_COUNT 2U
#define INVALID_SET 0xFFU
#define COMMIT_BYTES 44U

static uint8_t g_present[BANKS][SLOTS];
static uint8_t g_active_set;
static uint8_t g_staging_set = INVALID_SET;
static uint32_t g_generation;
static uint8_t g_staging_bitmap[32];

static uint8_t valid(uint8_t b,uint8_t p){return(b<BANKS&&p<SLOTS)?1U:0U;}
static uint8_t path_for_set(char*out,uint32_t size,uint8_t set,uint8_t b,uint8_t p){int n=snprintf(out,size,"0:/PATTERN/S%u/B%02u_P%02u.B6C",set,b,p);return(n>0&&(uint32_t)n<size)?1U:0U;}
static uint8_t commit_path(char*out,uint32_t size,uint8_t set,uint8_t temporary){int n=snprintf(out,size,"0:/PATTERN/S%u/COMMIT.%s",set,temporary?"TMP":"BIN");return(n>0&&(uint32_t)n<size)?1U:0U;}
static uint8_t acquire(void){if(sd_access_gate_try_acquire(SD_ACCESS_CLIENT_PATTERN)==0U)return 0U;if(sd_access_fs_mount_if_needed()==0U){sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);return 0U;}return 1U;}
static uint32_t crc32(uint32_t crc,const uint8_t*d,uint32_t n){for(uint32_t i=0U;i<n;++i){crc^=d[i];for(uint8_t b=0U;b<8U;++b)crc=(crc>>1U)^(0xEDB88320UL&((uint32_t)-(int32_t)(crc&1U)));}return crc;}
static uint32_t le32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8U)|((uint32_t)p[2]<<16U)|((uint32_t)p[3]<<24U);}
static void put32(uint8_t*p,uint32_t v){for(uint8_t i=0U;i<4U;++i)p[i]=(uint8_t)(v>>(8U*i));}
static void scan_bitmap(uint8_t set,uint8_t*out){memset(out,0,32U);for(uint8_t b=0U;b<BANKS;++b)for(uint8_t p=0U;p<SLOTS;++p){char x[48];FILINFO i;if(path_for_set(x,sizeof(x),set,b,p)&&f_stat(x,&i)==FR_OK){uint8_t slot=(uint8_t)(b*SLOTS+p);out[slot>>3U]|=(uint8_t)(1U<<(slot&7U));}}}
static void scan_active(void){memset(g_present,0,sizeof(g_present));for(uint8_t b=0;b<BANKS;++b)for(uint8_t p=0;p<SLOTS;++p){char x[48];FILINFO i;if(path_for_set(x,sizeof(x),g_active_set,b,p)&&f_stat(x,&i)==FR_OK)g_present[b][p]=1U;}}
static void clear_set(uint8_t set){char commit[48],tmp[48];if(commit_path(commit,sizeof(commit),set,0U))(void)f_unlink(commit);if(commit_path(tmp,sizeof(tmp),set,1U))(void)f_unlink(tmp);for(uint8_t b=0;b<BANKS;++b)for(uint8_t p=0;p<SLOTS;++p){char x[48];if(path_for_set(x,sizeof(x),set,b,p))(void)f_unlink(x);}}
static uint8_t write_commit(uint8_t set,uint32_t generation,const uint8_t*bitmap){uint8_t r[COMMIT_BYTES]={0};r[0]='B';r[1]='6';r[2]='P';r[3]='B';r[4]=1U;r[5]=set;put32(&r[8],generation);memcpy(&r[12],bitmap,32U);put32(&r[40],~crc32(0xFFFFFFFFUL,r,40U));char x[48],tmp[48];FIL f;UINT n=0U;if(!commit_path(x,sizeof(x),set,0U)||!commit_path(tmp,sizeof(tmp),set,1U)||f_open(&f,tmp,FA_CREATE_ALWAYS|FA_WRITE)!=FR_OK)return 0U;uint8_t ok=(f_write(&f,r,sizeof(r),&n)==FR_OK&&n==sizeof(r)&&f_sync(&f)==FR_OK);(void)f_close(&f);if(ok){(void)f_unlink(x);ok=(f_rename(tmp,x)==FR_OK);}if(!ok)(void)f_unlink(tmp);return ok;}
static uint8_t read_commit(uint8_t set,uint32_t*out_generation){uint8_t r[COMMIT_BYTES],actual[32];char x[48];FIL f;UINT n=0U;if(!commit_path(x,sizeof(x),set,0U)||f_open(&f,x,FA_READ)!=FR_OK)return 0U;uint8_t ok=((uint32_t)f_size(&f)==sizeof(r)&&f_read(&f,r,sizeof(r),&n)==FR_OK&&n==sizeof(r));(void)f_close(&f);ok=(ok&&r[0]=='B'&&r[1]=='6'&&r[2]=='P'&&r[3]=='B'&&r[4]==1U&&r[5]==set&&r[6]==0U&&r[7]==0U&&le32(&r[40])==~crc32(0xFFFFFFFFUL,r,40U));if(ok){scan_bitmap(set,actual);ok=(memcmp(actual,&r[12],32U)==0);}if(ok)*out_generation=le32(&r[8]);return ok;}
static uint8_t store_to_set(uint8_t set,uint8_t b,uint8_t p,const persist_control_pattern_t*in){char x[48],tmp[52];persistent_fatfs_file_t f;uint8_t ok=path_for_set(x,sizeof(x),set,b,p);if(ok){snprintf(tmp,sizeof(tmp),"%s.TMP",x);ok=persistent_fatfs_open_write(&f,tmp);if(ok){persist_codec_sink_t s=persistent_fatfs_sink(&f);ok=(persist_codec_encode_pattern(in,&s,NULL)==PERSIST_CODEC_OK)&&(f_sync(&f.file)==FR_OK);persistent_fatfs_close(&f);}if(ok){(void)f_unlink(x);ok=(f_rename(tmp,x)==FR_OK);}else(void)f_unlink(tmp);}return ok;}

static uint8_t copy_file(const char*source,const char*destination){FIL in,out;UINT nr=0U,nw=0U;uint8_t buffer[512];if(f_open(&in,source,FA_READ)!=FR_OK)return 0U;if(f_open(&out,destination,FA_CREATE_ALWAYS|FA_WRITE)!=FR_OK){(void)f_close(&in);return 0U;}uint8_t ok=1U;do{if(f_read(&in,buffer,sizeof(buffer),&nr)!=FR_OK){ok=0U;break;}if(nr!=0U&&(f_write(&out,buffer,nr,&nw)!=FR_OK||nw!=nr)){ok=0U;break;}}while(nr!=0U);if(ok)ok=(f_sync(&out)==FR_OK);(void)f_close(&out);(void)f_close(&in);if(!ok)(void)f_unlink(destination);return ok;}
static uint8_t begin_staging(uint8_t copy_active,uint8_t skip_valid,uint8_t skip_bank,uint8_t skip_pattern){if(g_active_set>=SET_COUNT||g_staging_set!=INVALID_SET)return 0U;g_staging_set=(uint8_t)(g_active_set^1U);clear_set(g_staging_set);memset(g_staging_bitmap,0,sizeof(g_staging_bitmap));if(copy_active){for(uint8_t b=0U;b<BANKS;++b)for(uint8_t p=0U;p<SLOTS;++p){if(!g_present[b][p]||(skip_valid&&b==skip_bank&&p==skip_pattern))continue;char source[48],destination[48];if(!path_for_set(source,sizeof(source),g_active_set,b,p)||!path_for_set(destination,sizeof(destination),g_staging_set,b,p)||!copy_file(source,destination)){clear_set(g_staging_set);g_staging_set=INVALID_SET;return 0U;}uint8_t slot=(uint8_t)(b*SLOTS+p);g_staging_bitmap[slot>>3U]|=(uint8_t)(1U<<(slot&7U));}}return 1U;}

void pattern_control_bank_init(void){memset(g_present,0,sizeof(g_present));g_active_set=INVALID_SET;g_staging_set=INVALID_SET;g_generation=0U;if(!acquire())return;(void)f_mkdir("0:/PATTERN");(void)f_mkdir("0:/PATTERN/S0");(void)f_mkdir("0:/PATTERN/S1");uint32_t g0=0U,g1=0U;uint8_t v0=read_commit(0U,&g0),v1=read_commit(1U,&g1);if(v0&&v1&&g0!=g1){g_active_set=((int32_t)(g1-g0)>0)?1U:0U;g_generation=(g_active_set==1U)?g1:g0;}else if(v0&&!v1){g_active_set=0U;g_generation=g0;}else if(v1&&!v0){g_active_set=1U;g_generation=g1;}if(g_active_set==INVALID_SET){clear_set(0U);clear_set(1U);uint8_t blank[32]={0};if(write_commit(0U,1U,blank)){g_active_set=0U;g_generation=1U;}}if(g_active_set<SET_COUNT)scan_active();else memset(g_present,0,sizeof(g_present));sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);}
uint8_t pattern_control_bank_present(uint8_t b,uint8_t p){return valid(b,p)?g_present[b][p]:0U;}
uint8_t pattern_control_bank_load(uint8_t b,uint8_t p,persist_control_pattern_t*out){if(!valid(b,p)||out==NULL||!g_present[b][p]||!acquire())return 0U;char x[48];persistent_fatfs_file_t f;uint8_t ok=path_for_set(x,sizeof(x),g_active_set,b,p)&&persistent_fatfs_open_read(&f,x);if(ok){persist_codec_source_t s=persistent_fatfs_source(&f);ok=(persist_codec_decode_pattern(&s,(persist_codec_pattern_staging_t*)out)==PERSIST_CODEC_OK);persistent_fatfs_close(&f);}sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);if(!ok)g_present[b][p]=0U;return ok;}
uint8_t pattern_control_bank_store(uint8_t b,uint8_t p,const persist_control_pattern_t*in){if(!valid(b,p)||in==NULL||!acquire())return 0U;uint8_t ok=begin_staging(1U,1U,b,p);if(ok)ok=store_to_set(g_staging_set,b,p,in);if(ok){uint8_t slot=(uint8_t)(b*SLOTS+p);g_staging_bitmap[slot>>3U]|=(uint8_t)(1U<<(slot&7U));ok=pattern_control_bank_commit(NULL);}if(!ok)pattern_control_bank_abort(NULL);sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);return ok;}
uint8_t pattern_control_bank_delete(uint8_t b,uint8_t p){if(!valid(b,p)||!acquire())return 0U;if(!g_present[b][p]){sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);return 1U;}uint8_t ok=begin_staging(1U,1U,b,p);if(ok)ok=pattern_control_bank_commit(NULL);if(!ok)pattern_control_bank_abort(NULL);sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);return ok;}
uint8_t pattern_control_bank_clear(void){if(!acquire())return 0U;uint8_t ok=begin_staging(0U,0U,0U,0U);if(ok)ok=pattern_control_bank_commit(NULL);if(!ok)pattern_control_bank_abort(NULL);sd_access_gate_release(SD_ACCESS_CLIENT_PATTERN);return ok;}
uint16_t pattern_control_bank_count(void){uint16_t n=0U;for(uint8_t b=0;b<BANKS;++b)for(uint8_t p=0;p<SLOTS;++p)n+=g_present[b][p]?1U:0U;return n;}
uint8_t pattern_control_bank_get_ordinal_project(uint16_t ordinal,persist_control_pattern_record_t*out){if(out==NULL)return 0U;for(uint8_t b=0;b<BANKS;++b)for(uint8_t p=0;p<SLOTS;++p)if(g_present[b][p]&&ordinal--==0U){char x[48];persistent_fatfs_file_t f;memset(out,0,sizeof(*out));out->bank=b;out->pattern=p;out->present=1U;uint8_t ok=path_for_set(x,sizeof(x),g_active_set,b,p)&&persistent_fatfs_open_read(&f,x);if(ok){persist_codec_source_t s=persistent_fatfs_source(&f);ok=(persist_codec_decode_pattern(&s,(persist_codec_pattern_staging_t*)&out->content)==PERSIST_CODEC_OK);persistent_fatfs_close(&f);}return ok;}return 0U;}
uint8_t pattern_control_bank_begin_project(void){return begin_staging(0U,0U,0U,0U);}
uint8_t pattern_control_bank_put_record_project(const persist_control_pattern_record_t*r){if(r==NULL||r->present!=1U||!valid(r->bank,r->pattern)||g_staging_set>=SET_COUNT||!store_to_set(g_staging_set,r->bank,r->pattern,&r->content))return 0U;uint8_t slot=(uint8_t)(r->bank*SLOTS+r->pattern);g_staging_bitmap[slot>>3U]|=(uint8_t)(1U<<(slot&7U));return 1U;}
uint8_t pattern_control_bank_commit(void*context){(void)context;if(g_staging_set>=SET_COUNT)return 0U;const uint8_t old=g_active_set;const uint32_t next=g_generation+1U;if(!write_commit(g_staging_set,next,g_staging_bitmap))return 0U;g_active_set=g_staging_set;g_generation=next;g_staging_set=INVALID_SET;scan_active();clear_set(old);return 1U;}
void pattern_control_bank_abort(void*context){(void)context;if(g_staging_set<SET_COUNT){clear_set(g_staging_set);g_staging_set=INVALID_SET;}}
