#include "Storage/persistent_patch_control.h"
#include "Storage/persistent_key_catalog.h"
#include "Core/project_control.h"
#include "Core/track_runtime.h"
#include "Core/track_state.h"
#include "Param/param_registry.h"
#include "UI/ui_active_track_sync.h"
#include "UI/ui_track_catalog.h"
#include <string.h>

static uint8_t patch_name(const char*name,persist_control_patch_t*out){if(name==NULL)return 1U;while(out->name_length<PERSIST_CONTROL_PATCH_NAME_BYTES&&name[out->name_length]!='\0'){out->name[out->name_length]=name[out->name_length];++out->name_length;}return name[out->name_length]=='\0';}
static uint32_t patch_asset_kind(ui_track_family_t f,ui_track_type_t t){if(f!=UI_TRACK_FAMILY_SAMPLER)return 0U;if(t==UI_TRACK_TYPE_STREAM)return PERSIST_ASSET_SAMPLE_STREAM;if(t==UI_TRACK_TYPE_RAM)return PERSIST_ASSET_SAMPLE_RAM;if(t==UI_TRACK_TYPE_MULTI)return PERSIST_ASSET_MULTI;return 0U;}
persist_codec_result_t persistent_patch_control_capture(uint8_t entity,const char*name,persist_control_patch_t*out){if(out==NULL||entity>=PERSIST_CONTROL_ENTITY_COUNT)return PERSIST_CODEC_INVALID_ARGUMENT;memset(out,0,sizeof(*out));if(patch_name(name,out)==0U)return PERSIST_CODEC_CAPACITY_EXCEEDED;ui_track_family_t family=track_state_get_family(entity);ui_track_type_t type=track_state_get_type(entity);if(persist_key_family_to_disk(family,&out->family)==0U||persist_key_type_to_disk(type,&out->type)==0U)return PERSIST_CODEC_UNKNOWN_KEY;for(param_id_t id=0U;id<PARAM_COUNT;++id){persist_param_descriptor_t d;float value;if(persist_key_param_descriptor(id,&d)==0U||d.persistent==0U||d.scope!=PERSIST_PARAM_SCOPE_ENTITY||track_runtime_get_effective_param_status(entity,id)!=TRACK_RUNTIME_PARAM_ALLOWED)continue;if(param_registry_get_track_value(id,entity,&value)==0U)continue;if(out->parameter_count>=PERSIST_CONTROL_ENTITY_PARAM_COUNT)return PERSIST_CODEC_CAPACITY_EXCEEDED;persist_control_parameter_t*p=&out->parameters[out->parameter_count++];p->key=d.key;p->kind=d.kind;p->value.f32=value;}uint32_t kind=patch_asset_kind(family,type);float selector=0.0f;if(kind!=0U&&param_registry_get_track_value(PARAM_SAMPLER_SAMPLE,entity,&selector)!=0U)(void)project_control_get_logical_asset(kind,(uint16_t)(selector+0.5f),&out->asset);return persist_codec_validate_patch(out);}
persist_codec_result_t persistent_patch_control_validate(const persist_control_patch_t*p,uint8_t target){persist_codec_result_t r=persist_codec_validate_patch(p);if(r!=PERSIST_CODEC_OK)return r;if(target>=PERSIST_CONTROL_ENTITY_COUNT)return PERSIST_CODEC_INVALID_ENTITY;ui_track_family_t family;ui_track_type_t type;if(persist_key_family_from_disk(p->family,&family)==0U||persist_key_type_from_disk(p->type,&type)==0U)return PERSIST_CODEC_UNKNOWN_KEY;ui_track_config_t cfg[BRICK_ENTITY_CAPACITY];memcpy(cfg,track_state_get_configs(),sizeof(cfg));cfg[target].family=family;cfg[target].type=type;if(ui_track_catalog_type_is_available(target,family,type,cfg)==false)return PERSIST_CODEC_INVALID_ENTITY;for(uint16_t i=0U;i<p->parameter_count;++i){param_id_t id;persist_param_descriptor_t d;if(persist_key_param_from_disk(p->parameters[i].key,&id)==0U||persist_key_param_descriptor(id,&d)==0U||d.scope!=PERSIST_PARAM_SCOPE_ENTITY)return PERSIST_CODEC_UNKNOWN_KEY;}return PERSIST_CODEC_OK;}
persist_codec_result_t persistent_patch_control_apply(const persist_control_patch_t*p,uint8_t target){persist_codec_result_t r=persistent_patch_control_validate(p,target);if(r!=PERSIST_CODEC_OK)return r;uint16_t logical=0U;uint8_t has_asset=(p->asset.id!=PERSIST_CONTROL_ASSET_NONE)?1U:0U;if(has_asset){char path[PERSIST_CONTROL_ASSET_PATH_BYTES+1U];memcpy(path,p->asset.path,p->asset.path_length);path[p->asset.path_length]='\0';if(!project_control_ensure_asset(p->asset.kind,path,&logical))return PERSIST_CODEC_INVALID_ASSET;}uint8_t family[BRICK_ENTITY_CAPACITY],type[BRICK_ENTITY_CAPACITY],midi[BRICK_ENTITY_CAPACITY],source[BRICK_ENTITY_CAPACITY],input[UI_TRACK_COUNT];for(uint8_t e=0U;e<BRICK_ENTITY_CAPACITY;++e){family[e]=(uint8_t)track_state_get_family(e);type[e]=(uint8_t)track_state_get_type(e);midi[e]=track_state_get_midi_channel(e);source[e]=(uint8_t)track_state_get_midi_source(e);if(e<UI_TRACK_COUNT)input[e]=track_state_get_external_input(e);}ui_track_family_t f;ui_track_type_t t;(void)persist_key_family_from_disk(p->family,&f);(void)persist_key_type_from_disk(p->type,&t);family[target]=(uint8_t)f;type[target]=(uint8_t)t;if(track_structure_apply_entity_bulk_with_inputs(family,type,midi,source,input)==false)return PERSIST_CODEC_INVALID_ENTITY;param_registry_batch_begin();for(uint16_t i=0U;i<p->parameter_count;++i){param_id_t id;const float value=(has_asset&&persist_key_param_from_disk(p->parameters[i].key,&id)!=0U&&id==PARAM_SAMPLER_SAMPLE)?(float)logical:p->parameters[i].value.f32;param_registry_prepared_value_t prepared;float current=0.0f;if(persist_key_param_from_disk(p->parameters[i].key,&id)==0U||param_registry_prepare_value(id,value,&prepared)==0U){param_registry_batch_end();return PERSIST_CODEC_UNKNOWN_KEY;}if(param_registry_get_track_value(id,target,&current)!=0U&&current==prepared.value)continue;if(param_registry_apply_track_value(id,target,prepared.value)==0U){param_registry_batch_end();return PERSIST_CODEC_UNKNOWN_KEY;}}param_registry_batch_end();ui_active_track_sync_full_after_global_restore();return PERSIST_CODEC_OK;}
