#include "Storage/persistent_patch_control.h"
#include <string.h>
#include "App/live_parameter_audio_publication.h"
#include "IPC/live_clock_control.h"
#include "IPC/live_parameter_event.h"
#include "Mod/mod_env3_control.h"
#include "Mod/mod_destination_contract.h"
#include "Mod/mod_lfo_v1_control.h"
#include "Mod/mod_matrix_control.h"
#include "Param/param_filter.h"
#include "Storage/persistent_key_catalog.h"
#include "Storage/project_control.h"
#include "Track/audio_fx_control_state.h"
#include "Track/entity_topology.h"
#include "Track/fm_control_state.h"
#include "Track/polyphony_control.h"
#include "Track/tone_program_control.h"
#include "Track/track_sound_state.h"
#include "Track/track_state.h"
#include "Track/vca_control_state.h"
#include "Track/track_catalog.h"

static uint8_t copy_name(const char*n,persist_control_patch_t*p){if(n==NULL)return 1U;while(p->name_length<PERSIST_CONTROL_PATCH_NAME_BYTES&&n[p->name_length]){p->name[p->name_length]=n[p->name_length];++p->name_length;}return n[p->name_length]=='\0';}
static void capture_assets(uint8_t e,track_family_t f,track_type_t t,persist_control_patch_t*p){if(f==TRACK_FAMILY_SAMPLER&&(t==TRACK_TYPE_STREAM||t==TRACK_TYPE_RAM||t==TRACK_TYPE_MULTI)){if(project_control_track_asset_get(e,PROJECT_CONTROL_ASSET_SAMPLER,&p->assets[0]))p->asset_count=1U;}else if(f==TRACK_FAMILY_SYNTH&&t==TRACK_TYPE_WAVE)for(uint8_t i=0U;i<2U;++i)if(project_control_track_asset_get(e,(project_control_asset_role_t)(PROJECT_CONTROL_ASSET_WAVE_OSC1+i),&p->assets[p->asset_count]))++p->asset_count;}
static uint8_t capture_mod(uint8_t e,persist_control_modulation_t*m){track_sound_state_t s;mod_env3_control_state_t env;if(!track_sound_state_capture(e,&s)||!mod_env3_control_capture(e,&env))return 0U;for(uint8_t i=0U;i<3U;++i){float sh,tr;if(!mod_lfo_v1_get_track_param(e,i,MOD_LFO_PARAM_RATE,&m->lfos[i].rate)||!mod_lfo_v1_get_track_param(e,i,MOD_LFO_PARAM_SHAPE,&sh)||!mod_lfo_v1_get_track_param(e,i,MOD_LFO_PARAM_TRIG,&tr)||!mod_lfo_v1_get_track_param(e,i,MOD_LFO_PARAM_PHASE,&m->lfos[i].phase_offset)||!persist_key_lfo_shape_to_disk((mod_lfo_shape_t)(uint8_t)sh,&m->lfos[i].shape_key)||!persist_key_lfo_trigger_to_disk((mod_lfo_trig_mode_t)(uint8_t)tr,&m->lfos[i].trigger_key))return 0U;}m->envelope=(persist_control_mod_envelope_t){env.attack,env.decay,env.sustain,env.release,(uint8_t)(env.retrigger>=0.5f)};for(uint8_t i=0U;i<2U;++i){if(!persist_key_mod_source_to_disk(s.mod_multi_source[i][0],&m->multi[i].source_a_key)||!persist_key_mod_source_to_disk(s.mod_multi_source[i][1],&m->multi[i].source_b_key)||!persist_key_mod_source_to_disk(s.mod_slew_source[i],&m->slew[i].source_key))return 0U;m->slew[i].amount=s.mod_slew_amount[i];}for(uint8_t i=0U;i<8U;++i){track_mod_matrix_slot_t*r=&s.mod_matrix[i];persist_control_mod_route_t*d=&m->routes[i];if(!persist_key_mod_source_to_disk(r->source,&d->source_key))return 0U;d->depth=r->depth;d->enabled=r->enabled;if(r->destination==MOD_DESTINATION_NONE){d->destination_entity=e;d->destination_parameter=PERSIST_CONTROL_KEY_NONE;d->enabled=0U;}else{uint8_t de;param_id_t dp;if(!mod_destination_address_resolve(r->destination,&de,&dp)||!persist_key_mod_destination_to_disk(de,dp,&d->destination_entity,&d->destination_parameter))return 0U;}}return 1U;}

persist_codec_result_t persistent_patch_control_capture(uint8_t e,const char*n,persist_control_patch_t*p){if(p==NULL||e>=PERSIST_CONTROL_ENTITY_COUNT)return PERSIST_CODEC_INVALID_ARGUMENT;memset(p,0,sizeof(*p));track_family_t f=track_state_get_family(e);track_type_t t=track_state_get_type(e);if(!copy_name(n,p)||!persist_key_family_to_disk(f,&p->family)||!persist_key_type_to_disk(t,&p->type))return PERSIST_CODEC_UNKNOWN_KEY;capture_assets(e,f,t,p);if(f==TRACK_FAMILY_SYNTH&&t==TRACK_TYPE_FM){p->fm_present=1U;if(!fm_control_state_get(e,&p->fm))return PERSIST_CODEC_INVALID_ENTITY;}else{p->tone_present=1U;if(!tone_program_control_capture(e,&p->tone))return PERSIST_CODEC_INVALID_ENTITY;}if(!param_filter_control_capture(e,&p->filter)||!vca_control_state_capture(e,&p->vca)||!mod_env3_control_capture(e,&p->env3)||!audio_fx_control_state_capture(e,&p->audio_fx)||!polyphony_control_capture(e,&p->polyphony)||!capture_mod(e,&p->modulation))return PERSIST_CODEC_INVALID_ENTITY;return persist_codec_validate_patch(p);}
persist_codec_result_t persistent_patch_control_validate(const persist_control_patch_t*p,uint8_t target){persist_codec_result_t r=persist_codec_validate_patch(p);if(r!=PERSIST_CODEC_OK)return r;if(target>=PERSIST_CONTROL_ENTITY_COUNT)return PERSIST_CODEC_INVALID_ENTITY;track_family_t f;track_type_t t;if(!persist_key_family_from_disk(p->family,&f)||!persist_key_type_from_disk(p->type,&t))return PERSIST_CODEC_UNKNOWN_KEY;track_config_t c[BRICK_ENTITY_CAPACITY];memcpy(c,track_state_get_configs(),sizeof(c));c[target].family=f;c[target].type=t;return track_catalog_type_is_available(target,f,t,c)?PERSIST_CODEC_OK:PERSIST_CODEC_INVALID_ENTITY;}
static uint8_t restore_mod(uint8_t e,const persist_control_modulation_t*m)
{
    mod_lfo_control_bank_t lfos;
    for(uint8_t i=0U;i<3U;++i){mod_lfo_shape_t sh;mod_lfo_trig_mode_t tr;
        if(!persist_key_lfo_shape_from_disk(m->lfos[i].shape_key,&sh)
                ||!persist_key_lfo_trigger_from_disk(m->lfos[i].trigger_key,&tr))return 0U;
        lfos.lfo[i]=(mod_lfo_control_value_t){m->lfos[i].rate,(float)sh,
            (float)tr,m->lfos[i].phase_offset};}
    if(!mod_lfo_v1_restore_track(e,&lfos))return 0U;
    mod_env3_control_state_t env={m->envelope.attack,m->envelope.decay,m->envelope.sustain,m->envelope.release,(float)m->envelope.retrigger_hard};
    if(!mod_env3_control_restore(e,&env))return 0U;
    for(uint8_t i=0U;i<2U;++i){uint8_t a,b,s;if(!persist_key_mod_source_from_disk(m->multi[i].source_a_key,&a)||!persist_key_mod_source_from_disk(m->multi[i].source_b_key,&b)||!persist_key_mod_source_from_disk(m->slew[i].source_key,&s)||!mod_matrix_set_multi_source(e,i,0U,(float)a)||!mod_matrix_set_multi_source(e,i,1U,(float)b)||!mod_matrix_set_slew_source(e,i,(float)s)||!mod_matrix_set_slew_amount(e,i,m->slew[i].amount))return 0U;}
    for(uint8_t i=0U;i<8U;++i){const persist_control_mod_route_t*r=&m->routes[i];uint8_t src,de;param_id_t dp;mod_destination_address_t dst=MOD_DESTINATION_NONE;if(!persist_key_mod_source_from_disk(r->source_key,&src))return 0U;if(r->destination_parameter!=PERSIST_CONTROL_KEY_NONE){if(!persist_key_mod_destination_from_disk(r->destination_entity,r->destination_parameter,entity_topology_group_is_active(),&de,&dp))return 0U;dst=mod_destination_address_make(de,dp);}if(!mod_matrix_set_slot_state(e,i,src,dst,r->depth,r->enabled))return 0U;}
    return 1U;
}
static uint8_t assets_apply(const persist_control_patch_t*p,uint8_t e,track_family_t f,track_type_t t){if(p->asset_count==0U)return 1U;if(f==TRACK_FAMILY_SAMPLER)return p->asset_count==1U&&project_control_track_asset_restore(e,PROJECT_CONTROL_ASSET_SAMPLER,&p->assets[0]);if(f==TRACK_FAMILY_SYNTH&&t==TRACK_TYPE_WAVE){if(p->asset_count!=2U)return 0U;for(uint8_t i=0U;i<2U;++i)if(!project_control_track_asset_restore(e,(project_control_asset_role_t)(PROJECT_CONTROL_ASSET_WAVE_OSC1+i),&p->assets[i]))return 0U;return 1U;}return 0U;}
static uint8_t restore_polyphony_audio_fx(uint8_t entity,const polyphony_control_state_t*polyphony,const audio_fx_control_state_t*audio_fx){polyphony_control_state_t pp;audio_fx_control_state_t pa;live_parameter_audio_bulk_t bulk={.capture_tick=live_clock_capture_tick(),.source=LIVE_PARAMETER_EVENT_SOURCE_BULK};if(!polyphony_control_prepare(polyphony,&pp)||!audio_fx_control_state_prepare_for_polyphony(entity,audio_fx,pp.voice_count,&pa)||!polyphony_control_bulk_add(entity,&pp,&bulk)||!audio_fx_control_state_bulk_add_prepared(entity,&pa,&bulk)||!live_parameter_audio_publication_submit_bulk(&bulk))return 0U;return polyphony_control_install_prepared(entity,&pp)&&audio_fx_control_state_install_prepared(entity,&pa);}
persist_codec_result_t persistent_patch_control_apply(const persist_control_patch_t*p,uint8_t target){persist_codec_result_t r=persistent_patch_control_validate(p,target);if(r!=PERSIST_CODEC_OK)return r;uint8_t f[BRICK_ENTITY_CAPACITY],t[BRICK_ENTITY_CAPACITY],m[BRICK_ENTITY_CAPACITY],s[BRICK_ENTITY_CAPACITY],in[TRACK_COUNT];for(uint8_t e=0U;e<BRICK_ENTITY_CAPACITY;++e){f[e]=track_state_get_family(e);t[e]=track_state_get_type(e);m[e]=track_state_get_midi_channel(e);s[e]=track_state_get_midi_source(e);if(e<TRACK_COUNT)in[e]=track_state_get_external_input(e);}track_family_t family;track_type_t type;(void)persist_key_family_from_disk(p->family,&family);(void)persist_key_type_from_disk(p->type,&type);f[target]=family;t[target]=type;if(!track_structure_apply_entity_bulk_with_inputs(f,t,m,s,in)||!assets_apply(p,target,family,type))return PERSIST_CODEC_INVALID_ENTITY;if(p->fm_present){if(!fm_control_state_restore(target,&p->fm))return PERSIST_CODEC_INVALID_ENTITY;}else if(!tone_program_control_restore(target,&p->tone))return PERSIST_CODEC_INVALID_ENTITY;if(!param_filter_control_restore(target,&p->filter)||!vca_control_state_restore(target,&p->vca)||!mod_env3_control_restore(target,&p->env3)||!restore_polyphony_audio_fx(target,&p->polyphony,&p->audio_fx)||!restore_mod(target,&p->modulation))return PERSIST_CODEC_INVALID_ENTITY;return PERSIST_CODEC_OK;}
