#include "Storage/persistent_project_control.h"
#include "Storage/persistent_pattern_control.h"
#include "Core/project_control.h"
#include "Storage/pattern_live_ram.h"
#include <string.h>
persist_codec_result_t persistent_project_control_capture(persist_control_project_t*out){if(out==NULL)return PERSIST_CODEC_INVALID_ARGUMENT;memset(out,0,sizeof(*out));persist_codec_result_t r=persistent_pattern_control_capture(&out->working_pattern);if(r!=PERSIST_CODEC_OK)return r;(void)pattern_live_get_active(&out->active_pattern_bank,&out->active_pattern);if(project_control_capture_macros(&out->macros)==0U)return PERSIST_CODEC_INVALID_ENTITY;out->asset_count=project_control_capture_assets(out->assets,PERSIST_CONTROL_ASSET_COUNT);for(uint8_t e=0U;e<PERSIST_CONTROL_ENTITY_COUNT;++e){persist_control_asset_ref_t a;if(project_control_get_entity_asset(e,&a)!=0U)out->working_pattern.entities[e].asset=a.id;}return persist_codec_validate_project(out);}
persist_codec_result_t persistent_project_control_validate(const persist_control_project_t*p){return persist_codec_validate_project(p);}
persist_codec_result_t persistent_project_control_apply(const persist_control_project_t*p,uint8_t resume){persist_codec_result_t r=persist_codec_validate_project(p);if(r!=PERSIST_CODEC_OK)return r;if(project_control_apply_assets(p->assets,p->asset_count,&p->working_pattern)==0U||project_control_apply_macros(&p->macros)==0U)return PERSIST_CODEC_INVALID_ASSET;r=persistent_pattern_control_apply(&p->working_pattern,resume);if(r!=PERSIST_CODEC_OK)return r;pattern_live_set_active_state(p->active_pattern_bank,p->active_pattern,0U,0U,0U);return PERSIST_CODEC_OK;}
uint8_t persistent_project_control_apply_progressive_core(void*context,const persist_control_project_t*p){persistent_project_apply_context_t*c=context;if(c==NULL)return 0U;c->result=persistent_project_control_apply(p,c->resume_transport);return(c->result==PERSIST_CODEC_OK)?1U:0U;}
