#include "Seq/seq_timing.h"
#include <limits.h>
#include <stddef.h>
#include <string.h>
#include "Platform/memory_layout.h"
#include "Storage/groove_bank.h"
#include "Storage/persistence_workspace.h"
#include "stm32h7xx.h"

#define STEP_Q16 UINT32_C(65536)
#define MICROTIMING_DENOMINATOR 96
#define MICROTIMING_MIN (-24)
#define ALPHA_ONE INT64_C(1073741824)

SEQ_STATE_SDRAM static seq_groove_compiled_t g_blocks[SEQ_TIMING_TRACK_COUNT+1U];
static seq_groove_compiled_t *g_active[SEQ_TIMING_TRACK_COUNT],*g_scratch;
static seq_groove_compiled_t *g_pending[SEQ_TIMING_TRACK_COUNT];
static uint64_t g_pending_key[SEQ_TIMING_TRACK_COUNT];
static uint8_t g_changed[SEQ_TIMING_TRACK_COUNT],g_build_mode;
static persistence_groove_build_workspace_t *g_workspace;

static uint32_t mix32(uint32_t x){x^=x>>16U;x*=UINT32_C(0x7FEB352D);x^=x>>15U;x*=UINT32_C(0x846CA68B);return x^(x>>16U);}
static uint32_t base_q16(uint8_t b){static const uint32_t p[SEQ_TIMING_BASE_COUNT]={4U*STEP_Q16,2U*STEP_Q16,(4U*STEP_Q16)/3U,STEP_Q16,(2U*STEP_Q16)/3U,STEP_Q16/2U};return p[(b<SEQ_TIMING_BASE_COUNT)?b:SEQ_TIMING_BASE_1_16];}
static uint64_t base_q32(uint8_t b){static const uint64_t p[SEQ_TIMING_BASE_COUNT]={UINT64_C(1)<<32U,UINT64_C(1)<<31U,(UINT64_C(1)<<32U)/3U,UINT64_C(1)<<30U,(UINT64_C(1)<<32U)/6U,UINT64_C(1)<<29U};return p[(b<SEQ_TIMING_BASE_COUNT)?b:SEQ_TIMING_BASE_1_16];}
static uint32_t rd32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8U)|((uint32_t)p[2]<<16U)|((uint32_t)p[3]<<24U);}
static int64_t rdi64(const uint8_t*p){return(int64_t)((uint64_t)rd32(p)|((uint64_t)rd32(p+4U)<<32U));}
static int64_t mod64(int64_t x,int64_t m){int64_t r=x%m;return r<0?r+m:r;}

static uint64_t geom_key(const seq_track_timing_config_t*c,groove_bank_record_view_t*out){groove_bank_entry_view_t e;groove_bank_record_view_t r;if(!c||c->groove==SEQ_GROOVE_NONE||!groove_bank_get(c->groove,&e)||!groove_bank_resolve(c->groove,&r))return 0U;if(out)*out=r;return((uint64_t)e.record_crc32<<16U)|((uint64_t)c->groove<<8U)|c->base;}
static int64_t cyclic_delta(int64_t p,int64_t n,int64_t period){int64_t d=p-n,h=period/2;while(d>h)d-=period;while(d< -h)d+=period;return d;}

static uint8_t compile_geom(const seq_track_timing_config_t*c,seq_groove_compiled_t*out){groove_bank_record_view_t r;const uint64_t key=geom_key(c,&r);if(!out||!key||!r.period_q32)return 0U;memset(out,0,sizeof(*out));uint64_t count=(r.period_q32+base_q32(c->base)/2U)/base_q32(c->base);if(count<1U)count=1U;if(count>SEQ_GROOVE_MAX_PREPARED_NODES)return 0U;const uint16_t n=(uint16_t)count;int64_t best[SEQ_GROOVE_MAX_PREPARED_NODES];for(uint16_t i=0;i<n;++i){best[i]=INT64_MAX;out->velocity_q16[i]=UINT16_MAX;}const int64_t period=(int64_t)r.period_q32;for(uint16_t k=0;k<r.point_count;++k){const uint8_t*p=r.points+(uint32_t)k*GROOVE_BANK_POINT_BYTES;const int64_t pos=mod64(rdi64(p),period);const uint64_t scaled=(uint64_t)pos*n;uint16_t i=(uint16_t)((scaled+r.period_q32/2U)/r.period_q32);if(i==n)i=0U;const int64_t node=(int64_t)((r.period_q32*i)/n);const int64_t d=cyclic_delta(pos,node,period),a=d<0?-d:d;if(a>=best[i])continue;best[i]=a;out->offset_q16[i]=(int32_t)(d>>14U);uint64_t v=((uint64_t)rd32(p+8U)*UINT16_MAX+((uint64_t)127U<<15U))/((uint64_t)127U<<16U);out->velocity_q16[i]=(uint16_t)(v>UINT16_MAX?UINT16_MAX:v);}
 const int64_t pq16=(int64_t)(r.period_q32>>14U),b=pq16/n,tau=(5*b)/21;int64_t ds[SEQ_GROOVE_MAX_PREPARED_NODES],sum=0,dmin=INT64_MAX;for(uint16_t i=0;i<n;++i){uint16_t l=i?i-1U:n-1U,rr=(i+1U==n)?0U:i+1U;int64_t dl=b+out->offset_q16[i]-out->offset_q16[l],dr=b+out->offset_q16[rr]-out->offset_q16[i];ds[i]=dl<dr?dl:dr;sum+=ds[i];if(ds[i]<dmin)dmin=ds[i];}const int64_t mu=sum/n;int64_t alpha=ALPHA_ONE;if(dmin<tau){const int64_t den=100*(b-dmin);alpha=den>0?(99*(b-tau)*ALPHA_ONE)/den:0;if(alpha<0)alpha=0;if(alpha>ALPHA_ONE)alpha=ALPHA_ONE;}const int64_t mue=b+((mu-b)*alpha)/ALPHA_ONE;out->min_offset_q16=INT32_MAX;out->max_offset_q16=INT32_MIN;for(uint16_t i=0;i<n;++i){const int64_t de=b+((ds[i]-b)*alpha)/ALPHA_ONE;int64_t h=(de<mue?de:mue)-tau;if(h<0)h=0;if(h>UINT32_MAX)h=UINT32_MAX;out->random_width_q16[i]=(uint32_t)h;if((uint32_t)h>out->max_random_width_q16)out->max_random_width_q16=(uint32_t)h;if(out->offset_q16[i]<out->min_offset_q16)out->min_offset_q16=out->offset_q16[i];if(out->offset_q16[i]>out->max_offset_q16)out->max_offset_q16=out->offset_q16[i];}out->period_q32=r.period_q32;out->geometry_key=key;out->base_period_q16=(uint32_t)b;out->node_count=n;out->valid=1U;return 1U;}

void seq_timing_geometry_init(void){memset(g_blocks,0,sizeof(g_blocks));for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t)g_active[t]=&g_blocks[t];g_scratch=&g_blocks[SEQ_TIMING_TRACK_COUNT];memset(g_pending,0,sizeof(g_pending));memset(g_changed,0,sizeof(g_changed));g_build_mode=0U;g_workspace=NULL;}
void seq_timing_geometry_build_abort(void){if(g_workspace)persistence_workspace_release(PERSISTENCE_WORKSPACE_GROOVE_BUILD);g_workspace=NULL;g_build_mode=0U;memset(g_changed,0,sizeof(g_changed));}
uint8_t seq_timing_geometry_build_begin(const seq_track_timing_config_t c[SEQ_TIMING_TRACK_COUNT]){if(!c)return 0U;seq_timing_geometry_build_abort();uint8_t builds=0U;for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t){uint64_t k=geom_key(&c[t],NULL);g_pending_key[t]=k;g_changed[t]=(uint8_t)(k!=g_active[t]->geometry_key);if(g_changed[t]&&k)++builds;g_pending[t]=k?g_active[t]:NULL;}if(!builds)return 1U;if(builds==1U){g_build_mode=1U;for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t)if(g_changed[t]&&g_pending_key[t]){if(!compile_geom(&c[t],g_scratch)){seq_timing_geometry_build_abort();return 0U;}g_pending[t]=g_scratch;break;}return 1U;}g_workspace=persistence_workspace_acquire_groove_build();if(!g_workspace)return 0U;g_build_mode=2U;for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t)if(g_changed[t]&&g_pending_key[t]){if(!compile_geom(&c[t],&g_workspace->track[t])){seq_timing_geometry_build_abort();return 0U;}g_pending[t]=&g_workspace->track[t];}return 1U;}
void seq_timing_geometry_build_commit(seq_track_timing_plan_t plan[SEQ_TIMING_TRACK_COUNT]){if(!plan){seq_timing_geometry_build_abort();return;}if(g_build_mode==1U){for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t)if(g_changed[t]&&g_pending_key[t]){seq_groove_compiled_t*old=g_active[t];g_active[t]=g_scratch;g_scratch=old;break;}}else if(g_build_mode==2U){for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t)if(g_changed[t]&&g_pending_key[t]){memcpy(g_active[t],g_pending[t],sizeof(*g_active[t]));plan[t].compiled=g_active[t];}}for(uint8_t t=0;t<SEQ_TIMING_TRACK_COUNT;++t){if(g_changed[t]&&!g_pending_key[t])memset(g_active[t],0,sizeof(*g_active[t]));if(!g_pending_key[t])plan[t].compiled=NULL;}__DMB();seq_timing_geometry_build_abort();}

static int64_t nearest_grid(int64_t p,uint32_t b){if(!b)return p;int64_t q=p/(int64_t)b,r=p%(int64_t)b;if(r<0){r+=b;--q;}if((uint64_t)r*2ULL>=b)++q;return q*(int64_t)b;}
int64_t seq_timing_quantize_position_q16(const seq_track_timing_plan_t*p,int64_t x){if(!p||!p->quantize)return x;int64_t d=nearest_grid(x,p->base_period_q16)-x,s=d*p->quantize;return x+(s+(s>=0?50:-50))/100;}

typedef struct{int32_t offset;uint32_t wl,wr;uint16_t velocity;uint64_t node,node_right,num,den;} groove_sample_t;
static uint8_t sample_field(const seq_track_timing_plan_t*p,int64_t pos,groove_sample_t*out){const seq_groove_compiled_t*g=p->compiled;if(!g||!g->valid||!g->node_count||!out)return 0U;int64_t x=pos;if(p->loop_period_q16)x=mod64(x,p->loop_period_q16);else if(x<0)x=0;uint64_t period=g->period_q32>>14U;if(!period)return 0U;uint64_t scaled=(uint64_t)x*g->node_count,abs=scaled/period,rem=scaled%period;uint16_t l=(uint16_t)(abs%g->node_count),r=(l+1U==g->node_count)?0U:l+1U;out->offset=g->offset_q16[l]+(int32_t)(((int64_t)g->offset_q16[r]-g->offset_q16[l])*(int64_t)rem/(int64_t)period);int64_t v=g->velocity_q16[l]+((int64_t)g->velocity_q16[r]-g->velocity_q16[l])*(int64_t)rem/(int64_t)period;if(v<0)v=0;if(v>UINT16_MAX)v=UINT16_MAX;out->velocity=(uint16_t)v;out->wl=g->random_width_q16[l];out->wr=g->random_width_q16[r];out->node=abs;out->node_right=abs+1U;if(p->loop_period_q16){uint64_t cycle=((uint64_t)p->loop_period_q16*g->node_count+period/2U)/period;if(!cycle)cycle=1U;out->node%=cycle;out->node_right=(out->node+1U==cycle)?0U:out->node+1U;}out->num=rem;out->den=period;return 1U;}
static uint32_t global_random(uint8_t g){return(uint32_t)g*g;}
static int32_t node_random(const seq_track_timing_plan_t*p,const note_event_t*e,uint64_t node,uint32_t h){uint32_t id=p->groove_seed^(uint32_t)node^((uint32_t)(node>>32U)*UINT32_C(0x9E3779B9))^((uint32_t)(p->track+1U)<<27U)^((uint32_t)e->temporal_index<<19U)^((uint32_t)e->branch<<11U)^((uint32_t)e->note<<3U);int32_t u=(int32_t)(mix32(id)&0xFFFFU)-32768;int64_t n=(int64_t)h*p->random*global_random(p->global)*u;return(int32_t)(n/INT64_C(65536000000));}
static int32_t random_delta(const seq_track_timing_plan_t*p,const note_event_t*e,const groove_sample_t*s){if(!p->random||!p->global)return 0;int32_t a=node_random(p,e,s->node,s->wl),b=node_random(p,e,s->node_right,s->wr);return a+(int32_t)(((int64_t)(b-a)*(int64_t)s->num)/(int64_t)s->den);}
static int64_t event_position_q16(uint64_t sample,uint64_t ref,uint64_t refpos,
    uint32_t sps)
{int64_t sd=sample>=ref?(int64_t)(sample-ref):-(int64_t)(ref-sample);
 return(int64_t)refpos+(sd*INT64_C(4294967296))/sps;}
static int64_t groove_delta_q16(const seq_track_timing_plan_t*p,
    const note_event_t*e,int64_t pos,int32_t*timing_out)
{groove_sample_t s;if(!sample_field(p,pos,&s)){if(timing_out)*timing_out=0;return 0;}
 int32_t timing=(int32_t)(((int64_t)s.offset*p->timing*p->global)/10000);
 if(timing_out)*timing_out=timing;
 return(int64_t)timing+random_delta(p,e,&s);}
static uint64_t shift_sample(uint64_t sample,int64_t delta_q16,uint32_t sps)
{int64_t delta=(delta_q16*(int64_t)sps)/INT64_C(4294967296);
 if(delta>=0){const uint64_t d=(uint64_t)delta;
  return sample>UINT64_MAX-d?UINT64_MAX:sample+d;}
 const uint64_t d=(uint64_t)-delta;return sample>d?sample-d:0U;}

void seq_timing_compile(const seq_track_timing_config_t*c,uint32_t sps,uint8_t track,uint32_t seed,uint32_t loop,seq_track_timing_plan_t*p){if(!p)return;memset(p,0,sizeof(*p));if(!c)return;p->base_period_q16=base_q16(c->base);p->quantize=c->quantize<=100U?c->quantize:100U;p->timing=c->timing<=100U?c->timing:100U;p->random=c->random<=100U?c->random:100U;p->velocity=c->velocity < -100?-100:(c->velocity>100?100:c->velocity);p->global=c->global<=130U?c->global:130U;p->track=track;p->groove_seed=seed;p->loop_period_q16=loop;p->compiled=track<SEQ_TIMING_TRACK_COUNT?g_pending[track]:NULL;p->groove=p->compiled?c->groove:SEQ_GROOVE_NONE;uint32_t grid=(p->base_period_q16-1U)/2U;p->max_quantize_advance_q16=p->quantize?(uint32_t)(((uint64_t)grid*p->quantize+50U)/100U):0U;uint32_t micro=(uint32_t)(((uint64_t)(-MICROTIMING_MIN)*STEP_Q16)/MICROTIMING_DENOMINATOR);if(p->compiled){int64_t scale=(int64_t)p->timing*p->global,mn=(int64_t)p->compiled->min_offset_q16*scale/10000,mx=(int64_t)p->compiled->max_offset_q16*scale/10000;p->max_groove_timing_advance_q16=mn<0?(uint32_t)-mn:0U;uint64_t rn=(uint64_t)p->compiled->max_random_width_q16*p->random*global_random(p->global);p->max_random_advance_q16=(uint32_t)((rn+1999999U)/2000000U);p->finalizer_max_advance_q16=p->max_groove_timing_advance_q16+p->max_random_advance_q16;p->finalizer_max_delay_q16=(mx>0?(uint32_t)mx:0U)+p->max_random_advance_q16;}p->source_discovery_advance_q16=micro+p->max_quantize_advance_q16+p->finalizer_max_advance_q16;p->source_discovery_advance_samples=seq_timing_advance_samples(p->source_discovery_advance_q16,sps);p->finalizer_max_advance_samples=seq_timing_advance_samples(p->finalizer_max_advance_q16,sps);p->finalizer_max_delay_samples=seq_timing_advance_samples(p->finalizer_max_delay_q16,sps);p->enabled=(uint8_t)(p->quantize||p->compiled||p->random||p->velocity);}
uint32_t seq_timing_advance_samples(uint32_t q,uint32_t sps){uint64_t x=(uint64_t)q*sps,r=(x+UINT32_C(0xFFFFFFFF))>>32U;return r>UINT32_MAX?UINT32_MAX:(uint32_t)r;}
uint64_t seq_timing_source_timestamp(const seq_track_timing_plan_t*p,uint64_t nominal,uint64_t ordinal,int16_t micro,uint32_t sps){int64_t np=(int64_t)(ordinal<<16U),src=np+((int64_t)micro*STEP_Q16)/MICROTIMING_DENOMINATOR,q=seq_timing_quantize_position_q16(p,src),d=q-np,s=(d*(int64_t)sps)/INT64_C(4294967296);if(s>=0)return nominal+(uint64_t)s;return nominal>(uint64_t)-s?nominal-(uint64_t)-s:0U;}
void seq_timing_finalize(const seq_track_timing_plan_t*p,uint64_t ref,uint64_t refpos,uint32_t sps,note_event_t*e){if(!p||!e||!sps)return;const uint64_t source_start=e->sample_abs;const int64_t start_pos=event_position_q16(source_start,ref,refpos,sps);int32_t start_timing=0;const int64_t start_delta=groove_delta_q16(p,e,start_pos,&start_timing);if(e->kind==NOTE_EVENT_KIND_ON&&p->velocity&&p->global){groove_sample_t vs;if(sample_field(p,start_pos+start_timing,&vs)){int32_t amount=(p->velocity<0?-p->velocity:p->velocity)*p->global,target=p->velocity>=0?vs.velocity:(int32_t)UINT16_MAX-vs.velocity,factor=(int32_t)UINT16_MAX+((target-(int32_t)UINT16_MAX)*amount)/10000,v=((int32_t)e->velocity*factor+32767)/65535;if(v<1)v=1;if(v>127)v=127;e->velocity=(uint8_t)v;}}if(e->timing_class!=NOTE_EVENT_TIMING_SCHEDULED)return;const uint64_t final_start=shift_sample(source_start,start_delta,sps);if(e->kind!=NOTE_EVENT_KIND_ON||(e->flags&NOTE_EVENT_FLAG_HELD)!=0U){e->sample_abs=final_start;return;}const uint64_t source_end=source_start>UINT64_MAX-e->duration_samples?UINT64_MAX:source_start+e->duration_samples;const int64_t end_pos=event_position_q16(source_end,ref,refpos,sps);const uint64_t final_end=shift_sample(source_end,groove_delta_q16(p,e,end_pos,NULL),sps);e->sample_abs=final_start;if(final_end<=final_start){e->duration_samples=1U;return;}const uint64_t duration=final_end-final_start;e->duration_samples=(uint32_t)(duration>UINT32_MAX?UINT32_MAX:duration);}
