cmake_policy(SET CMP0007 NEW)
cmake_policy(SET CMP0057 NEW)

foreach(required CONTROL_MANIFEST AUDIO_MANIFEST NM READELF LD
                 CONTROL_ALLOWLIST AUDIO_ALLOWLIST REPORT_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "domain_symbol_audit: ${required} is required")
    endif()
endforeach()

file(MAKE_DIRECTORY "${REPORT_DIR}")
file(READ "${CONTROL_ALLOWLIST}" control_allowed_text)
file(READ "${AUDIO_ALLOWLIST}" audio_allowed_text)
string(REPLACE "\r\n" "\n" control_allowed_text "${control_allowed_text}")
string(REPLACE "\n" ";" CONTROL_ALLOWED "${control_allowed_text}")
string(REPLACE "\r\n" "\n" audio_allowed_text "${audio_allowed_text}")
string(REPLACE "\n" ";" AUDIO_ALLOWED "${audio_allowed_text}")
list(FILTER CONTROL_ALLOWED EXCLUDE REGEX "^(#.*)?$")
list(FILTER AUDIO_ALLOWED EXCLUDE REGEX "^(#.*)?$")

function(load_image manifest_path image)
    file(STRINGS "${manifest_path}" rows)
    set(objects "")
    set(records "")
    set(symbol_report "symbol|type|owner|object|source\n")
    set(section_report "")
    set(relocation_report "")
    foreach(row IN LISTS rows)
        string(REPLACE "|" ";" fields "${row}")
        list(GET fields 0 owner)
        list(GET fields 1 object)
        list(GET fields 2 source)
        list(APPEND objects "${object}")
        execute_process(COMMAND "${NM}" --format=posix "${object}"
            RESULT_VARIABLE nm_result OUTPUT_VARIABLE nm_output
            ERROR_VARIABLE nm_error)
        if(NOT nm_result EQUAL 0)
            message(FATAL_ERROR "nm failed for ${object}: ${nm_error}")
        endif()
        string(REPLACE "\r\n" "\n" nm_output "${nm_output}")
        string(REPLACE "\n" ";" nm_lines "${nm_output}")
        foreach(nm_line IN LISTS nm_lines)
            if(nm_line MATCHES "^([^ ]+) ([A-Za-z?])")
                set(symbol "${CMAKE_MATCH_1}")
                set(type "${CMAKE_MATCH_2}")
                list(APPEND records "${symbol}|${type}|${owner}|${object}|${source}")
                string(APPEND symbol_report "${symbol}|${type}|${owner}|${object}|${source}\n")
                if(owner STREQUAL "SHARED_BACKING" AND type MATCHES "^[TtWw]$")
                    set_property(GLOBAL APPEND PROPERTY AUDIT_ERRORS
                        "${image}: function ${symbol} defined by SHARED_BACKING ${source}")
                endif()
                if(owner STREQUAL "CONTRACTS" AND type MATCHES "^[BbCcDdGgSsVv]$")
                    set_property(GLOBAL APPEND PROPERTY AUDIT_ERRORS
                        "${image}: mutable ${symbol} defined by CONTRACTS ${source}")
                endif()
            endif()
        endforeach()
        execute_process(COMMAND "${READELF}" -SW "${object}"
            OUTPUT_VARIABLE sections ERROR_VARIABLE sections_error)
        execute_process(COMMAND "${READELF}" -rW "${object}"
            OUTPUT_VARIABLE relocations ERROR_VARIABLE relocations_error)
        string(APPEND section_report "\n== ${owner} | ${source} ==\n${sections}")
        string(APPEND relocation_report "\n== ${owner} | ${source} ==\n${relocations}")
    endforeach()
    file(WRITE "${REPORT_DIR}/${image}_symbols.map" "${symbol_report}")
    file(WRITE "${REPORT_DIR}/${image}_sections.txt" "${section_report}")
    file(WRITE "${REPORT_DIR}/${image}_relocations.txt" "${relocation_report}")
    set(${image}_OBJECTS "${objects}" PARENT_SCOPE)
    set(${image}_RECORDS "${records}" PARENT_SCOPE)
endfunction()

load_image("${CONTROL_MANIFEST}" CONTROL)
load_image("${AUDIO_MANIFEST}" AUDIO)

set(all_records ${CONTROL_RECORDS} ${AUDIO_RECORDS})
set(CONTROL_PRIVATE_SYMBOLS "")
set(AUDIO_PRIVATE_SYMBOLS "")
foreach(provider IN LISTS all_records)
    string(REPLACE "|" ";" provider_fields "${provider}")
    list(GET provider_fields 0 provider_symbol)
    list(GET provider_fields 1 provider_type)
    list(GET provider_fields 2 provider_owner)
    if(provider_type MATCHES "^[A-Z]$" AND NOT provider_type STREQUAL "U")
        if(provider_owner STREQUAL "CONTROL")
            list(APPEND CONTROL_PRIVATE_SYMBOLS "${provider_symbol}")
        elseif(provider_owner STREQUAL "AUDIO")
            list(APPEND AUDIO_PRIVATE_SYMBOLS "${provider_symbol}")
        endif()
    endif()
endforeach()
list(REMOVE_DUPLICATES CONTROL_PRIVATE_SYMBOLS)
list(REMOVE_DUPLICATES AUDIO_PRIVATE_SYMBOLS)
foreach(image CONTROL AUDIO)
    set(undefined_report "symbol|category\n")
    set(image_defined "")
    set(image_undefined "")
    foreach(record IN LISTS ${image}_RECORDS)
        string(REPLACE "|" ";" fields "${record}")
        list(GET fields 0 symbol)
        list(GET fields 1 type)
        if(type MATCHES "^[A-Z]$" AND NOT type STREQUAL "U")
            list(APPEND image_defined "${symbol}")
        elseif(type STREQUAL "U")
            list(APPEND image_undefined "${symbol}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES image_defined)
    list(REMOVE_DUPLICATES image_undefined)

    foreach(symbol IN LISTS image_undefined)
        if(symbol IN_LIST image_defined)
            string(APPEND undefined_report "${symbol}|same-image provider\n")
            continue()
        endif()
        set(opposite_owner "")
        if(image STREQUAL "CONTROL" AND symbol IN_LIST AUDIO_PRIVATE_SYMBOLS)
            set(opposite_owner AUDIO)
        elseif(image STREQUAL "AUDIO" AND symbol IN_LIST CONTROL_PRIVATE_SYMBOLS)
            set(opposite_owner CONTROL)
        endif()
        if(opposite_owner)
            string(APPEND undefined_report "${symbol}|FORBIDDEN ${opposite_owner} provider\n")
            set_property(GLOBAL APPEND PROPERTY AUDIT_ERRORS
                "${image}: ${symbol} requires private ${opposite_owner} provider")
        elseif(symbol IN_LIST ${image}_ALLOWED)
            string(APPEND undefined_report "${symbol}|nominative external allowlist\n")
        else()
            string(APPEND undefined_report "${symbol}|UNCATEGORIZED\n")
            set_property(GLOBAL APPEND PROPERTY AUDIT_ERRORS
                "${image}: uncategorized undefined ${symbol}")
        endif()
    endforeach()
    file(WRITE "${REPORT_DIR}/${image}_undefined.map" "${undefined_report}")

    set(response "")
    foreach(object IN LISTS ${image}_OBJECTS)
        string(APPEND response "\"${object}\"\n")
    endforeach()
    file(WRITE "${REPORT_DIR}/${image}.rsp" "${response}")
    execute_process(COMMAND "${LD}" -r -o "${REPORT_DIR}/${image}_relocatable.o"
        "@${REPORT_DIR}/${image}.rsp" RESULT_VARIABLE link_result
        OUTPUT_VARIABLE link_output ERROR_VARIABLE link_error)
    if(NOT link_result EQUAL 0)
        set_property(GLOBAL APPEND PROPERTY AUDIT_ERRORS
            "${image}: relocatable link failed: ${link_output}${link_error}")
    endif()
endforeach()

get_property(errors GLOBAL PROPERTY AUDIT_ERRORS)
if(errors)
    list(REMOVE_DUPLICATES errors)
    list(JOIN errors "\n  - " error_text)
    message(FATAL_ERROR "Domain symbol audit failed:\n  - ${error_text}")
endif()
message(STATUS "CONTROL/AUDIO object, symbol, relocation and section audit passed")
