#include "Platform/crash_library.h"
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include "IPC/control_audio_fifo_layout.h"
#include "Storage/sd_access_gate.h"
#include "ff.h"
#include "stm32h7xx_hal.h"
#include "tim.h"
#define CRASH_DIR "0:/BRICK/CRASH"
#define CRASH_MAGIC 0x43524153UL
#define CRASH_VERSION 2U
#define CRASH_EXTRA_WORDS 128U
#define CRASH_FIFO_SNAPSHOT 8U
typedef struct{char firmware_id[32],message[96],file[96],function[64];uint32_t line,code,entity,context,requested,capacity;uint32_t pc,lr,sp,xpsr,msp,psp,control,ipsr;uint32_t primask,basepri,faultmask,exc_return;uint32_t cfsr,hfsr,dfsr,afsr,mmfar,bfar;uint32_t reset_reason,hal_tick,tim5_count,fifo_head;uint32_t fifo_tail,fifo_count,fifo_overflow,fifo_invariant_failures;control_audio_command_t fifo[CRASH_FIFO_SNAPSHOT];uint32_t extra_count,extra[CRASH_EXTRA_WORDS];}crash_payload_t;
typedef struct{uint32_t magic,version,capsule_size,sequence;uint32_t payload_size,crc32,flags,reserved;crash_payload_t payload;}crash_capsule_t;
static crash_capsule_t g_capsule;static FIL g_file;static char g_path[40];static uint32_t g_next_sequence=1U;static uint8_t g_ready;static volatile uint8_t g_writer_active;
__attribute__((weak))uint32_t crash_library_capture_extra(uint32_t*words,uint32_t capacity){(void)words;(void)capacity;return 0U;}
static uint32_t capsule_crc(const crash_capsule_t*c){const uint8_t*p=(const uint8_t*)c;uint32_t crc=0xFFFFFFFFUL;for(uint32_t i=0U;i<sizeof(*c);++i){uint8_t v=(i>=offsetof(crash_capsule_t,crc32)&&i<offsetof(crash_capsule_t,crc32)+4U)?0U:p[i];crc^=v;for(uint32_t b=0U;b<8U;++b)crc=(crc>>1)^((0U-(crc&1U))&0xEDB88320UL);}return ~crc;}
static void bounded_copy(char*d,uint32_t n,const char*s){uint32_t i=0U;if(s)while(i+1U<n&&s[i]){d[i]=s[i];++i;}if(n)d[i]=0;}
static uint8_t filename_sequence(const char*n,uint32_t*out){if(n==NULL||out==NULL||strlen(n)!=12U||strcmp(&n[8],".B6C")!=0)return 0U;uint32_t v=0U;for(uint32_t i=0U;i<8U;++i){char c=n[i];uint32_t d;if(c>='0'&&c<='9')d=(uint32_t)(c-'0');else if(c>='A'&&c<='F')d=(uint32_t)(c-'A'+10);else return 0U;v=(v<<4U)|d;}*out=v;return 1U;}
void crash_library_init(void){g_ready=0U;g_next_sequence=1U;if(!sd_access_gate_try_acquire(SD_ACCESS_CLIENT_CRASH))return;if(sd_access_fs_mount_if_needed()){(void)f_mkdir("0:/BRICK");(void)f_mkdir(CRASH_DIR);DIR d;FILINFO i;if(f_opendir(&d,CRASH_DIR)==FR_OK){while(f_readdir(&d,&i)==FR_OK&&i.fname[0]!=0){uint32_t s;if(filename_sequence(i.fname,&s)&&s>=g_next_sequence)g_next_sequence=s+1U;}(void)f_closedir(&d);g_ready=1U;}}sd_access_gate_release(SD_ACCESS_CLIENT_CRASH);}
void crash_library_capture_and_persist(const brick_fatal_record_t*f){if(f==NULL||__get_IPSR()!=0U||!g_ready||g_writer_active||sd_access_storage_status()!=SD_STORAGE_STATUS_READY)return;if(!sd_access_gate_try_acquire(SD_ACCESS_CLIENT_CRASH))return;g_writer_active=1U;memset(&g_capsule,0,sizeof(g_capsule));crash_capsule_t*c=&g_capsule;c->magic=CRASH_MAGIC;c->version=CRASH_VERSION;c->capsule_size=sizeof(*c);c->sequence=g_next_sequence;c->payload_size=sizeof(c->payload);bounded_copy(c->payload.firmware_id,sizeof(c->payload.firmware_id),__DATE__ " " __TIME__);bounded_copy(c->payload.message,sizeof(c->payload.message),f->message);bounded_copy(c->payload.file,sizeof(c->payload.file),f->file);bounded_copy(c->payload.function,sizeof(c->payload.function),f->function);c->payload.line=f->line;c->payload.code=f->code;c->payload.entity=f->entity;c->payload.context=f->context;c->payload.requested=f->requested;c->payload.capacity=f->capacity;c->payload.pc=f->caller_pc;c->payload.lr=(uint32_t)(uintptr_t)__builtin_return_address(0);c->payload.sp=f->caller_sp;c->payload.xpsr=__get_xPSR();c->payload.msp=__get_MSP();c->payload.psp=__get_PSP();c->payload.control=__get_CONTROL();c->payload.ipsr=__get_IPSR();c->payload.primask=__get_PRIMASK();c->payload.basepri=__get_BASEPRI();c->payload.faultmask=__get_FAULTMASK();c->payload.cfsr=SCB->CFSR;c->payload.hfsr=SCB->HFSR;c->payload.dfsr=SCB->DFSR;c->payload.afsr=SCB->AFSR;c->payload.mmfar=SCB->MMFAR;c->payload.bfar=SCB->BFAR;c->payload.reset_reason=RCC->RSR;c->payload.hal_tick=HAL_GetTick();c->payload.tim5_count=TIM5->CNT;uint32_t h=g_control_audio_fifo_layout.head,t=g_control_audio_fifo_layout.tail;c->payload.fifo_head=h;c->payload.fifo_tail=t;c->payload.fifo_count=h-t;c->payload.fifo_overflow=g_control_audio_fifo_layout.overflow_count;c->payload.fifo_invariant_failures=g_control_audio_fifo_layout.invariant_failure_count;for(uint32_t i=0U;i<CRASH_FIFO_SNAPSHOT;++i)c->payload.fifo[i]=g_control_audio_fifo_commands[(t+i)&(CONTROL_AUDIO_FIFO_CAPACITY-1U)];c->payload.extra_count=crash_library_capture_extra(c->payload.extra,CRASH_EXTRA_WORDS);if(c->payload.extra_count>CRASH_EXTRA_WORDS)c->payload.extra_count=CRASH_EXTRA_WORDS;c->crc32=capsule_crc(c);(void)snprintf(g_path,sizeof(g_path),CRASH_DIR "/%08lX.B6C",(unsigned long)g_next_sequence);UINT w=0U;uint8_t ok=0U;if(f_open(&g_file,g_path,FA_CREATE_NEW|FA_WRITE)==FR_OK)ok=(f_write(&g_file,c,sizeof(*c),&w)==FR_OK&&w==sizeof(*c)&&f_sync(&g_file)==FR_OK&&f_close(&g_file)==FR_OK);if(ok)g_next_sequence++;g_writer_active=0U;sd_access_gate_release(SD_ACCESS_CLIENT_CRASH);}
